default_to_none = true
id = "vEGkaTAcalE_vasantOtsava-samApanam"
tags = [ "AndhraTempleFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 1
anga_type = "tithi"
anga_number = 15
kaala = "चन्द्रोदयः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Vasantotsava is an annual festival conducted for three days (Trayodashi, Chaturdashi and Pournami in the month of Chaitra). During this period, Lord Sri Venkateshwara and His Consorts Sridevi and Bhudevi are taken out in a procession and brought to the Vasanta Mandapam for abhishekam. On the third day, idols of Sri Rama, Sita, Lakshmana, Anjaneya and Sri Krishna (with Rukmini and Satyabhama) are brought to Vasanta Mandapam in procession."

[names]
sa = [ "वेङ्कटाचले वसन्तोत्सव-समापनम्",]
