default_to_none = true
id = "kAJcI_19_jagadguru_zrI~mArtaNDa_vidyAghanEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
श्रीकण्ठोऽयम् उमेशशङ्करसुतः श्वित्री वयस्यष्टमे
निर्हन्तुं गदम् अन्वहं कृतनमःसाहस्रम् अर्कं भजन्।
श्रीविद्याजपतश्च नीरुजतनुर्जातस्तथाऽष्टादशे
सन्न्यस्यन् स सुरेन्द्रदेशिकपदं प्रापत् प्रशान्तान्तरः॥४१॥
मौनी तपःस्ववशमृत्युरधिस्वपीठम् अब्दांस्त्रयोदश विहृत्य च शङ्करेन्द्रम्।
निक्षिप्य दत्तगुरुवाचम् अलब्ध सिद्धिं सद्धेमलम्बिनि तथाऽह्नि महानवम्याम्॥४२॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-19.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 7
anga_type = "tithi"
anga_number = 9
kaala = "अपराह्णः"
year_start = 3499
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "The preceptor Śrīkaṇṭha, son of Umeśa Śaṅkara, suffering from leprosy, worshipped Sūrya everyday with a thousand salutations to get rid of the disease and became healthy due to the japa of Śrīvidyā, renounced at the age of eighteen and reached with a tranquil mind the holy feet of the preceptor Surendradeśika. Avowed to rigoroaus practice of adhering to silence, austere, blessed with a virtue of opting his death day at his will, governed the seat of the Chief of Preceptors for thirteen years and after deputing Śaṅkarendra with due instructions, reached the beatitude on the ninth day of the bright fortnight in the month of Bhādrapada of the year Hevilambi."

[names]
sa = [ "काञ्ची १९ जगद्गुरु श्री-मार्तण्ड विद्याघनेन्द्र सरस्वती आराधना",]
