default_to_none = true
id = "bhAdrapdika-nAga-paJcamI"
tags = [ "SpecialPuja"]
shlokas = """
सुमन्तुरुवाच
तथा भाद्रपदे मासि पंचम्यां श्रद्वयान्वितः।
अथालेख्य नरो नागान्कृष्णवर्णादिवर्णकैः॥१॥
पूजयेद्धपुष्पैश्च सर्पिःपायसगुग्गुलैः।
तस्य तुष्टिं समायान्ति पन्नगास्तक्षकादयः॥२॥
आसप्तमात्कुलात्तस्य न भयं नागतो भवेत्।
तस्मात्सर्वप्रयत्नेन नागान् सम्पूजयेद्बुधः॥३॥
॥इति श्रीभविष्ये महापुराणे शतार्धसाहस्र्यां संहितायां ब्राह्मेपर्वणि पञ्चमीकल्पे भाद्रपदिकनागपञ्चमीव्रतवर्णनं नाम सप्तत्रिंशोऽध्यायः॥
"""
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 6
anga_type = "tithi"
anga_number = 5
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Bhadrapada Naga Panchami."

[names]
sa = [ "भाद्रपदिक-नाग-पञ्चमी",]
