default_to_none = true
id = "aGgArakI~caturthI"
tags = [ "RareDays", "Combinations",]
shlokas = """
अमावस्या तु सोमेन सप्तमी भानुना सह।
चतुर्थी भूमिपुत्रेण सोमपुत्रेण चाष्टमी।
चतस्रस्तिथयस्त्वेताः सूर्यग्रहणसन्निभाः॥
नारदीयपुर्णे ११३.६०---
यस्मिन्कस्मिन्भवेन्मासि चतुर्थी रविवारयुक्।
साङ्गारका वा विप्रेन्द्र सा विशेषफलप्रदा॥
"""
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "When `caturthI tithi` occurs on a Tuesday, it is known as `aGgArakI` and is as sacred as a solar eclipse. Particularly special day for doing puja of Ganesha/Subrahmanya with naivedyam of modakam/millet flour respectively."

[names]
sa = [ "अङ्गारकी~चतुर्थी",]
