default_to_none = true
id = "kRSNAGgAraka-caturdazI-puNyakAlaH_or_yamatarpaNam"
tags = [ "RareDays", "Combinations",]
shlokas = """
दीपोत्सवचतुर्दश्यां कार्यं तु यमतर्पणम्।
कृष्णाङ्गारचतुर्दश्याम् अपि कार्यं सदैव वा॥
कृष्णपक्षे चतुर्दश्याम् अङ्गारकदिनं यदा।
तदा स्नात्वा शुभे तोये कुर्वीत यमतर्पणम्॥
"""
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = """
`kRSNa caturdazI tithi` on a Tuesday is very sacred. Perform `tarpaNam` to Yama Dharamaraja.
एकैकेन तिलैर्मिश्रान् दद्यात् त्रींस्त्रीन् जलाञ्जलीन्।
संवत्सरकृतं पापं तत्क्षणादेव नश्यति॥
कृष्णपक्षे चतुर्दश्यां यां काञ्चित् सरितं प्रति।
यमुनायां विशेषेण नियतस्तर्पयेद् यमम्॥
यत्र क्वचन नद्यां हि स्नात्वा कृष्णचतुर्दशीम्।
सन्तर्प्य धर्मराजं तु मुच्यते सर्वकिल्बिषैः॥
दक्षिणभिमुखो भूत्वा तिलैः सव्यं समाहितः।
देवतीर्थेन देवत्वात् तिलैः प्रेताधिपो यतः॥

Perform Japa of the following names—
यमो निहन्ता पितृधर्मराजो वैवस्वतो दण्डधरश्च कालः।
प्रेताधिपो दत्तकृतानुसारी कृतान्तः (एतद् दशकृज्जपन्ति)॥

Perform `namaskAraH`—
नीलपर्वतसङ्काशो रुद्रकोपसमुद्भवः।
कालो दण्डधरो देवो वैवस्वत नमोऽस्तु ते॥
"""

[names]
sa = [ "कृष्णाङ्गारक-चतुर्दशी-पुण्यकालः/यमतर्पणम्",]
