default_to_none = true
id = "sukhA~aGgAraka-caturthI"
tags = [ "RareDays", "Combinations",]
jsonClass = "HinduCalendarEvent"
shlokas = """
सुमन्तुरुवाच---
सुखावहा च सुसुखा सौभाग्यकरणी परम्॥११॥
चतुर्थी कुरुशार्दूल रूपसौभाग्यदा शुभा।
सुखाव्रतं महापुण्यं रूपदं भाग्यदं तथा॥१२॥
सुसूक्ष्मं सुकरं धन्यमिह पुण्यसुखावहम्।
परत्र फलदं वीर दिव्यरूपप्रदायकम्॥१३॥
हसितं ललितं चोक्तं चेष्टितं च सुखावहम्।
सविलासभुजक्षेपश्चङ्क्रमश्चेष्टितं शुभम्॥१४॥
सुखाव्रतेन सर्वेषां सुखं कुरुकुलोद्वह।
कृत्येन पूजिते चेशे विघ्नेशे शिवयोः सुते॥१५॥
यदा शुक्लचतुर्थ्यां तु वारो भौमस्या वै भवेत्।
तदा सा सुखदा ज्ञेया चतुर्थी वै सुखेति च॥१६॥
पुरा मैथुनमाश्रित्य स्थिताभ्यां तु हिमाचले।
भीमोमाभ्यां महाबाहो रक्तबिन्दुश्च्युतः क्षितौ॥१७॥
मेदिन्यां स प्रयत्नेन सुखेन विधृतोऽनया।
जातोस्याः स कुजो वीर रक्तो रक्तसमुद्भवः॥१८॥
ममाङ्गतो यथोद्पन्नस्तस्मादङ्गारको ह्ययम्।
अङ्गदोङ्गोपकारश्च अङ्गानां तु प्रदो नृणाम्॥१९॥
सौभाग्यादिकरो यस्मात्तस्मादङ्गारको मतः।
भक्त्या चतुर्थ्यां नक्तेन यो वै श्रद्धासमन्वितः॥२०॥
उपवत्स्यति ना राजन्नारी वा नान्यमानसा।
पूजयेच्च कुजं भक्त्या रक्तपुष्पविलेपनैः॥२१॥
गणेशं प्रथमं भक्त्या योऽर्चयेच्छ्रद्धयान्वितः।
यस्य तुष्टः प्रयच्छेत्स सौभाग्यं रूपसम्पदम्॥२२॥
पूर्वं च कृतसङ्कल्पः स्नानं कृत्वा यथाविधि।
गृहीत्वा मृत्तिकां वन्देन्मन्त्रेणानेन भारत॥२३॥
इह त्वं वन्दिता पूर्वं कृष्णेनोद्धरता किल।
तस्मान्मे दह पाप्मानं यन्मया पूर्वसञ्चितम्॥२४॥
इमं मन्त्रं पठन्वीर आदित्याय प्रदर्शयेत्।
आदित्यरश्मिसम्पूतां गङ्गाजलकणोक्षिताम्॥२५॥
दत्त्वा मृदं शिरसि तां सर्वाङ्गेषु च योजयेत्।
ततः स्नानं प्रकुर्वीत मन्त्रयेत जलं पुनः॥२६॥
त्वमापो योनिः सर्वेषां दैत्यदानवद्यौकसाम्।
स्वेदाण्डजोद्भिदां चैव रसानां पतये नमः॥२७॥
स्नातोऽहं सर्वतीर्थेषु सर्वप्रस्रवणेषु च।
तडागेषु च सर्वेषु मानसादिसरःसु च॥२८॥
नदीषु देवखातेषु सुतीर्थेषु ह्रदेषु वै।
ध्यायन् पठन्निमं मन्त्रं ततः स्नानं समाचरेत्॥२९॥
ततः स्नात्वा शुचिर्भूत्वा गृहमागत्य वै स्पृशेत्।
दूर्वाश्वत्थौ शमीं स्पृष्ट्वा गां च मन्त्रेण मन्त्रवित्॥३०॥
दूर्वा नमस्य मन्त्रेण शुचौ भूमौ समुत्थिताम्।
त्वं दूर्वेऽमृतनामासि सर्वदेवैस्तु वन्दिता॥३१॥
वन्दिता दह तत्सर्वं दुरितं यन्मया कृतम्॥३२॥
शमीमन्त्रं प्रवक्ष्यामि तन्निबोध महीपते।
पवित्राणां पवित्रां त्वं काश्यपी प्रथिता श्रुतौ।
शमी शमय मे पापं नूनं वेत्सि धराधरान्॥३३॥
अश्वत्थालम्भने वीर मन्त्रमेतं निबोध मे।
नेत्रस्पन्दादिजं दुःखं दुःस्वप्नं दुर्विचिन्तनम्।
शक्तानां च समुद्योगमश्वत्थ त्वं क्षमस्व मे॥३४॥
इमं मन्त्रं पठन्वीर कुर्याद्वै स्पर्शनं बुधः।
ततो देव्यै तु गां दद्याद्वीरं कृत्वा प्रदक्षिणाम्।
समालभ्य तु हस्तेन ततो मन्त्रमुदीरयेत्॥३५॥
सर्वदेवमयी देवि मुनिभिस्तु सुपूजिता।
तस्मात्स्पृशामि वन्दे त्वां वन्दिता पापहा भव॥३६॥
इमं मन्त्रं पठन्वीर भक्त्या श्रद्धासमन्वितः।
प्रदक्षिणं तु यः कुर्यादर्जुनं कुरुनन्दन।
प्रदक्षिणीकृता तेन पृथिवी स्यान्न संशयः॥३७॥
एवं मौनेन चाऽऽगत्य ततो वह्निगृहं व्रजेत्।
प्रक्षाल्य च मृदा पादावाचान्तोग्निगृहं विशेत्।
होमं तत्र प्रकुर्वीत एभिर्मन्त्रपदैर्वरैः॥३८॥
शर्वाय शर्वपुत्राय क्षोण्युत्सङ्गभवाय च।
कुजाय ललिताङ्गाय लोहिताङ्गाय वै तथा॥३९॥
ॐकारपूर्वकैर्मन्त्रैः स्वाहाकारसमन्वितैः।
अष्टोत्तरशतं वीर अर्धार्धमर्धमेव च॥४०॥
एतैर्मन्त्रपदैर्भक्त्या शक्त्या वा कामतो नृप।
खादिरैः सुसमिद्भिस्तु चाऽऽज्यदुग्धैर्यवैस्तिलैः॥४१॥
भक्ष्यैर्नानाविधैश्चान्यैः शक्त्या भक्त्या समन्वितः।
हुत्वाऽऽहुतीस्ततो वीर देवं संस्थापयेत्क्षितौ॥४२॥
सौवर्णं राजतं वाऽपि शक्त्या दारुमयं नृप।
देवदारुमयं वाऽपि श्रीखण्डचन्दनैरपि॥४३॥
ताम्रे पात्रे रौप्यमये चाऽऽज्यकुङ्कुमकेसरैः।
अन्यैर्वा लोहितैर्वाऽपि पुष्पैः पत्रैः फलैरपि।
रक्तैश्च विविधैर्वीर अथ वा शक्तितोऽर्चयेत्॥४४॥
वरद्विसृजते वित्तं वित्तवान्वीर भक्तितः ।
तावद्विवर्धते पुण्यं दातुं शतसहस्रिकम्॥४५॥
अन्ये ताम्रमये पात्रे वंशजे मृन्मयेऽपि वा।
पूजयन्ति नराः शक्त्या कृत्वा कुङ्कुमकेसरैः।
पुरुषाकृतिकृतं पात्र इमं मन्त्रैः समर्चयेत्॥४६॥
अग्रिर्मूर्धेति मन्त्रेण गन्धपुष्पादिभिस्तथा।
धूपैरभ्यर्च्य विधिवद्ब्राह्मणाय प्रदीयते॥४७॥
गुडौदनं घृतं क्षीरं गोधूमाञ्छालितण्डुलान्।
अवेक्ष्य शक्तिं दद्याद्वै दरिद्रो वित्तवांस्तथा॥४८॥
वित्तशाठ्यं न कर्तव्यं विद्यमाने धने नृप।
वित्तशाठ्यं हि कुर्वाणो नामुत्र फलभाग्भवेत्॥४९॥
शतानीक उवाच
अङ्गारकेण संयुक्ता चतुर्थी नक्तभोजनैः।
उपोष्या कतिमात्रा तु उताहो सकृदेव तु॥५०॥
सुमन्तुरुवाच
चतुर्थी सा चतुर्थी सा यदाङ्गारकसंयुता।
उपोष्या तत्र तत्रैव प्रदेयो विधिवद्गुडः॥५१॥
उपोष्य नक्तेन विभो चतस्रः कुजसंयुता।
चतुर्थ्यां च चतुर्थ्यां च विधानं शृणु यादृशम्॥५२॥
सौवर्णं तु कुजं कृत्वा सविनायकमादरात्।
दशसौवर्णिकं मुख्यं दशार्धमर्धमेव च॥५३॥
सौवर्णपात्रे रौप्ये वा भक्त्या ताम्रमयेऽपि वा।
विंशत्पलानि पात्राणि विंशत्यर्धपलानि वा॥५४॥
विंशत्कर्षाणि वा वीर विंशदर्धार्धमेव वा।
रौप्यसङ्ख्यं पलं कार्यं पलार्धमर्धमेव च॥५५॥
शक्त्या वित्तैश्च भक्त्या च पात्रे ताम्रमयेऽपि तु।
प्रतिष्ठाप्य ग्रहेशं वै वस्त्रैः सम्परिवेष्टितम्।
विविधैः साधकै रक्तैः पुष्पै रक्तैः समन्वितम्॥५६॥
ब्राह्मणाय सदा दद्याद्दक्षिणासहितं नृप।
वाचकाय महाबाहो गुणिने श्रेयसे नृप॥५७॥
इति ते कथिता पुण्या तिथीनामुत्तमा तिथिः।
यामुपोष्य नरो रूपं दिव्यमाप्नोति भारत॥५८॥
कान्त्यात्रेयसमं वीरं तेजसा रविसन्निभम्।
प्रभया रविकल्पं च समीरबलसंश्रितम्॥५९॥
ईदृग्रूपं समाप्येह याति भौमसदो नृप।
प्रसादाद्विघ्ननाथस्य तथा गणपतेर्नृप॥६०॥
पठतां शृण्वतां राजन्कुर्वतां च विशेषतः।
ब्रह्महत्यादिपापानि क्षीयन्ते नात्र संशयः।
ऋद्धिं वृद्धिं तथा लक्ष्मीं लभते नात्र संशयः॥।६१॥
---श्रीभविष्ये महापुराणे शतार्धसाहस्र्यां संहितायां ब्राह्मे पर्वणि चतुर्थीकल्पे सुखावहाङ्गारकचतुर्थीव्रतनिरूपणं नामैकत्रिंशोऽध्यायतः
"""

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "`caturthI tithi` on a Tuesday is as sacred as a solar eclipse. When it occurs in `zuklapakSa`, it is called `sukhA`. Good day for doing puja of Ganesha/Subrahmanya with naivedyam of modakam/millet flour respectively."

[names]
sa = [ "सुखा-अङ्गारक-चतुर्थी",]
