default_to_none = true
id = "vijayA~bhAnusaptamI★"
tags = [ "RareDays", "Combinations",]
shlokas = """
अमावस्या तु सोमेन सप्तमी भानुना सह।
चतुर्थी भूमिपुत्रेण सोमपुत्रेण चाष्टमी।
चतस्रस्तिथयस्त्वेताः सूर्यग्रहणसन्निभाः॥
"""
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "`saptamI tithi` on a Sunday is as sacred as a solar eclipse. Particularly good for worshipping Surya. When `zukla saptamI` is present at sunrise, it is called `vijayA`."

[names]
sa = [ "विजया-भानुसप्तमी★",]
