default_to_none = true
id = "mun2aiyaDuvAr_nAyan2mAr_(52)_gurupUjai"
tags = [ "NayanmarGurupujai",]
references_secondary = [ "63 Nayanmar Saints by Swami Sivananda, published by The Divine Life Society",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "sidereal_solar_month"
priority = "paraviddha"
month_number = 12
anga_type = "nakshatra"
anga_number = 8
kaala = "प्रातः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """Between the 6th and 9th centuries, in South India, there existed 63 ardent devotees of Bhagavan Shiva, collectively known as the Nayanmars. These devout individuals, hailing from various walks of life including potters, fishermen, farmers, merchants, priests, hunters, and washermen, created devotional songs still sung by followers around the globe. Among these Nayanmars, Appar, Sambandar, and Sundarar, known for their Thevaram hymns, along with Manikkavasagar, are distinguished as the Samayacharyas or the ‘The Four’ (`nAlvar`) revered teachers of the faith. They were instrumental in promoting the Shaiva Siddhanta philosophy and culture, effectively challenging the spread of Jainism and Buddhism. Their teachings centered around the concept that Shiva embodies love, and that embracing love for all beings and existence is essential in connecting with Shiva, the Supreme Being.

This Nayanmar, a Vellala from Tiru Nidur in the Chola kingdom, was renowned for his profound devotion to Bhagavan Shiva and His devotees. Known for his strength and skill in combat, he became a beacon of hope for those in distress, often aiding the weak and defeated. He offered his services as a professional fighter (fencer), setting a wage for his involvement. Significantly, he used the earnings from these endeavors to feed and care for devotees of Bhagavan Shiva, thus earning the moniker ‘Munaiyaduvar’. His life was marked by two key lessons: first, the use of his God-given talent in fencing was always in defense of righteousness, supporting those who were oppressed or downtrodden. Second, he consistently dedicated the fruits of his efforts to serving the Bhagavan, aligning with the core teachings of the Bhagavad Gita and various saints."""

[names]
ta = [ "mun2aiyaDuvAr nAyan2mAr (52) gurupUjai",]
