default_to_none = true
id = "sAmba-dazamI_or_sUryapUjA"
tags = [ "LessCommonFestivals", "OdishaTempleFestivals",]
references_secondary = [ "https://hindupad.com/samba-dashami-2009-samba-dasami-or-surya-puja-in-orissa/",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 11
anga_type = "tithi"
anga_number = 10
jsonClass = "HinduCalendarEventTiming"

[description]
en = "`sAmba`, the son of Sri Krishna, was cured of leprosy after performing `tapaH` to propitiate Surya Bhagavan. `sAmba` was the son of Bhagavan Sri Krishna and Jambavan's daughter, Jambavati. He was afflicted with leprosy owing to some sins accumulated in previous births. Deeply remorseful, he approached his father, Sri Krishna. Bhagavan pointed out that there was no other recourse to curing this disease other than the `upAsana` of `sUrya bhagavAn` and narrated the method to propitiate Surya Bhagavan and the story of a `caNDAla strI` who had gotten cured from disease by Surya Bhagavan. `sAmba` then propitiated Surya Bhagavan with bhakti. Pleased with his devotion, Surya Bhagavan revealed to him the `AryAdvAdazakam` stuti (http://stotrasamhita.net/wiki/Dwadasharya_Surya_Stuti). Performing `pArAyaNam` of this stuti, `sambA` was cured of this debilitating disease."
ta = "ஜகத்குருவான பகவான் ஶ்ரீக்ருஷணருக்கும் ஜாம்பவானது புத்ரியான ஜாம்பவதிக்கும் பிறந்தவர் ஸாம்பன்.  அவருக்கு ஜன்மாந்தரத்தில் செய்த பாபத்தால் குஷ்டரோகம் பாதித்தது. அதனால் மிகவும் வருந்திய அவர் தந்தையான ஶ்ரீக்ருஷ்ணரையே ஶரணடைந்தார். பகவானும் ஸூர்ய-உபாஸனையைத் தவிர இதற்கு வேறு உபாயமில்லை என்று கூறி ஸூர்யனை உபாஸிக்கும் முறைகளை உபதேஶித்து ஸூர்யபகவானால் நோயிலிருந்து குணமடைந்த சண்டாள ஸ்த்ரீயின் வ்ருத்தாந்தத்தையும் கூறினார். பிறகு ஸாம்பன் பக்தியுடன் ஸூர்யபகாவானை உபாஸித்தார். இதனால் மகிழ்ந்த ஸூர்ய பகவான் ஸாம்பனுக்கு \"ஆர்யாத்வாதஶகம்\" (http://stotrasamhita.net/wiki/Dwadasharya_Surya_Stuti) என்ற இந்த ஸ்துதியை அருளினார். அதை பாராயணம் செய்து மஹாரோகமான குஷ்டரோகத்திலிருந்து குணமடைந்தார்."

[names]
sa = [ "साम्ब-दशमी (सूर्यपूजा)",]
