default_to_none = true
id = "sthAlIpAkaH_1"
tags = [ "MonthlyFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 0
anga_type = "tithi"
anga_number = 1
priority = "puurvaviddha"
kaala = "पूर्वाह्णः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "`sthAlIpakaH` is an important fortnightly ritual, involving the offering of `haviSyAnna` to `agni`, with the offering being cooked on the fire itself."

[names]
sa = [ "स्थालीपाकः",]
