default_to_none = true
id = "tyAgarAja~jayantI"
tags = [ "MahapurushaEvents", "CommonFestivals",]
references_secondary = [ "Vaidikasri May 2017",]
shlokas = """
कामक्रोधादिरहितं रामभक्तशिरोमणिम्।
त्यागराजगुरुं वन्दे सङ्गीताब्धिं कलानिधिम्॥
"""
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 2
anga_type = "tithi"
anga_number = 7
year_start = 4868
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "त्यागराज-जयन्ती",]
