default_to_none = true
id = "kapAlI adhikAra nandi"
tags = [ "TamilnaduTempleFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
anchor_festival_id = "kar2pagAmbAL–kapAlIzvarar tirukkalyANam"
offset = -7
jsonClass = "HinduCalendarEventTiming"

[names]
ta = [ "kapAlI adhikAra nandi",]
sa = [ "कपाल्यधिकार-नन्दी",]
