default_to_none = true
id = "mAgha-snAnapUrtiH"
tags = [ "SpecialSnanam",]
references_secondary = [ "Narada Mahapuranam",]
shlokas = """
देवैस्तेजः परिक्षिप्तं माघमासे स्वकं जले।
तस्माज्जलं माघमासे पावनं हि विशेषतः॥
---नारदमहापुराणे उत्तरार्धे ३१.१०
तन्नास्ति पातकं यत्तु माघस्नानं न शोधयेत्।
अग्निप्रवेशादधिकं माघोषस्येव मज्जनम्॥
---नारदमहापुराणे उत्तरार्धे ३१.१६
पावका इव दीप्यन्ते माघस्नानैर्नरोत्तमाः।
विमुक्ताः सर्वपापेभ्यो मेघेभ्य इव चन्द्रमाः॥
---पाद्मे महापुराणे उत्तरखण्डे १२६.३२
एकविंशकुलैः सार्द्धं भोगान् भुक्त्वा यथेप्सितान्।
माघमास्युषसि स्नात्वा विष्णुलोकं स गच्छति॥
---श्रीभविष्यमहापुराणे उत्तरपर्वणि १२२.३४
कावेरी तुङ्गभद्रा च यास्तथान्याः समुद्रगाः।
तासु स्नायी नरो याति स्वर्गलोकं विकल्मषः॥
---नारदमहापुराणे उत्तरार्धे ६३.३०

सूर्यार्घ्यप्रदानम्---
तपस्यर्कोदये नद्यां स्नात्वाऽहं विधिपूर्वकम्।
माधवाय ददामीदम् अर्घ्यं धर्मार्थ-सिद्धिदम्॥
माधवाय नमः इदमर्घ्यम्। माधवाय नमः इदमर्घ्यम्। माधवाय नमः इदमर्घ्यम्।

सवित्रे प्रसवित्रे च परं धाम्ने नमोऽस्तु ते।
त्वत्तेजसा परिभ्रष्टं पापं यातु सहस्रधा॥
सवित्रे नमः इदमर्घ्यम्। सवित्रे नमः इदमर्घ्यम्। सवित्रे नमः इदमर्घ्यम्।

यदनेकजनुर्जन्यं यज्ज्ञानाज्ञानतः कृतम्।
त्वत्तेजसा हतं चास्तु तत्तु पापं सहस्रधा॥
सवित्रे नमः इदमर्घ्यम्। सवित्रे नमः इदमर्घ्यम्। सवित्रे नमः इदमर्घ्यम्।

प्रार्थना----
दिवाकर जगन्नाथ प्रभाकर नमोस्तु ते।
परिपूर्णं कुरुष्वेदं माघस्नानं महाव्रतम्॥
"""
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 11
anga_type = "tithi"
anga_number = 30
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "माघ-स्नानपूर्तिः",]
