default_to_none = true
id = "mAgha-mAsa-samApanam"
tags = [ "SpecialDays", "SpecialPeriodEnd",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 11
anga_type = "tithi"
anga_number = 30
priority = "paraviddha"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "`mAgha-mAsaH` ends today"

[names]
sa = [ "माघ-मास-समापनम्",]
