id = "gilgit-vidrohaH"
jsonClass = "HinduCalendarEvent"

[timing]
month_type = "gregorian"
anga_type = "day"
month_number = 10
anga_number = 31
year_start = 1947
year_start_era = "gregorian"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """
On this day, Gilgit was lost to betrayal by muslim-dominated Gilgit Scouts.

Brigadier Ghansara Singh was appointed the governor of the Gilgit region by the Maharaja in August of 1947. He was to defend the region with help of Gilgit Scouts, the armed militia which owed its allegiance to Maharaja. Most of the soldiers in this body were recruited from Hunza and Nagar principalities. Ghansara Singh also had under him soldiers of 6 J&K Infantry, with its Battalion headquarters at Bunji, 54 kilometers from Gilgit, on the road to Srinagar. The battalion had Sikhs and Muslims in equal proportion. Most of the Muslims in the battalion were from Poonch. Sensing trouble, Ghansara Singh called for help from Srinagar, but a Muslim officer who manned the telegraph office at Gilgit did not forward the messages!

On the night of 31 Oct- 01 Nov 1947 British Officers stationed in Gilgit, under the employment of Maharaja, and Muslim soldiers and officers of Gilgit Scouts treacherously captured Ghansara Singh. The 35 Sikhs of the 6 J&K Infantry at Janglot were attacked by Muslim soldiers of their own unit! Only 1 survived the massacre by jumping into the icy cold Indus river.

The other Sikh troops at Bunji got information of the massacre and tried to slip away, but most were ruthlessly hunted and killed by Gilgit Scouts and their own brothers-in-arms. The commander at Bunji, Lt Col Abdul Majid Khan, however, was a rare Muslim officer who remained loyal to Maharaja and was put under arrest. On 03 Nov 1947, Maj Brown of Gilgit Scouts hoisted the Pakistani Flag in the Scout Lines and declared for Pakistan.
"""

[names]
sa = [ "गिल्जित-द्रोहः",]
