default_to_none = true
id = "kAJcI_23_jagadguru_zrI~saccitsukhEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
श्रीचिक्काकुलसोमणार्यतनयः सोऽयं गिरीशः पुरा
सन्न्यस्तः परिपूर्णबोधगुरुणा सच्चित्सुखः षण्मुखम्।
ध्यायन् कालविदं सुदूरम् उदधौ प्रोष्यार्यभट्टाभिधं
प्रत्यावृत्तम् अधाद् अथास्तिकम् अनुष्ठाप्योदितं निष्क्रयम्॥४८॥
चित्सुखं विनिवेश्य स्वे पदे सच्चित्सुखः सिते।
खरे खरांशौ वृषगे सप्तम्यां सिद्धिम् आप सः॥४९॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-23.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 3
anga_type = "tithi"
anga_number = 7
kaala = "अपराह्णः"
year_start = 3613
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Son of Śrī Cikkākula Somanārya, named Girīśa earlier. initiated with the tile Saccitsukha by Paripūrṇabodha; an ardent devotee of Lord Subrahmanya, He made pious the astrologer Āryabhaṭṭa by making him carry out the expiatory rite for his long voyage (on sea). He, Saccitsukha, having instituted Citsukha in his place, attained siddhi on the seventh day of the bright fortnight of the month of Vṛṣabha in the year Khara."

[names]
sa = [ "काञ्ची २३ जगद्गुरु श्री-सच्चित्सुखेन्द्र सरस्वती आराधना",]
