default_to_none = true
id = "kAJcI_39_jagadguru_zrI~saccidvilAsEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
कान्यकुब्जकमलेश्वरात्मजः श्रीपतिः श्रितयमश्च शङ्करात्।
अध्युवास गुरुपीठम् अश्रमं बाल(३३)वर्षधृतिशील आश्रमी॥८१॥
आनन्दवर्धनमुखैः अभिरूपवर्यैः आराधिताङ्घ्रिः अधिपद्मपुरं चिराय।
अध्युष्य काञ्चिम् उपगम्य च नन्दनाब्दे सिद्धिं गतो निशि नृसिंहजयन्तिकायाः॥८२॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-39.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 2
anga_type = "tithi"
anga_number = 14
kaala = "अपराह्णः"
year_start = 3974
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Son of Kamaleśvara Śrīpati, having received the initiation from Śaṅkara, the sage (preceptor) with an ability to endure heat and cold easily, remained in the guru Pīṭha. Adorned by the erudites like Ānandavardhana etc., residing at Padmapuram for a long time and then, having reached Kāñci, He attained siddhi on the night of Narasimha Jayanti in the year Nandana. This saint Saccidvilāsa, adored by Śrī Ānandavardhana, Muktākaṇa, Śivaswāmi and Rājānakaratnākara remained in the Pīṭha for thirty-three years and attained siddhi near Kāñci on the full moon day of Vaiśāka month in the year Nandana."

[names]
sa = [ "काञ्ची ३९ जगद्गुरु श्री-सच्चिद्विलासेन्द्र सरस्वती आराधना",]
