default_to_none = true
id = "bagalAmukhI~jayantI"
tags = [ "Dashamahavidya",]
references_secondary = [ "Ashtanga Panchangam",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 2
anga_type = "tithi"
anga_number = 4
kaala = "मध्यरात्रिः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Goddess Bagalamukhi is 8th of the Dasha Maha Vidyas."

[names]
sa = [ "बगलामुखी-जयन्ती", "पीताम्बर-जयन्ती",]
