default_to_none = true
id = "nandOtsavaH"
tags = [ "NorthIndiaTempleFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
anchor_festival_id = "zrIkRSNajanmASTamI"
offset = 1
jsonClass = "HinduCalendarEventTiming"

[description]
en = """Since Lord Krishna was taken by Sri Vasudeva to Gokul in the night, the next day is celebrated as Nandotsava in "Vraja Kshetra", which includes a number of places where Lord Krishna enacted his leelas, including Mathura, Kamyavan, Govardhan, Gokul, etc. This festival is widely celebrated in temples as the 2nd of Janmashtami Mahotsav."""

[names]
sa = [ "नन्दोत्सवः",]
