default_to_none = true
id = "vaizAkha-(adhika)-amAvAsyA"
tags = [ "AmavasyaDays",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "`amAvAsyA` of the `adhika vaizAkha` month."

[names]
sa = [ "वैशाख-(अधिक)-अमावास्या",]
