default_to_none = true
id = "zrAvaNa-(adhika)-amAvAsyA"
tags = [ "AmavasyaDays",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "`amAvAsyA` of `adhika zrAvaNa` month."

[names]
sa = [ "श्रावण-(अधिक)-अमावास्या",]
