default_to_none = true
id = "zrAvaNa-(adhika)_(karkaTa)_amAvAsyA"
tags = [ "AmavasyaDays",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "`amAvAsyA` of `adhika zravaNa` month, which also falls in the sidereal solar month of `kaTaka`."

[names]
sa = [ "श्रावण-(अधिक) (कर्कट) अमावास्या",]
