default_to_none = true
id = "ASADha-(adhika)-amAvAsyA"
tags = [ "AmavasyaDays",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "`amAvAsyA` of `adhika ASADha` month."

[names]
sa = [ "आषाढ-(अधिक)-अमावास्या",]
