default_to_none = true
id = "alabhya-nakSatra-amAvAsyA"
tags = [ "AmavasyaDays",]
shlokas = """
विष्णुपुराणे---
अमावास्या यदा मैत्रविशाखास्वातियोगिनी।
श्राद्धे पितृगणस्तृप्तिमवाप्नोत्यष्टवार्षिकीम्॥
अमावास्या यदा पुष्ये रौद्रेऽथः पुनर्वसौ।
द्वादशाब्दं तदा तृप्तिं प्रयान्ति पितरोऽर्चिताः॥
वासवाजैकपादृक्षे पितॄणां तृप्तिमिच्छताम्।
वारुणे चाप्यमावास्या देवानामपि दुर्लभा।
नवस्वृक्षेष्वमावास्या यदैतेष्ववनीपते॥
"""
references_primary = [ "Vaidyanatha Dikshitiyam",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "It is said in Vishnupuranam that when Amavasya overlaps with one of nine nakshatras---Anuradha, Vishakha, Swati, Pushya, Ardra, Punarvasu, Shravishtha, Purvaproshthapada, or Shatabhishak---it is sacred even for Devas. For instance, Shraaddha done on an Amavasya joined with Anuradha, Vishakha, Swati keeps the `pitr`s satisfied for eight years. Likewise, on Pushya, Ardra and Punarvasu, the `pitr`s satisfied for twelve years."

[names]
sa = [ "अलभ्य-नक्षत्र-अमावास्या",]
