default_to_none = true
id = "mAgha-zraviSThA-amAvAsyA"
tags = [ "AmavasyaDays",]
jsonClass = "HinduCalendarEvent"
shlokas = """
विष्णुपुराणम्---
माघासिते पञ्चदशी कदाचिदुपैति योगं यदि वारुणेन।
ऋक्षेण कालः स वरः पितॄणां नह्यल्पपुण्यैर्नृप लभ्यतेऽसौ॥
गायन्ति केचित् पितरः कदा नु वर्षा मघा तृप्तिमवाप्य भूयः।
माघासितान्ते शुभतीर्थतोयैर्यास्याम तृप्तिं तनयादिदत्तैः॥
काले धनिष्ठा यदि नाम तस्मिन् भवेत्तु भूपाल तदा पितृभ्यः।
दत्तं जलान्नं प्रददाति तृप्तिं वर्षायुतं तत्कुलजैर्मनुष्यैः॥
"""
references_primary = [ "Vaidyanatha Dikshitiyam",]

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "It is said in the Vishnu Puranam, that if the Amavaysa of Magha month coincides with the nakashatra of Varuna, i.e. Shatabhishak, the `pitR`s are overjoyed, and do not obtain it unless they have accumulated a lot of punya! If it is Shravishtha, then the `pitR`s are satisfied for (ten) thousand years."

[names]
sa = [ "माघ-शरविष्ठा-अमावास्या",]
