default_to_none = true
id = "puSkalA-amAvAsyA"
tags = [ "AmavasyaDays",]
shlokas = """
स्मृत्यन्तरे---
अमा सोमेन भौमेन गुरुणा वा युता यदि।
सा तिथिः पुष्कला नाम सूर्यग्रहणसन्निभा॥
"""
references_primary = [ "Vaidyanatha Dikshitiyam",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "It is said in the Smrtis, that if Amavaysa falls on a Monday, Tuesday or Thursday, such a tithi is given the appellation `puSkalA` and is as sacred as a solar eclipse."

[names]
sa = [ "पुष्कला-अमावास्या",]
