default_to_none = true
id = "rudra~pazupati_nAyan2mAr_(17)_gurupUjai"
tags = [ "NayanmarGurupujai",]
references_secondary = [ "63 Nayanmar Saints by Swami Sivananda, published by The Divine Life Society",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "sidereal_solar_month"
priority = "paraviddha"
month_number = 6
anga_type = "nakshatra"
anga_number = 1
kaala = "प्रातः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """
Between the 6th and 9th centuries, in South India, there existed 63 ardent devotees of Bhagavan Shiva, collectively known as the Nayanmars. These devout individuals, hailing from various walks of life including potters, fishermen, farmers, merchants, priests, hunters, and washermen, created devotional songs still sung by followers around the globe. Among these Nayanmars, Appar, Sambandar, and Sundarar, known for their Thevaram hymns, along with Manikkavasagar, are distinguished as the Samayacharyas or the ‘The Four’ (`nAlvar`) revered teachers of the faith. They were instrumental in promoting the Shaiva Siddhanta philosophy and culture, effectively challenging the spread of Jainism and Buddhism. Their teachings centered around the concept that Shiva embodies love, and that embracing love for all beings and existence is essential in connecting with Shiva, the Supreme Being.

The 17th of the Nayanmars, Rudra Pasupathi Nayanmar, was an unparalleled devotee of Bhagavan Shiva, engaged in a specific spiritual practice involving Shri Rudram (The Yajur Veda, which is considered the Head of the Bhagavan, contains seven Kandas. At the heart of the middle Kanda lies Shri Rudram, which celebrates the many magnificent manifestations of Bhagavan Shiva and is highly revered in spiritual practices). 

His method of worship included standing neck-deep in water and reciting Sri Rudram. This particular form of devotion, combining the sanctity of the scripture with the purifying nature of water, was believed to be especially potent. As a result of his deep devotion and unique practice, Rudra Pasupathi Nayanmar was graced by Bhagavan Shiva with Moksha, the liberation of the soul from the cycle of birth and death, achieving ultimate spiritual fulfillment.
"""

[names]
ta = [ "rudra~pazupati nAyan2mAr (17) gurupUjai",]
