default_to_none = true
id = "cidambarE_bhikSATana_svarNarathaH"
tags = [ "TamilnaduTempleFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
anchor_festival_id = "naTarAjar_An2i_tirumaJcan2am"
offset = -2
jsonClass = "HinduCalendarEventTiming"

[description]
en = "The Brahmotsavam of Nataraja at Chidambaram happens specially around the Aani Thirumanjana festival each year, for ten days. On this eighth day of the festival, Shiva appears as Bhikshatana. This form relates to the myth of Daruvana, the Daru Forest, where Shiva enlightened the rishis on devotion and advaita, and commenced his Cosmic Dance. As a naked mendicant, Bhikshatana, he implores us to surrender our ego into his begging bowl. Upon reaching the East Car Street, the Bhagavan will be placed in the magnificent Golden Chariot for a procession around the four car streets. Late at night, after Bhikshatana returns, Somaskanda will ride around the city on a horse vahana."

[names]
sa = [ "चिदम्बरे भिक्षाटन-स्वर्णरथः",]
