default_to_none = true
id = "viSNu-damanakOtsavaH"
shlokas = """
चैत्रे मासि तथा विष्णोः कार्यो दमनकोत्सवः।
वैष्णवैर्विष्णुभक्त्या च जनतानन्दवर्धनः॥
देवानन्दसमुद्भूता दिव्या दमनमञ्जरी।
निवेद्या विष्णवे भक्त्या सर्वपुण्यफलेप्सुभिः॥
"""
references_primary = ["Smriti Kaustubham p.101"]
tags = ["LessCommonFestivals"]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 1
anga_type = "tithi"
anga_number = 12
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Perform `pUjA` to `viSNu`s using `damanaka` (dhavana) flowers."

[names]
sa = ["विष्णु-दमनकोत्सवः"]

