default_to_none = true
id = "madhyASTamI"
tags = [ "CommonFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 6
anga_type = "tithi"
anga_number = 23
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "मध्याष्टमी",]
