default_to_none = true
id = "trailaGga-svAmI~jayantI"
tags = [ "MahapurushaEvents",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 10
anga_type = "tithi"
anga_number = 11
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Paramahamsa described Him as \"walking Shiva of Varanasi\""

[names]
sa = [ "त्रैलङ्ग-स्वामि-जयन्ती",]
