default_to_none = true
id = "kAJcI_14_jagadguru_zrI~vidyAghanEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
निवेश्य गङ्गाधरगीष्पतिं पदे प्रविश्य कूटं तद् अगस्त्यचिह्नितम्।
प्रमोटयन् मन्त्रत उग्रभैरवं निवेशनं स्वं तत एव कॢप्तवान्॥२८॥
श्रीमद्बापणसोमयाजितनयः श्रीनायनाभिख्यया
ख्यातः पूर्वम् उदारमन्त्रविभवः संयम्य सच्चिद्घनात्।
आस्थायाप्यधिकामकोटि स शिवान् (४५) अब्दान् अगेऽगाल्लयं
धातौ शालि-मणीशिखीक्षण(२३९)-सहे दर्शे च विद्याघनः॥२९॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-14.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 9
anga_type = "tithi"
anga_number = 30
kaala = "अपराह्णः"
year_start = 3418
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Having entered the peak named Agastya after established Gaṅgādharagīṣpati in the ācārya Pīṭha and after subduing the Ugrabhairava through mantra, He stayed there itself. Son of Śrī Boppanna, known as Śrī Nāyana earlier, that Vidyāghana having got initiation from Saccidghana, endowed with enormous occult powers, having adorned the principal seat of Kāmakoṭi for forty-five years, He merged (in Self) on the new moon day of the month of Mārgaśīrṣa in the year Dhātu of Śālivāhana era 239."

[names]
sa = [ "काञ्ची १४ जगद्गुरु श्री-विद्याघनेन्द्र सरस्वती आराधना",]
