id = "vAsAy-yuddha-samAptiH"
jsonClass = "HinduCalendarEvent"

[timing]
month_type = "julian"
anga_type = "day"
month_number = 5
anga_number = 5
year_start = 1739
year_start_era = "gregorian"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """
Chimaji Appa ground down the Portuguese, systematically mined, blasted and won vasAi/ bessein (long suffering Christian inquisition barbarisms). 

## Impact
This ended the Portuguese "Generalship of the North". The resulting treaty ensured that Gentoos (Hindus) inhabiting Goa etc. could again freely practice their religion. The English (having failed to aid Portuguese) hastily sent envoys to draw up friendship treaties with marATha-s. This victory came at a heavy cost (22k soldiers dead) and after a determined campaign of 2 years.

## Events
"On the 3rd, the tower of San Sebastian was demolished by a Maratha mine. Eight hundred Portuguese soldiers had been killed and their powerful bastions of San Sebastian and Remedios lay demolished. The white flag was hoisted on the fort and on the 5th of May 1739, the garrison surrendered. Ten days later, they were allowed to march out of Vasai into boats which would take them to Goa. On the 23rd of May 1739, the Portuguese flag which had flown atop Vasai or Bacaim as the Portuguese called it, was pulled down and the zari parka unfurled in it's place. A bell from the church on the fort was taken and re installed as a temple bell at Bhimashankar! Other bells were sent to other temples." - AG's book.
"""

[names]
sa = [ "वासायि-युद्ध-समाप्तिः",]
