default_to_none = true
id = "lalitA~jayantI"
tags = [ "CommonFestivals", "Dashamahavidya",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 11
anga_type = "tithi"
anga_number = 15
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Goddess Lalita is 3rd of the Dasha Maha Vidyas."

[names]
sa = [ "ललिता-जयन्ती",]
