default_to_none = true
id = "tulasI-vivAhOtsava-samApanam"
tags = [ "CommonFestivals",]
shlokas = """
कनकस्य सुता पूर्वमेकादश्यां किशोरिका।
चकार भक्तितः सायं तुलस्युद्वाहजं विधिम्॥९॥
तेन वैधव्यदोषेण निर्मुक्ताऽऽसीत् सुलोचना।
तस्मात् सायं प्रकर्तव्यस्तुलस्युद्वाहजो विधिः॥१०॥
अवश्यमेव कर्तव्यः प्रतिवर्षं तु वैष्णवैः॥
विधिं तस्य प्रवक्ष्यामि यथा साङ्गा क्रिया भवेत॥११॥
विष्णोस्तु प्रतिमां कुर्यात् पलस्य स्वर्णजां शुभाम्।
तदर्धार्धं तदर्धार्धं यथाशक्त्या प्रकल्पयेत्॥१२॥
प्राणप्रतिष्ठां कृत्वैव तुलसीविष्णुरूपयोः।
तत उत्थापयेद् देवं पूर्वोक्तैश्च स्तवादिभिः॥१३॥
उपचारैः षोडशभिः पूजयेत् पुरुषोक्तिभिः।
देशकालौ ततः स्मृत्वा गणेशं तत्र पूजयेत्॥१४॥
पुण्याहं वाचयित्वाऽथ नान्दीश्राद्धं समाचरेत्।
वेदवाद्यादिनिर्घोषैर्विष्णुमूर्तिं समानयेत्॥१५॥
तुलसीनिकटे सा तु स्थाप्या चान्तर्हिता पटैः।
आगच्छ भगवन्देव अर्चयिष्यामि केशव॥१६॥
तुभ्यं दास्यामि तुलसीं सर्वकामप्रदो भव॥
दद्यात् त्रिवारमर्घ्यं च पाद्यं विष्टरमेव च॥१७॥
तत आचमनीयं च त्रिरुक्त्वा च प्रदापयेत्।
ततो दधि घृतं क्षीरं कांस्यपात्रपुटीकृतम्॥१८॥
मधुपर्कं गृहाण त्वं वासुदेव नमोऽस्तु ते।
हरिद्रालेपानाभ्यङ्गकार्यं सर्वं विधाय च॥१९॥
गोधूलिसमये पूज्यौ तुलसीकेशवौ पुनः।
पृथक्पृथक्तथा कार्यौ सम्मुखौ मङ्गलं पठेत्॥२०॥
ईषद्दृश्ये भास्करे तु सङ्कल्पं तु समुच्चरेत्।
स्वगोत्रप्रवरानुक्त्वा तथा त्रिपुरुषादिकम्॥२१॥
अनादिमध्यनिधन त्रैलोक्यप्रतिपालक।
इमां गृहाण तुलसीं विवाहविधिनेश्वर॥२२॥
पार्वतीबीजसम्भूतां वृन्दाभस्मनि संस्थिताम्।
अनादिमध्यनिधनां वल्लभां ते ददाम्यहम्॥२३॥
पयोघटैश्च सेवाभिः कन्यावद् वर्धिता मया।
त्वत्प्रियां तुलसीं तुभ्यं ददामि त्वं गृहाण भोः॥२४॥
एवं दत्त्वा च तुलसीं पश्चात्तौ पूजयेत्ततः।
रात्रौ जागरणं कुर्याद् विवाहोत्सवपूर्वकम्॥२५॥
ततः प्रभातसमये तुलसीं विष्णुमर्चयेत्।
वह्निसंस्थापनं कृत्वा द्वादशाक्षरविद्यया॥२६॥
पायसाऽऽज्यक्षौद्रतिलैर्जुह्यादष्टोत्तरं शतम्।
ततः स्विष्टकृतं हुत्वा दद्यात्पूर्णाहुतिं ततः।
आचार्यं च समभ्यर्च्य होमशेषं समापयेत्॥२७॥
चतुरो वार्षिकान्मासान्नियमो येन यः कृतः।
कथयित्वा द्विजेभ्यस्तत्तथाऽन्यत्परिपूरयेत्॥२८॥
इदं व्रतं मया देव कृतं प्रीत्यै तव प्रभो।
न्यूनं संपूर्णतां यातु त्वत्प्रसादाज्जनार्दन॥२९॥
रेवतीतुर्यचरणे द्वादशीसंयुते नरः।
न कुर्यात् पारणं कुर्वन्व्रतं निष्फलतां नयेत्॥३०॥
ततो येषां पदार्थानां वर्जनं तु कृतं भवेत्॥
चातुर्मास्येऽथवा चोर्जे ब्राह्मणेभ्यः समर्पयेत्।
ततः सर्वं समश्नीयाद् यद् यत् त्यक्तं व्रते स्थितम्॥३१॥
दम्पतिभ्यां सहैवाऽत्र भोक्तव्यं च द्विजैः सह॥३२॥
ततो भुक्त्युत्तरं यानि गलितानि दलानि च।
तानि भुक्त्वा तुलस्याश्च स्वयं पापैः प्रमुच्यते॥३३॥
इक्षुदण्डं तथा धात्रीफलं कोलिफलं तथा।
भुक्त्वा तु भोजनस्यान्ते तस्योच्छिष्टं विनश्यति॥३४॥
एषु त्रिषु न भुक्तं चेदेकैकमपि येन तु।
ज्ञेय उच्छिष्ट आवर्षं नरोऽसौ नात्र संशयः॥३५॥
ततः सायं पुनः पूज्याविक्षुदण्डैश्च शोभितैः।
तुलसीवासुदेवौ च कृतकृत्यो भवेत् ततः॥३६॥
ततो विसर्जनं कृत्वा दत्त्वा दायादिकं हरेः।
वैकुण्ठं गच्छ भगवन्स्तुलसीसहितः प्रभो।
मत्कृतं पूजनं गृह्य सन्तुष्टो भव सर्वदा॥३७॥
गच्छ गच्छ सुरश्रेष्ठ स्वस्थाने परमेश्वर।
यत्र ब्रह्मादयो देवास्तत्र गच्छ जनार्दन॥३८॥
एवं विसृज्य देवेशमाचार्याय प्रदापयेत्।
मूर्त्यादिकं सर्वमेव कृतकृत्यो भवेन्नरः॥३९॥
प्रतिवर्षं तु यः कुर्यात् तुलसीकरपीडनम्।
भक्तिमान् धनधान्यैः स युक्तो भवति निश्चितम्।
इहलोके परत्रापि विपुलं च यशो लभेत्॥४०॥
---श्रीस्कान्दे महापुराणे द्वितीये वैष्णवखण्डे कार्तिकमासमाहात्म्ये कूष्माण्डनवमीतुलसीविवाहविधिवर्णनं नामैकत्रिंशोऽध्यायः
"""
references_primary = [ "Skanda Puranam",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "puurvaviddha"
month_number = 8
anga_type = "tithi"
anga_number = 12
kaala = "मध्याह्नः"
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "तुलसी-विवाहः",]
