default_to_none = true
id = "kapAlI tEr"
tags = [ "TamilnaduTempleFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
anchor_festival_id = "kar2pagAmbALâ€“kapAlIzvarar tirukkalyANam"
offset = -3
jsonClass = "HinduCalendarEventTiming"

[names]
ta = [ "kapAlI tEr",]
