id = "mUlAdi-hatyA"
jsonClass = "HinduCalendarEvent"

[timing]
month_type = "gregorian"
anga_type = "day"
month_number = 2
anga_number = 17
year_start = 1950
year_start_era = "gregorian"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """
On this day a big massacre of Hindus by Islamist mobs began in the mUlAdi river port in East Pakistan. On the morning of 17th, terrified Hindus and Christians began to rush towards the Muladi police station. The O.C. however refused to provide any shelter. The orgy of loot, murder, rape and arson continued till the evening, when they departed with the loot and the abducted women. The streets, ghats and the river were full of corpses. In the betelnut orchard of one Hindu, more 300 dead bodies were found.

On the morning of 18th, Saturday, many Hindus and Christians returned to their looted, destroyed and gutted houses. In the evening, they once again assembled at the police station. This time they were allowed inside in lieu of their cash and jewellery. In the meantime, the Ansars went all around Muladi announcing in loudspeakers asking the Hindus to assemble at the Muladi police station. After the Hindus and Christians had gathered hundreds of non-Muslim men were massacred within the precincts of the police station.  The O.C. himself stripped the Hindu women of their vermillion and conch shell bangles and forced them to recite the kalma. Later he distributed the women among the gang leaders.

On the morning of 20 February, the Officer in Charge announced that a relief camp has been opened in the port area. He seized all the money and the jewellery from the Hindus gathered at the police station and directed them towards the port. At around 12 noon, at the signal of the O.C. a 3,000 strong armed Muslim mob attacked the warehouses. More than 700 men and elderly women were massacred and their bodies thrown into the river. The remaining women were taken into a shed belonging to one Mukteshwar Saha and forced to recite the kalma. After that 50 women were distributed among the gang leaders.
"""

[names]
sa = [ "मूलादि-हत्या",]
