default_to_none = true
id = "zrIkRSNajanmASTamI"
tags = [ "Dashavataram", "CommonFestivals",]
jsonClass = "HinduCalendarEvent"
shlokas = """
मासि तु श्रावणेऽष्टम्यां निशीथे कृष्णपक्षके।
प्राजापत्यसंयुक्ते कृष्णं देवक्यजीजनत्॥
अवतारदिने पुण्ये हरिमुद्दिश्य भक्तितः।
उपवासादि यत् किञ्चित्तदानन्त्याय कल्पते॥
श्रीब्रह्मवैवर्ते महापुराणे ब्रह्मखण्डे सौतिशौनकसंवादे नारदं प्रति शिवोपदेशे भक्ष्याभक्ष्यादिविवरणं नाम सप्तविंशतितमोऽध्यायः---
जन्माष्टमीदिने रामनवमीदिवसे हरेः।
शिवरात्रौ च यो भुङ्क्ते सोऽपि द्विगुणपातकी॥११॥
"""
references_primary = [ "Vaidyanatha Dikshitiyam (SVR) p.62",]

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "paraviddha"
month_number = 5
anga_type = "tithi"
anga_number = 23
kaala = "निशीथः"
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "श्रीकृष्णजन्माष्टमी",]
