jsonClass = "HinduCalendarEvent"
default_to_none = true
id = "ta__tiruccendUr murugan2 mAcit tiruvizhA ##9##m nALâ€”taGga kailAca vAhan2am"
script_priority = "ta"
tags = [ "TamilnaduTempleFestivals",]

[timing]
jsonClass = "HinduCalendarEventTiming"
default_to_none = true
anchor_festival_id = "ta__tiruccendUr mAcit tiruvizhA nir2aivu"
offset = -3
