default_to_none = true
id = "girijA-kalyANam"
tags = [ "SringeriFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 2
anga_type = "tithi"
anga_number = 12
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "गिरिजा-कल्याणम्",]
