default_to_none = true
id = "kaMsa-vadhaH"
tags = [ "PuranaEvents", "CommonFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 8
anga_type = "tithi"
anga_number = 10
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Lord Krishna killed Kamsa on this day; most popularly celebrated in Mathura and Uttar Pradesh."

[names]
sa = [ "कंस-वधः",]
