default_to_none = true
id = "zamI-pUjA"
tags = [ "LessCommonFestivals",]
shlokas = """
शमीं शमयते पापं शमी शत्रुविनाशिनि।
अर्जुनस्य धनुर्धात्री रामस्य प्रियदर्शिनी॥
शमीं कमलपत्राक्षीं शमीं कण्टकधारिणीम्।
आरोहतु शमीं लक्ष्मीः नृणामायुष्यवर्धिनीम्॥
नमो विश्वासवृक्षाय पार्थशस्त्रास्त्रधारिणे।
त्वत्तः पत्रं प्रतीच्छामि सदा विजयदो भव॥
अमङ्गलानां शमनीं दुष्कृतस्य च नाशिनीम्।
दुःस्वप्नहारिणीं धन्यां प्रवस्येऽहं शमीं शुभाम्॥
"""
references_primary = [ "Vrata Mahima",]
references_secondary = [ "Vaidikasri Sep 2009",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 7
anga_type = "tithi"
anga_number = 10
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Perform puja to Shami tree. Arjuna and Pandavas had left their weapons on this tree during `ajJAtavAsa`. Those who are unable to worship the tree must at least chant the following shlokas."

[names]
sa = [ "शमी-पूजा",]
