default_to_none = true
id = "dIpAvalI_or_lakSmI-kubEra-pUjA"
tags = [ "CommonFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 7
anga_type = "tithi"
anga_number = 30
kaala = "प्रदोषः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Gives light even to Naraka-vasis; Also, Bali was sent to Paatalam on this day."

[names]
sa = [ "दीपावली/लक्ष्मी-कुबेर-पूजा",]
