default_to_none = true
id = "akSaya-tRtIyA~(alabhyam–budha-rOhiNI)"
tags = [ "CommonFestivals",]
shlokas = """
अक्षय्यतृतीया वैशाखशुक्लतृतीयायां निर्णयामृते भविष्ये विष्णुपूजोक्ता---
वैशाखस्य तृतीयायां श्रीसमेतं जगद्गुरुम्।
नारायणं पूजयेत पुष्पधूपविलेपनैः।
तत्रैव विशेषः---
वैशाखे शुक्लपक्षे च तृतीयायां तथैव च।
गङ्गातोयैर्नरः स्नात्वा मुच्यते सर्वकिल्बिषैः।
तस्यां कार्यो यवैर्होमो यवैर्विष्णुं समर्चयेत्।
यवान्दद्याद् द्विजातिभ्यः प्रयतः प्राशयद्यवान्।
तथा मदनरत्ने भविष्ये---
कृष्ण उवाच
बहुनाऽत्र किमुक्तेन किं बह्वक्षरमालया।
वैशाखस्य सितामेकां तृतीयामक्षयां शृणु॥१॥
यस्यां स्नानं जपो होमः स्वाध्यायः पितृतर्पणम्।
दानं च क्रियते किञ्चित् तत्सर्वं स्यादिहाक्षयम्॥२॥
आदिः कृतयुगस्येयं युगादिस्तेन कथ्यते।
सर्वपापप्रशमनी सर्वसौख्यप्रदायिनी॥३॥
पुरा महोदये पार्थ वणिगासीत्स निर्धनः।
प्रियंवदः सत्यवृत्तिर्देवब्राह्मणपूजकः॥४॥
पुण्याख्यानैकचित्तोऽभूत्कुटुम्बव्याकुलोऽपि सन्।
तेन श्रुता वाच्यमाना तृतीया रोहिणीयुता॥५॥
यदा स्याद् बुधसंयुक्ता तदा सा सुमहाफला।
तस्यां यद्दीयते किञ्चिदक्षयं स्यात्तदेव हि॥६॥
इति श्रुत्वा स गङ्गायां सन्तर्प्य पितृदेवताः।
गृहमागत्य करकान्सान्नानुदकसंयुतान्॥७॥
अन्नपूर्णान् बृहत्कुम्भाञ्जलेन विमलेन च।
यवगोधूमचणकान्सक्तून्दध्योदनं तथा॥८॥
इक्षुक्षीरविकारांश्च सहिरण्यांश्च शक्तितः।
शुचिः शुद्धेन मनसा ब्राह्मणेभ्यो ददौ वणिक्॥९॥
भार्यया वार्यमाणोऽपि कुटुम्बासक्तचित्तया।
तावत्तस्थौ स्थिरे सत्त्वे मत्वा सर्वं विनश्वरम्॥१०॥
धर्मासक्तमतिः पार्थे कालेन बहुना ततः।
जगाम पञ्चत्वमसौ वासुदेवमनुस्मरन्॥११॥
ततः स क्षत्रियो जातः कुशावत्यां युधिष्ठिर।
बभूव चाक्षया तस्य समृद्धिर्धर्मसंयुता॥१२॥
इयाज स महायज्ञैः समाप्तवरदक्षिणैः।
स ददौ गोहिरण्यादि दानान्यन्यान्यहर्निशम्॥१३॥
बुभुजे कामतो भोगान्दीनान्धान्पूरयद्धनैः।
तथाऽप्यक्षयमेवास्य क्षयं याति न तद्धनम्॥१४॥
श्रद्धापूर्वं तृतीयायां दत्तं च विभवं विना।
इत्येतत्ते समाख्यातं श्रूयतामत्र यो विधिः॥१५॥
तृतीयां च समासाद्य स्नात्वा सन्तर्प्य देवताः।
एकभक्तं तदा कुर्याद्वासुदेवं प्रपूजयेत्॥१६॥ 
उदकुम्भान्सकरकान्सान्नान्सर्वरसैः सह।
ग्रैष्मिकं सर्वमेवात्र सस्यं दाने प्रशस्यते॥१७॥ 
छत्रोपानत्प्रदानं च गोभूकाश्वनवाससाम्।
यद्यदिष्टतमं चान्यत्तद्देयमविशङ्कया॥१८॥ 
एतत्ते सर्वमाख्यातं किमन्यच्छ्रोतुमिच्छसि।
अनाख्येयं न मे किञ्चिदस्ति स्वस्त्यस्तु तेऽनघ॥१९॥ 
अस्यां तिथौ क्षयमुपैति हुतं न दत्तं
तेनाक्षयेति कथिता मुनिभिस्तृतीया।
उद्दिश्य दैवतपितॄन्क्रियते मनुष्यैस्-
तच्चाक्षयं भवति भारत सर्वमेव॥२०॥

कृत्यसारसमुच्चये---
ब्रह्मपुराणे---
तस्यां कार्यो यवैर्यज्ञो यवैर्विष्णुं प्रपूजयेत्।
यवान् दद्याद् द्विजातिभ्यः प्रयतः प्राशयेद् यवान्॥
पूजादि विधायातिशयिताक्षय-यवदान-जन्य-फल-प्राप्ति-कामनया यवान् दद्यात्।
तद् वाक्यमेतत् फलानुसारेणोहयं (करणीयम्)। द्रव्यान्तरदानेऽपि
अक्षयफलप्राप्तिकामनया इत्यादिवाक्यम्। नारदीये---
वैशाखे शुक्लपक्षे तु तृतीयायां तथैव च।
गङ्गातोये नरः स्नात्वा मुच्यते सर्वकिल्बिषैः॥
ॐ अद्येत्यादि सर्वकिल्बिषविमुक्तिकामो गङ्गायां स्नानमहं करिष्ये, इति गङ्गास्नानसङ्कल्पः।
कौशिकीस्नानप्रकरणे, रामायणे आदिकाण्डे-
वैशाखे मासि काकुत्स्थ तृतीया या भवेत् तिथिः।
शुक्लपक्षे नरः स्नात्वा अश्वमेधफलं लभेत्॥
कृत्तिका ऋक्षसंयुक्ता राका या कार्तिके भवेत्।
कोकामुखे तु कौशिक्यां स्नात्वा स्वर्गे वसेन्नरः॥
ॐ अद्येत्यादि अश्वमेधफलप्ताप्तिकामः कौशिक्यां स्नानमहं करिष्ये इति तृतीयायां सङ्कल्पः।
"""
references_primary = [ "Smriti Kaustubha p.109-110"]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Daanam of Dadhyodanam, Vyanjanam, Chatram, Paduka, Udaka Kumbham, Mangos, Jackfruit; Lakshmi Narayana Pooja; Gauri Pooja;"

[names]
sa = [ "अक्षय-तृतीया~(अलभ्यम्–बुध-रोहिणी)",]
