default_to_none = true
id = "kArttika-mAsa-antimatrayatithi-vratam"
tags = [ "LessCommonFestivals",]
references_primary = [ "skAnda mahApurANe vaiSNavakhaNDE SaDtriMzO.adhyAyaH",]
jsonClass = "HinduCalendarEvent"
shlokas = """
यास्तिस्रस्तिथयः पुण्या अन्तिके शुक्लपक्षके।
कार्तिके मासि विप्रेन्द्र पूर्णिमान्ताः शुभावहाः॥१॥
अन्तिपुष्करिणी संज्ञा सर्वपापक्षयावहा।
कार्तिके मासि सम्पूर्ण यो वै स्नानं करोति ह॥२॥
तिथिष्वेतासु सः स्नानात्पूर्णमेव फलं लभेत्।
सर्वे वेदास्त्रयोदश्यां गत्वा जन्तून् पुनन्ति हि॥३॥
चतुर्दश्यां सयज्ञाश्च देवा जन्तून् पुनन्ति हि।
पूर्णिमायां सुतीर्थानि विष्णुना संस्थितानि हि॥४॥
ब्रह्मघ्नान् वा सुरापान् वा सर्वान् जन्तून् पुनन्ति हि।
उष्णोदकेन यः स्नायात्कार्तिक्यादिदिनत्रये॥५॥
रौरवं नरकं याति यावदिन्द्राश्चतुर्दश।
आमासनियमाशक्तः कुर्यादेतद्दिनत्रये॥६॥
तेन पूर्णफलं प्राप्य मोदते विष्णुमन्दिरे।
यो वै देवान्पितृन्विष्णुं गुरुमुद्दिश्य मानवः॥७॥
न स्नानादि करोत्यद्धा स याति नरकं ध्रुवम्।
कुटुम्बभोजनं यस्तु गृहस्थस्तु दिनत्रये॥८॥
सर्वान्पितॄन्समुद्धृत्य स याति परमं पदम्।
गीतापाठं तु यः कुर्यादन्तिमे च दिनत्रये॥९॥
दिनेदिनेऽश्वमेधानां फलमेति न संशयः।
सहस्रनामपठनं यः कुर्यात्तु दिनत्रये॥१०॥
न पापैर्लिप्यते क्वाऽपि पद्मपत्रमिवाम्भसा।
देवत्वं मनुजैः कैश्चित्कैश्चित्सिद्धत्वमेव च॥११॥
तस्य पुण्यफलं वक्तुं कः शक्तो दिवि वा भुवि।
यो वै भागवतं शास्त्रं शृणोति च दिनत्रयम्॥१२॥
कैश्चित्प्राप्तो ब्रह्मभावो दिनत्रयनिषेवणात्।
ब्रह्मज्ञानेन वा मुक्तिः प्रयागमरणेन वा॥१३॥
अथ वा कार्तिके मासि दिनत्रयनिषेवणात्।
कार्तिके हरिपूजां तु यः करोति दिनत्रये॥१४॥
न तस्य पुनरावृत्तिः कल्पकोटिशतैरपि।
कार्तिके मासि विप्रेन्द्र सर्वमन्त्यदिनत्रये॥१५॥
पुण्यं तत्राऽपि वैशेष्यं रोकायां वर्ततेऽनघ।
प्रातःकाले समुत्थाय शौचं स्नानादिकं चरेत्॥१६॥
समाप्य सर्वकर्माणि विष्णुपूजां समाचरेत्।
उद्याने वा गृहे वाऽपि कार्तिक्यां विष्णुतत्परः॥१७॥
मण्डपं तत्र कुर्वीत कदलीस्तम्भमण्डितम्।
चूतपल्लवसंवीतमिक्षुदण्डैः सुमण्डितम्॥१८॥
चित्रवस्त्रैः स्वलङ्कृत्य तत्र देवं प्रपूजयेत्।
चूतपल्लवपुष्पाढ्यैः फलाद्यैः पूजयेद्धरिम्॥१९॥
शृणुयादूर्जमाहात्म्यं नियमेन शुचिः पुमान्।
सम्पूर्णमथ वाऽध्यायमेकश्लोकमथाऽपि वा॥२०॥
मुहूर्तं वाऽपि शृणुयात्कथां पुण्यां दिनेदिने।
यदि प्रतिदिनं श्रोतुमशक्तः स्यात्तु मानवः॥२१॥
पुण्यमासेऽथवा पुण्यतिथौ संशृणुयादपि।
तेन पुण्यप्रभावेन पापान्मुक्तो भवेन्नरः॥२२॥
"""

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Last three days of `kArttika-mAsaH`. `anantaphaladam`! Perform Shiva/Vishnu Puja, Bhagavata Parayanam, BhagavadGita Parayanam, Vishnu Sahasranama Parayanam etc."

[names]
sa = [ "कार्त्तिक-मास-अन्तिमत्रयतिथि-व्रतम्",]
