default_to_none = true
id = "vaizAkha-mAsa-antimatrayatithi-vratam"
tags = [ "LessCommonFestivals",]
references_primary = [ "skAnda mahApurANe vaiSNavakhaNDE vaizAkhamAhAtmyE paJcaviMSO.adhyAyaH",]
jsonClass = "HinduCalendarEvent"
shlokas = """
यः माधवे वैशाखमासे, त्रयोदशीचतुर्दशीपूर्णिमासु तिथिषु स्नानादिकं करोति 
स निश्चयेन मोक्षं प्राप्नुयात्। यथा पुरा धनशर्मा ब्राह्मणः त्रयः प्रेताश्च
मुक्तिं प्रापुरिति। अत्र प्रसिद्धा कथा सप्तदशाध्यायात्मकपाद्मोक्तवैशाखमाहात्म्ये।
पुरा विष्णुना त्रयोदश्यां हिरण्याक्षः, चतुर्दश्यां मधुश्च घातितः,
पौर्णमास्यां भूम्युद्धारश्च कृतः, ततः प्रभृति तास्तिथयः पुण्या जाताः!
श्रुतदेव उवाच---
यास्तिस्रस्तिथयः पुण्या अन्तिमाः शुक्लपक्षके।
वैशाखमासि राजेन्द्र पूर्णिमान्ताः शुभावहाः॥१॥
अन्त्याः पुष्करिणीसंज्ञाः सर्वपापक्षयावहाः।
माधवे मासि यः पूर्णं स्नानं कर्तुं न च क्षमः॥२॥
तिथिष्वेतासु स स्नायात्पूर्णमेव फलं लभेत्।
सर्वे देवास्त्रयोदश्यां स्थित्वा जन्तून्पुनन्ति हि॥३॥
पूर्णायाः पर्वतीर्थैश्च विष्णुना सह संस्थिताः।
चतुर्दश्यां सयज्ञाश्च देवा एतान्पुनन्ति हि॥४॥
ब्रह्मघ्नं वा सुरापं वा सर्वानेतान्पुनन्ति हि।
एकादश्यां पुरा जज्ञे वैशाख्याममृतं शुभम्॥५॥
द्वादश्यां पालितं तच्च विष्णुना प्रभविष्णुना।
त्रयोदश्यां सुधां देवान्पाययामास वै हरिः॥६॥
जघान च चतुर्दश्यां दैत्यान्देवविरोधिनः।
पूर्णायां सर्वदेवानां साम्राज्याऽऽप्तिर्बभूव ह॥७॥
ततो देवाः सुसन्तुष्टा एतासां च वरं ददुः।
तिसृणां च तिथीनां वै प्रीत्योत्फुल्लविलोचनाः॥८॥
एता वैशाखमासस्य तिस्रश्च तिथयः शुभाः।
पुत्रपौत्रादिफलदा नराणां पापहानिदाः॥९॥
योऽस्मिन्मासे च सम्पूर्णे न स्नातो मनुजाधमः।
तिथित्रये तु स स्नात्वा पूर्णमेव फलं लभेत्॥१०॥
तिथित्रयेप्यकुर्वाणः स्नानदानादिकं नरः।
चाण्डालीं योनिमासाद्य पश्चाद्रौरवमश्नुते॥११॥
उष्णोदकेन यः स्नाति माधवे च तिथित्रये।
रौरवं नरकं याति यावदिंद्राश्चतुर्दश॥१२॥
पितॄन्देवान्समुद्दिश्य दध्यन्नं न ददाति यः।
पैशाचीं योनिमासाद्य तिष्ठत्याभूतसम्प्लवम्॥१३॥
प्रवृत्तानां च कामानां माधवे नियमे कृते।
अवश्यं विष्णुसायुज्यं युज्यते नात्र संशयः॥१४॥
आमासं नियमासक्तः कुर्याद्यदि दिनत्रये।
तेन पूर्णफलं प्राप्य मोदते विष्णुमन्दिरे॥१५॥
यो वै देवान्पितॄन्विष्णुं गुरुमुद्दिश्य मानवः।
न स्नानादि करोत्यद्धाऽमुष्य शापप्रदा वयम्॥१६॥
निःसन्तानो निरायुश्च निःश्रेयस्को भवेदिति।
इति देवा वरं दत्त्वा स्वधामानि ययुः पुरा॥१७॥
तस्मात्तिथित्रयं पुण्यं सर्वाघौघविनाशनम्।
अन्त्यं पुष्करिणीसंज्ञं पुत्रपौत्रविवर्धनम्॥१८॥
या नारी सुभगाऽऽपूपपायसं पूर्णिमादिने।
ब्राह्मणाय सकृद्दद्यात्कीर्तिमन्तं सुतं लभेत्॥१९॥
गीतापाठं तु यः कुर्यादन्तिमे च दिनत्रये।
दिनेदिनेऽश्वमेधानां फलमेति न संशयः॥२०॥
सहस्रनामपठनं यः कुर्य्याच्च दिनत्रये।
तस्य पुण्यफलं वक्तुं कः शक्तो दिवि वा भुवि॥२१॥
सहस्रनामभिर्देवं पूर्णायां मधुसूदनम्।
पयसा स्नाप्य वै याति विष्णुलोकमकल्मषम्॥२२॥
समस्तविभवैर्यस्तु पूजयेन्मधुसूदनम्।
न तस्य लोकाः क्षीयन्ते युग कल्पादि व्यत्यये॥२३॥
अस्नात्वा चाप्यदत्त्वा च वैशाखश्च मतो यदि।
स ब्रह्महा गुरुघ्नश्च पितॄणां घातकस्तथा॥२४॥
श्लोकार्धं श्लोकपादं वा नित्यं भागवतोद्भवम्।
वैशाखे च पठन्मर्त्यो ब्रह्मत्वं चोपपद्यते॥२५॥
यो वै भागवतं शास्त्रं शृणोत्येतद्दिनत्रये।
न पापैर्लिप्यते क्वाऽपि पद्मपत्रमिवांभसा॥२६॥
देवत्वं मनुजैः प्राप्तं कैश्चित्सिद्धत्वमेव च।
कैश्चित्प्राप्तो ब्रह्मभावो दिनत्रयनिषेवणात्॥२७॥
ब्रह्मज्ञानेन वै मुक्तिः प्रयागमरणेन वा।
अथवा मासि वैशाखे नियमेन जलाप्लुतेः॥२८॥
नीलवृषं समुत्सृज्य वैशाख्यां च जलाप्लुतेः।
समस्तबन्धनिर्मुक्तः पुमान्याति परं पदम्॥२९॥
गां सवत्सां द्विजेन्द्राय सीदते च कुटुम्बिने।
इहापमृत्युनिर्मुक्तः परत्र च परं व्रजेत्॥३०॥
स्नानदानविहीनस्तु वैशाखी चैव यो नयेत्।
श्वानयोनिशतं प्राप्य विष्ठायां जायते कृमिः॥३१॥
तिस्रः कोट्योऽर्धकोटिश्च तीर्थानि भुवनत्रये।
सम्भूय मन्त्रयाञ्चक्रुः पापसङ्घातशङ्किताः॥३२॥
जना अस्मासु पापिष्ठा विसृजन्ति स्वकं मलम्।
तदस्माकं कथं गच्छेदिति चिन्तासमन्विताः॥३३॥
तीर्थपादं हरिं जग्मुः शरण्यं शरणं विभुम्।
स्तुत्वा च बहुभिः स्तोत्रैः प्रार्थयामासुरञ्जसा॥३४॥
देवदेव जगन्नाथ सर्वाघौघविनाशन।
जना अस्मासु पापिष्ठाः स्नात्वा पापानि सर्वशः॥३५॥
विसृज्य त्वत्पदं यान्ति त्वदाज्ञाधारिणो भुवि।
अस्माकं चैव तत्पापं कथं गच्छेज्जनार्दन॥३६॥
तदुपायं वदास्माकं त्वत्पादशरणैषिणाम्।
इति तीर्थैः प्रार्थितस्तु भगवान्भूतभावनः॥३७॥
प्रहसन्प्राह तीर्थानि मेघगम्भीरया गिरा।
श्रीभगवानुवाच---
सिते पक्षे मेषसूर्ये वैशाखान्तेदिनत्रये॥३८॥
सर्वतीर्थमये पुण्ये ममाऽपि प्राणवल्लभे।
यूयं भगोदयात्पूर्वं बहिःसंस्थजलाप्लुताः॥३९॥
विमुक्ताघाः पुण्यरूपा भवन्त्वाशु सुनिर्मलाः।
भवद्भिश्च विमुक्ताघैर्ये न स्नाता दिनत्रये॥४०॥
तेषु तिष्ठन्तु तत्पापं जनैर्युष्मद्विरेचितम्।
इति तीर्थपदो विष्णुस्तीर्थानां च वरं ददौ॥४१॥
अनुज्ञाप्य च तान्योगात्तत्रैवान्तरधीयत।
स्वधामानि पुनः प्राप्य तानि तीर्थानि नित्यशः॥४२॥
प्रतिवर्षं तु वैशाखे तथैवान्त्यदिनत्रये।
तेनाघौघं विमुच्यैव यान्ति निर्मलतामहो॥४३॥
ये तु स्नानं न कुर्वन्ति वैशाखान्तदिनत्रये।
ते भवन्तु समस्तानां जनानां पातकाऽऽश्रयाः॥४४॥
इति शापं च तीर्थानि ह्यस्नातानां वदन्ति च।
न तेन सदृशः पापो यो न स्नातो दिनत्रये॥४५॥
विचारितेषु शास्त्रेषु न दृष्टो न च वै श्रुतः।
तस्माद्दिनत्रये कार्यं स्नानदानार्चनादिकम्॥४६॥
अन्यथा नरकं याति यावदिन्द्राश्चतुर्दश।
इत्येतत्सर्वमाख्यातं श्रुतकीर्ते महामते॥४७॥
"""

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Last three days of `vaizAkha-mAsaH`. `anantaphaladam`! Perform Shiva/Vishnu Puja, Bhagavata Parayanam, BhagavadGita Parayanam, Vishnu Sahasranama Parayanam, `dAna` of `apUpa`, `pAyasa` etc."

[names]
sa = [ "वैशाख-मास-अन्तिमत्रयतिथि-व्रतम्",]
