default_to_none = true
id = "zyAmaLAnavarAtraH"
tags = [ "Navaratri", "SpecialPeriod",]
references_secondary = [ "Vaidikasri Feb 2016",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Shyamala Devi specially blesses musicians; honour musicians in this period."

[names]
sa = [ "श्यामळानवरात्रः",]
