default_to_none = true
id = "pUntAnaM~jayantI"
tags = [ "MahapurushaEvents",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "sidereal_solar_month"
month_number = 11
anga_type = "nakshatra"
anga_number = 1
year_start = 4648
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Poonthanam, a great devotee of Guruvayurappan, enriched Malayalam devotional literature with his renowned poetic composition 'Jnanapana', a philosophical work of all times. On this day, recital of Poonthanam's works and debate takes place. A one week literary festival is conducted at Poonthanam illam."

[names]
sa = [ "पून्तानं-जयन्ती",]
