default_to_none = true
id = "chinnamastA~jayantI"
tags = [ "Dashamahavidya",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 2
anga_type = "tithi"
anga_number = 14
kaala = "मध्यरात्रिः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Goddess Chinnamasta is 6th of the Dasha Maha Vidyas."

[names]
sa = [ "छिन्नमस्ता-जयन्ती",]
