default_to_none = true
id = "AyuSmad-bava-saumya-saMyOgaH"
tags = [ "RareDays", "Combinations",]
references_secondary = [ "Maha Periva / Deivattin Kural",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "A rare combination of `AyuSmAn yOga, bava karaNa` and `saumyavAsara`."

[names]
sa = [ "आयुष्मद्-बव-सौम्य-संयॊगः",]
