default_to_none = true
id = "kAJcI_17_jagadguru_zrI~sadAzivEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
विप्राच्छ्रीदेवमिश्राद् अजनि जनित एवाप्तविद्याप्रकाशः
संस्कारैः प्राक्तनैर्यः समगिरत गिरं सर्वम् आत्मेति सत्यम्।
तन्नो मृष्यद्भिरर्हज्जिनयुगभिजनैः पातितः सिन्धुवेण्यां
त्रातः प्रेम्णैव सिन्ध्वाऽप्यविलयम् अमुया पद्मपत्रे निवेश्य॥३४॥
सूनुः सोऽयं तपोभिस्तव मुदितधिया दीयतेऽद्येति वाचा
सार्धं दत्तो द्विजाय स्थिरनियमयुजे यस्तयैवोह्यमानः।
पुष्टस्तेनाथ पुष्पाभिधपुरजनुषा भूरिवस्वाह्वयेन
त्रात्रा पित्रोपनीतः समयम् अयम् अधाद् अद्वयं निर्द्वयत्वे॥३५॥
आचार्यम् उज्ज्वलमहायतिशङ्करार्यम् आराध्य संयमम् अवाप्य तदाज्ञयैव।
श्रीमान् सदाशिवगुरुर्व्यधिताऽऽऽब्धि यात्रां सान्दोलिकं सुविहिताश्रमवर्णधर्मः॥३६॥
नित्यं ब्रह्मसहस्रपोषणपरः सर्वत्र भाष्यं गुरोः
सञ्चार्य द्विविवर्जितान् सनियमं वारांश्च पञ्चाशतः।
अध्यास्याष्ट जगद्गुरोरधिमठं वर्षान् समाधिस्थलीं
जीवन्नेव सदाशिवः समविशत् कृत्वा सुरेन्द्रं पदे॥३७॥
भवे भवाकृतिः सोऽच्छे ज्येष्ठे ज्येष्ठस्तपस्विनाम्।
दशम्याम् आप दशमीं सिद्धिं सिद्धः सदाशिवः॥३८॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-17.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 3
anga_type = "tithi"
anga_number = 10
kaala = "अपराह्णः"
year_start = 3476
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "The one who was born to a brahmin Śrīdeva Miśrā; soon after the birth uttered the Truth that ‘everything is Ātman’ due to the samskāras of the previous birth; the Buddhists and Jains unable to counter the doctrine threw him in the river Sindhu, who saved his life by placing him lovingly on the lotus petals. Being carried by her (river Sindhu) He (Sadāśivabāla) was given to a brahmin endowed with austerities saying “pleased by your austerities/penance today this boy/child is given”; then being asked/enquired by Bhūrivasu of Pushpapura and initiated by him—the saviour—father, He held high the school of nondualism. Preceptor Śrī Sadāśivabāla having served with reverence Śrī Ujjvala Śaṅkarācārya, got initiation, adhering to the principles of asceticism well carried out voyage in palanquin. Preceptor Sadāśiva, always intent on feeding one thousand brahmins, moved around everywhere imparted as per injunctions, for fifty times and governing the maṭha of the Universal Preceptor for eight years, then installing Surendra spent sometime, reached the tranquil state in Tamaraparni (He attained jivasamadhi in Triyambakeshwar.). Sadāśiva, the great among ascetics, the personification of Lord Śiva, the accomplished One, attained his final beatitude on the tenth day of the bright fortnight in the month of Jyeṣṭha of the year Bhava."

[names]
sa = [ "काञ्ची १७ जगद्गुरु श्री-सदाशिवेन्द्र सरस्वती आराधना",]
