default_to_none = true
id = "kAJcI_53_jagadguru_zrI~pUrNAnanda_sadAzivEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
नागारण्यग-नागनाथतनुजः प्राप्ताश्रमः शङ्करानन्दादेष सदाशिवेन्द्रनियमी नेपालभूपाञ्चितः।
पूर्णानन्दपदेन यो भुवि पुनन् सर्वांश्च सानुग्रहं श्रीकाञ्च्यामधिकामपीठमवसत् सैकामशीतिं समाः॥१०५॥
पिङ्गले मङ्गलालोको ज्येष्ठे ज्येष्ठः शुचिः शुचौ।
दशम्यां दशमीम् आर्च्छद् दशां धाम्न्यपुनर्भवे॥१०६॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-53.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 3
anga_type = "tithi"
anga_number = 10
kaala = "अपराह्णः"
year_start = 4599
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "This preceptor Sadāśivendra, son of Nāganātha of Nāgāraṇya, having got initiation into asceticism from Śaṅkarānanda, with the title Pūrṇānanda, adored by/revered by the King of Nepal, sanctifying all on earth with grace, He stayed at the KāmaPīṭha in Kāṅci for eight-one years. The auspicious, revered, pure preceptor merged in the beatitude devoid of rebirth on the tenth day of the bright fortnight of Jyeṣṭha month in the year Piṅgala. This preceptor who went upto Nepal attained Siddhi in Kāṅci itself."

[names]
sa = [ "काञ्ची ५३ जगद्गुरु श्री-पूर्णानन्द सदाशिवेन्द्र सरस्वती आराधना",]
