default_to_none = true
id = "kAJcI_31_jagadguru_zrI~brahmAnandaghanEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
आनन्तिर्ज्येष्ठरुद्रो द्रविडिषु गरुडह्रादिनीसीम्नि जातो
बोधेन्द्राचार्यशिष्यो भुवनगुरुधुरां पालयञ्छीलयुक्तः।
कृत्स्नक्ष्मामण्डलीजिन्नृपवरललितादित्यनुत्यार्चिताङ्घ्रिः
श्रीब्रह्मानन्दसान्द्रः प्रभवशुचिशुचिद्वादशीयाह्नि लिल्ये॥६०॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-31.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 4
anga_type = "tithi"
anga_number = 12
kaala = "अपराह्णः"
year_start = 3769
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Born on the banks of river Garuḍa (Kaḍilam in Tamil) in the Draviḍa deśa (South India), as the son of Anantārya, He was called Jyeṣṭarudra (before initiation). Having become the disciple of Śrī Bodhendrācārya, He held with sincerity the responsibility of Preceptor-ship of the earth; worshipped by King Lalitāditya of Kashmir who conquered all rival kings on earth Śrī Brahmānandaghana attained liberation on dvādaśī(twelfth day) of the bright fortnight of Jyeṣṭa in the year Prabhava. Well-versed in the six system of philosophy and adored/worshipped by the well-known poet Bhavabhūti and Kashmir monarch Lalitāditya, this preceptor adorned the Pīṭha for thirteen years and attained liberation in Kāñci itself."

[names]
sa = [ "काञ्ची ३१ जगद्गुरु श्री-ब्रह्मानन्दघनेन्द्र सरस्वती आराधना",]
