default_to_none = true
id = "zyAmA~zAstrI~jayantI"
tags = [ "MahapurushaEvents", "CommonFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "sidereal_solar_month"
priority = "paraviddha"
month_number = 1
anga_type = "nakshatra"
anga_number = 3
kaala = "प्रातः"
year_start = 4863
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "श्यामा-शास्त्री-जयन्ती",]
