default_to_none = true
id = "kan2up~poGgal"
tags = [ "CommonFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
anchor_festival_id = "makara-saGkrAntiH"
offset = 1
jsonClass = "HinduCalendarEventTiming"

[names]
ta = [ "kan2up~poGgal",]
