default_to_none = true
id = "kAJcI_66_jagadguru_zrI~candrazEkharEndra_sarasvatI_6_ArAdhanA"
tags = [ "KanchiAradhanaDays", "CommonFestivals",]
shlokas = """
सीतारामविचक्षणस्य तनयः श्रीस्वामिनाथाभिधो
वर्णी संयमवान् स जात उदयग्रामे प्रवक्ता पटु।
अद्वैतस्य सुरक्षणे विनिहितप्राज्यप्रयत्नो महान्
अद्वैतार्यमहामठे सुविहितः पूर्वेण तत्सूरिणा॥१९॥
श्रीचन्द्रशेखरगुरुः समाः सप्तदश स्थितः।
पराभवे माघकृष्णाष्टम्यां धाम निजं ययौ॥२०॥
—पुण्यश्लोकमञ्जरी परिशिष्टम्
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-66.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 11
anga_type = "tithi"
anga_number = 23
kaala = "अपराह्णः"
year_start = 5008
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Preceptor Śrī Chandraśekhara adorned the Pīṭha for seventeen years. He reached his eternal beatitude on the eighth day of the black fortnight in the month of Māgha of the year Parābhava. The name of this preceptor before initiation was Svāminātha. Parents were well-known Maṅgalāmbikā and Sītārāmaśāstri. His place of siddhi was village Kalavai in Śalivahana era 1830."

[names]
sa = [ "काञ्ची ६६ जगद्गुरु श्री-चन्द्रशेखरेन्द्र सरस्वती ६ आराधना",]
