default_to_none = true
id = "kucEla-dinam"
tags = [ "PuranaEvents",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Celebrated especially in Kerala/Guruvayur. Commemorates the incident of Kuchela visiting Lord Krishna. Offer naivedyam of `pRthukam`."

[names]
sa = [ "कुचेल-दिनम्",]
