default_to_none = true
id = "kAJcI_64_jagadguru_zrI~candrazEkharEndra_sarasvatI_5_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
श्रीमठपार्श्वे सद्मनि जातो वेङ्कटसुब्रह्मण्यतपस्वी।
श्रीगुरुपार्श्वे संस्थितिम् आगाद् उत्तरवृन्दावनविख्यातः॥१४॥
श्रीचन्द्रशेखरगुरुः श्रितचन्द्रमौलिस्त्रिंशत्समा अपि च सप्त वसन् नु पीठे।
साधारणे शरदि कार्त्तिककृष्णपक्षस्याद्ये तिथावुपगतः स्थिरम् आत्मधाम॥१५॥
—पुण्यश्लोकमञ्जरी परिशिष्टम्
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-64.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 8
anga_type = "tithi"
anga_number = 16
kaala = "अपराह्णः"
year_start = 4952
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Devoted to Lord Chandramauli, preceptor Śrī Chandraśekhara too remaining in the Pīṭha for thirty-seven years reached his eternal abode on the first day of Kṛṣṇapakṣa in the month of Kārthika of the year Sādhāraṇa. The name of this preceptor before initiation was Veñkatasubrahmaṇya Dīkṣita. He was a descendant of the family of Govinda Dīkṣita, wellknown as “Ayyan” who carried out many righteous acts of “pūrta” and adorned the ministerial post in the assembly of King Sevappa Nāyaka of the Nāyaka dynasty ruling Tanjavur. This preceptor was well-versed in Mantra Śāstra. Only during the period of this preceptor, the renovation or reinstallation of the pair of ear-rings (taṭaṅka yugala) symbolic of Sricakra, of Goddess Akhilāṇdeśvarī of Jambukeśvara, renovation of Sricakra in the Kāmākṣī temple at Kāñci were carried out. During his visit ot Tanjavur, the preceptor was reverentially coronated with gold or offered Kanakābhiṣeka by the monarch who was ruling Tanjavur. Śalivahana era 1773."

[names]
sa = [ "काञ्ची ६४ जगद्गुरु श्री-चन्द्रशेखरेन्द्र सरस्वती ५ आराधना",]
