default_to_none = true
id = "bhRguvAra-subrahmaNya-vratam"
tags = [ "SpecialVratam",]
references_primary = [ "Skanda Puranam",]
jsonClass = "HinduCalendarEvent"
shlokas = """
अन्यद्व्रतं प्रवक्ष्यामि सुब्रह्मण्यस्य वै द्विजाः।
तुलाराशिं गते सूर्य पूर्वस्मिन् भृगुवासरे॥१॥
समुत्थाय शुचिर्भूत्वा प्रातरेव षडाननम्।
ध्यात्वा हृदब्जनिलये नित्यकर्म समाप्य च॥२॥
व्रतं चरेद्विधानेन सर्वपापहरं परम्।
कृत्तिकाव्रतमन्यच्च स्कन्दषष्ठिव्रतं पाम्॥३॥
व्रतानि त्रीणि ये मर्त्याश्चरन्त्यागममार्गतः।
ते भुक्त्वा विपुलान् भोगानन्ते मोक्षं गुहाज्ञया॥४॥
ब्रह्मविष्ण्वादयो देवाश्चरित्वैतानि भूसुराः।
जघ्नुर्दैत्यान्महाघोरान्रणमध्यगतान् पुरा॥५॥
कर्तृत्वं च दिशां प्रापुर्दिक्पालाः पुनरप्युत।
मुचुकुन्दो महीपालः शत्रूञ्जित्वा रणे पुरा॥६॥
गाणाधिपत्यं सम्पाप चरित्वैतानि भूसुराः।
नारदप्रमुखाः पूर्वे तापसानामधीश्वराः॥७॥
नित्यत्वं प्रापुरतुलं पुनरावृत्तिदुर्लभम्।
पुत्रानायुः पुरा केचिदपुत्रा ब्राह्मणोत्तमाः॥८॥
ऐश्वर्यं ज्ञानयोगांश्च मोक्षं चापुः पुरा परे।
त्रिष्वेतेषु व्रतं चैकं यश्चरेद्गुहसम्मतम्॥९॥
स लब्ध्वा वाञ्छितं सर्वं शिवलोकमनुत्तमम्।
प्राप्य मोक्षं व्रजत्यन्ते गुहस्यैव प्रसादतः॥१०॥
त्रीणि व्रतानि यो मर्त्यश्चरति स्कन्दसम्मतम्।
माहात्म्यं तस्य को वेत्ति गुहतुल्यस्य भूसुराः॥११॥ 
श्री स्कान्दे महापुराणे शङ्करसंहितायां शिवरहस्यखण्डे उपदेशकाण्डे सप्तत्रिंशोऽध्याये
"""

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Observed on the first Friday following the transit of Sun into `tulArAzI`. Three Vratas are very special for Subrahmanya---this one, the regular `kRttikA vratam`, and `skandaSaSThivratam`."

[names]
sa = [ "भृगुवार-सुब्रह्मण्य-व्रतम्",]
