default_to_none = true
id = "SaSThI-vratam"
tags = [ "MonthlyVratam", "ShashthiVratam",]
jsonClass = "HinduCalendarEvent"
shlokas = """
सुमन्तुरुवाच
षष्ठ्यां फलाशनो राजन्विशेषात् कार्तिके नृप ॥
राज्यच्युतो विशेषेण स्वं राज्यं लभतेऽचिरात्॥१॥
षष्ठी तिथिर्महाराज सर्वदा सर्वकामदा॥
उपोष्या तु प्रयत्नेन सर्वकालं जयार्थिना॥२॥
कार्त्तिकेयस्य दयिता एषा षष्ठी महातिथिः।
देवसेनाधिपत्यं हि प्राप्तं तस्यां महात्मना॥३॥
अस्यां हि श्रेयसा युक्तो यस्मात्स्कन्दो भवाग्रणीः।
तस्मात्षष्ठ्यां नक्तभोजी प्राप्नुयादीप्सितं सदा॥४॥
दत्त्वाऽर्घ्यं कार्तिकेयाय स्थित्वा वै दक्षिणामुखः।
दध्ना घृतोदकैः पुष्पैर्मन्त्रेणानेन सुव्रत॥५॥
सप्तर्षिदारज स्कन्द स्वाहापतिसमुद्भव।
रुद्रार्यमाग्निज विभो गङ्गागर्भ नमोऽस्तु ते।
प्रीयतां देवसेनानीः सम्पादयतु हृद्गतम्॥६॥
दत्त्वा विप्राय चाऽऽत्मान्नं यच्चान्यदपि विद्यते।
पश्चाद्भुङ्क्ते त्वसौ रात्रौ भूमिं कृत्वा तु भाजनम्॥७॥
एवं षष्ठ्यां व्रतं स्नेहात्प्रोक्तं स्कन्देन यत्नतः।
तन्निबोध महाराज प्रोच्यमानं मयाऽखिलम्॥८॥
षष्ठ्यां यस्तु फलाहारो नक्ताहारो भविष्यति।
शुक्लाकृष्णासु नियतो ब्रह्मचारी समाहितः॥९॥
तस्य सिद्धिं धृतिं तुष्टिं राज्यमायुर्निरामयम्।
पारत्रिकं चैहिकं च दद्यात्स्कन्दो न संशयः॥१०॥
यो हि नक्तोपवासः स्यात्स नक्तेन व्रती भवेत्।
इह वाऽमुत्र सोऽत्यन्तं लभते ख्यातिमुत्तमाम्।
स्वर्गे च नियतं वासं लभते नात्र संशयः॥११॥
इह चाऽऽगत्य कालान्ते यथोक्तफलभाग्भवेत्।
देवानामपि वन्द्योऽसौ राज्ञां राजा भविष्यति॥१२॥
यश्चापि शृणुयात्कल्पं षष्ठ्याः कुरुकुलोद्वह।
तस्य सिद्धिस्तथा तुष्टिर्धृतिः स्यात्ख्यातिसम्भवा॥१३॥
॥इति श्रीभविष्ये महापुराणे शतार्धसाहस्र्यां संहितायां ब्राह्मेपर्वणि पञ्चमीकल्पे षष्ठीकल्पवर्णनं नाम एकोनचत्वारिंशोऽध्यायः॥
"""
[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Monthly Shashthi vratam for Lord Subrahmanya (Madhyāhna/puurvaviddha)."

[names]
sa = [ "षष्ठी-व्रतम्",]
