default_to_none = true
id = "skandaSaSThI-vratam"
tags = [ "MonthlyVratam", "ShashthiVratam",]
shlokas = """
अन्यद्व्रतं प्रवक्ष्यामि सुब्रह्मण्यस्य वै द्विजाः।
तुलाराशिं गते सूर्य पूर्वस्मिन् भृगुवासरे॥१॥
समुत्थाय शुचिर्भूत्वा प्रातरेव षडाननम्।
ध्यात्वा हृदब्जनिलये नित्यकर्म समाप्य च॥२॥
व्रतं चरेद्विधानेन सर्वपापहरं परम्।
कृत्तिकाव्रतमन्यच्च स्कन्दषष्ठिव्रतं पाम्॥३॥
व्रतानि त्रीणि ये मर्त्याश्चरन्त्यागममार्गतः।
ते भुक्त्वा विपुलान् भोगानन्ते मोक्षं गुहाज्ञया॥४॥
ब्रह्मविष्ण्वादयो देवाश्चरित्वैतानि भूसुराः।
जघ्नुर्दैत्यान्महाघोरान्रणमध्यगतान् पुरा॥५॥
कर्तृत्वं च दिशां प्रापुर्दिक्पालाः पुनरप्युत।
मुचुकुन्दो महीपालः शत्रूञ्जित्वा रणे पुरा॥६॥
गाणाधिपत्यं सम्पाप चरित्वैतानि भूसुराः।
नारदप्रमुखाः पूर्वे तापसानामधीश्वराः॥७॥
नित्यत्वं प्रापुरतुलं पुनरावृत्तिदुर्लभम्।
पुत्रानायुः पुरा केचिदपुत्रा ब्राह्मणोत्तमाः॥८॥
ऐश्वर्यं ज्ञानयोगांश्च मोक्षं चापुः पुरा परे।
त्रिष्वेतेषु व्रतं चैकं यश्चरेद्गुहसम्मतम्॥९॥
स लब्ध्वा वाञ्छितं सर्वं शिवलोकमनुत्तमम्।
प्राप्य मोक्षं व्रजत्यन्ते गुहस्यैव प्रसादतः॥१०॥
त्रीणि व्रतानि यो मर्त्यश्चरति स्कन्दसम्मतम्।
माहात्म्यं तस्य को वेत्ति गुहतुल्यस्य भूसुराः॥११॥ 
श्री स्कान्दे महापुराणे शङ्करसंहितायां शिवरहस्यखण्डे उपदेशकाण्डे सप्तत्रिंशोऽध्याये

अस्यां हि श्रीः समायुक्तः यस्मात् स्कन्दोऽभवत् पुरा।
तस्माट्षष्ठ्यां न भुञ्जीत प्राप्नुयाद्भार्गवी सदा॥

सप्तर्षिदारज स्कन्द सेनाधिप महाबल।
रुद्रोमाग्निज षड्वक्त्र गङ्गागर्भ नमोऽस्तु ते॥

सुमन्तुरुवाच
षष्ठ्यां फलाशनो राजन्विशेषात् कार्तिके नृप ॥
राज्यच्युतो विशेषेण स्वं राज्यं लभतेऽचिरात्॥१॥
षष्ठी तिथिर्महाराज सर्वदा सर्वकामदा॥
उपोष्या तु प्रयत्नेन सर्वकालं जयार्थिना॥२॥
कार्त्तिकेयस्य दयिता एषा षष्ठी महातिथिः।
देवसेनाधिपत्यं हि प्राप्तं तस्यां महात्मना॥३॥
अस्यां हि श्रेयसा युक्तो यस्मात्स्कन्दो भवाग्रणीः।
तस्मात्षष्ठ्यां नक्तभोजी प्राप्नुयादीप्सितं सदा॥४॥
दत्त्वाऽर्घ्यं कार्तिकेयाय स्थित्वा वै दक्षिणामुखः।
दध्ना घृतोदकैः पुष्पैर्मन्त्रेणानेन सुव्रत॥५॥
सप्तर्षिदारज स्कन्द स्वाहापतिसमुद्भव।
रुद्रार्यमाग्निज विभो गङ्गागर्भ नमोऽस्तु ते।
प्रीयतां देवसेनानीः सम्पादयतु हृद्गतम्॥६॥
दत्त्वा विप्राय चाऽऽत्मान्नं यच्चान्यदपि विद्यते।
पश्चाद्भुङ्क्ते त्वसौ रात्रौ भूमिं कृत्वा तु भाजनम्॥७॥
एवं षष्ठ्यां व्रतं स्नेहात्प्रोक्तं स्कन्देन यत्नतः।
तन्निबोध महाराज प्रोच्यमानं मयाऽखिलम्॥८॥
षष्ठ्यां यस्तु फलाहारो नक्ताहारो भविष्यति।
शुक्लाकृष्णासु नियतो ब्रह्मचारी समाहितः॥९॥
तस्य सिद्धिं धृतिं तुष्टिं राज्यमायुर्निरामयम्।
पारत्रिकं चैहिकं च दद्यात्स्कन्दो न संशयः॥१०॥
यो हि नक्तोपवासः स्यात्स नक्तेन व्रती भवेत्।
इह वाऽमुत्र सोऽत्यन्तं लभते ख्यातिमुत्तमाम्।
स्वर्गे च नियतं वासं लभते नात्र संशयः॥११॥
इह चाऽऽगत्य कालान्ते यथोक्तफलभाग्भवेत्।
देवानामपि वन्द्योऽसौ राज्ञां राजा भविष्यति॥१२॥
यश्चापि शृणुयात्कल्पं षष्ठ्याः कुरुकुलोद्वह।
तस्य सिद्धिस्तथा तुष्टिर्धृतिः स्यात्ख्यातिसम्भवा॥१३॥
॥इति श्रीभविष्ये महापुराणे शतार्धसाहस्र्यां संहितायां ब्राह्मेपर्वणि पञ्चमीकल्पे षष्ठीकल्पवर्णनं नाम एकोनचत्वारिंशोऽध्यायः॥
"""
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "One of the most important vratams, alongside Krishnajanmashtami, Shivaratri etc. Must observe fast. Offer Arghyam facing South, using Curd, Akshata, Water and Flowers (`dadhnAkSatOdakaiH puSpaiH`) chanting the shloka mentioned. Three Vratas are very special for Subrahmanya---the `bhRguvAra-subrahmaNya-vratam` in `tulAmAsa`, the regular `kRttikA vratam`, and this most special `skandaSaSThivratam`."

[names]
sa = [ "स्कन्दषष्ठी-व्रतम्",]
