default_to_none = true
id = "tulA-kAvErI-snAna-ArambhaH"
shlokas = """
षट्षष्टिकोटितीर्थानि द्विसप्तभुवनेषु च।
केशवस्याऽऽज्ञया यान्ति तुलामासे मरुद्वृधम्॥
"""
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "sidereal_solar_month"
month_number = 7
anga_type = "day"
anga_number = 1
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Perform `snAnam` in Kaveri during this month."

[names]
sa = [ "तुला-कावेरी-स्नान-आरम्भः",]
