default_to_none = true
id = "atipatta_nAyan2mAr_(42)_gurupUjai"
tags = [ "NayanmarGurupujai",]
references_secondary = [ "63 Nayanmar Saints by Swami Sivananda, published by The Divine Life Society",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "sidereal_solar_month"
priority = "paraviddha"
month_number = 5
anga_type = "nakshatra"
anga_number = 9
kaala = "प्रातः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """Between the 6th and 9th centuries, in South India, there existed 63 ardent devotees of Bhagavan Shiva, collectively known as the Nayanmars. These devout individuals, hailing from various walks of life including potters, fishermen, farmers, merchants, priests, hunters, and washermen, created devotional songs still sung by followers around the globe. Among these Nayanmars, Appar, Sambandar, and Sundarar, known for their Thevaram hymns, along with Manikkavasagar, are distinguished as the Samayacharyas or the ‘The Four’ (`nAlvar`) revered teachers of the faith. They were instrumental in promoting the Shaiva Siddhanta philosophy and culture, effectively challenging the spread of Jainism and Buddhism. Their teachings centered around the concept that Shiva embodies love, and that embracing love for all beings and existence is essential in connecting with Shiva, the Supreme Being.

Atipattar, the 42nd of the Nayanmars was born into a fisherman's family in Nulaipadi, near Nagapattinam. He devoutly followed a unique ritual: daily, he would release one fish from his catch as an offering to Bhagavan Shiva. His dedication caught the attention of the divine, who sought to showcase his unwavering faith to the world.

For several days in a row, the fisherman found himself catching only a single fish each day. Undeterred by the prospect of going hungry, he faithfully released the lone fish back into the water, dedicating the act to Bhagavan Shiva. On one remarkable day, his catch consisted of just one fish again, but this time it was a golden fish. Despite the extraordinary nature of this find and the temptation it might have presented, he adhered to his vow and released the golden fish as an offering to the Bhagavan.

Moved by his steadfast devotion, Bhagavan Shiva manifested before the humble, uneducated fisherman, bestowing upon him divine blessings for his unyielding devotion and sacrifice."""

[names]
ta = [ "atipatta nAyan2mAr (42) gurupUjai",]
