default_to_none = true
id = "SaTtilA-dvAdazI"
tags = [ "SpecialPuja",]
shlokas = """
अर्घं दद्याद्विधानेन पूजयित्वा जनार्दनम्।
कृष्ण कृष्ण कृपालुस्त्वमगतीनां गतिर्भव॥१८॥
संसारार्णवमग्नानां प्रसीद पुरुषोत्तम।
नमस्ते पुण्डरीकाक्ष नमस्ते विश्वभावन॥१९॥
सुब्रह्मण्य नमस्तेऽस्तु महापुरुषपूर्वज।
गृहाणार्घ्यं मया दत्तं लक्ष्म्या सह जगत्पते॥२०॥
[इत्यर्घ्यमन्त्रः]
ततस्तु पूजयेद्विप्रमुदकुम्भं प्रदापयेत्।
छत्रोपानहवस्त्रैश्च कृष्णो मे प्रीयतामिति॥२१॥
कृष्णा धेनुः प्रदातव्या यथाशक्ति द्विजोत्तमे।
तिलपात्रं द्विजश्रेष्ठ दद्यात् पात्रविचक्षणः॥२२॥
स्नाने प्राशनके शस्तास्तथा कृष्णतिला मुने।
तान् प्रदद्यात् प्रयत्नेन यथाशक्ति द्विजोत्तमे।
तिलप्ररोहजाः क्षेत्रे यावत् सङ्ख्यास्तिला द्विज॥२३॥
तावद्वर्षसहस्राणि स्वर्गलोके महीयते।
तिलस्नायी तिलोद्वर्ती तिलहोमी तिलोदकी।
तिलदाता च भोक्ता च षट्तिला पापनाशिनी॥२४॥
---श्रीपाद्मे महापुराणे पञ्चपञ्चाशत्साहस्र्यां संहितायामुत्तरखण्डे उमापतिनारदसंवादान्तर्गतकृष्णयुधिष्ठिरसंवादे माघ-कृष्ण-षट्तिला-एकादशी-माहात्म्यं नाम चतुश्चत्वारिंशोऽध्यायः॥४४॥
"""
references_primary = [ "Padma Puranam",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 10
anga_type = "tithi"
anga_number = 12
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Offer arghyam to Mahavishnu after Ekadashi fast, using the given mantras."

[names]
sa = [ "षट्तिला-द्वादशी",]
