id = "hemachandra-vikramAdityo_hataH"
jsonClass = "HinduCalendarEvent"

[timing]
month_type = "julian"
anga_type = "day"
month_number = 11
anga_number = 5
year_start = 1526
year_start_era = "gregorian"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """
Hemachandra vikramAditya, aka Hemu, was vanquished by mogols invading under akbar and his regent bairAm khAn (though they stayed in the rear - 8 miles away). Hemu was aided by afghAn-s who had been earlier deposed by bAbur's invasion. Hemu was atop an elephant named hawAi. His left was led by his sister's son, Ramya, and the right by Shadi Khan Kakkar.

Mogol army was led by Ali Quli Khan Shaibani in the center, Sikandar Khan Uzbak on the right and Abdulla Khan Uzbak towards the left. Vanguard led by Husain Quli Beg and Shah Quli Mahram.

Both the wings of the Mughal army had been driven back and Hemu moved his contingent of war elephants and cavalry forward to crush their centre. Hemu was on the cusp of victory when he was wounded in the eye by a Mughal arrow and collapsed unconscious. This triggered a panic in his army which broke formation and fled.

The elephant carrying the wounded Hemu was captured and led to the Mughal camp. Bairam Khan asked the 13-year-old Akbar to behead Hemu, but he refused to take the sword to a dying man. Akbar was persuaded to touch Hemu's head with his sword after which Bairam Khan executed him. Hemu's head was sent to Kabul while his body was gibbeted on a gate in Delhi. A minaret was subsequently constructed of the heads of the other dead.

Hemu's family who lived in Machari (near Alwar) was captured by Pir Muhammad. Pir Muhammad offered to spare the life of Hemu's elderly father if he converted to Islam. When the old man refused, he was executed. Hemu's Smadhi Sthal, constructed during Akbar's reign by supports, supposedly on the spot where he died, is now occupied by migrant muslims and converted to a dargAh.
"""

[names]
sa = [ "हक्लदीघाटी-युद्धम्",]
