default_to_none = true
id = "mahAlaya-pakSa-samApanam"
tags = [ "SpecialPeriodEnd", "CommonFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
anchor_festival_id = "(bhAdrapada)_mahAlaya_amAvAsyA"
offset = 0
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "महालय-पक्ष-समापनम्",]
