default_to_none = true
id = "kAJcI_57_jagadguru_zrI~paramazivEndra_sarasvatI_2_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
पम्पासरस्तटभुवः परमेश्वरस्य पुत्रः सदाशिवरतः शिवरामकृष्णः।
तस्मादवाप्य नियमं नियमी निरस्तसङ्गोऽध्युवास सदनं खलु कामनेत्र्याः॥३॥
श्रीचक्रपूजनरतः शिवयोगलम्बी श्रीदेशिकेन्द्रवचसा श्रितकामपीठः।
आचार्यकं छवि(४७)समं विदधावकामः कामेश्वरी-मनु-पुरश्चरणैकदक्षः॥४॥
स पार्थिवे पार्थिवदेहदूरं नभो नभस्यच्छतमोऽच्छपक्षे।
अवापद् आपद्विधुरो दशम्यां दशम्यसौ दीनशके (१५०८) शकाब्दे॥५॥
—पुण्यश्लोकमञ्जरी परिशिष्टम्
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-57.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 5
anga_type = "tithi"
anga_number = 10
kaala = "अपराह्णः"
year_start = 4687
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Śivarāmakṛṣṇa, son of Parameśvara on the banks of river Pampā, devoted to Sadāśiva, having got initiation into asceticism from him, devoid of any attachment indeed, He remained at the abode of goddess Kāmākṣī. Devoted to the worship of Śrī Cakrarāja, adhered to the path of Śivarāja, adhered to the path of Śivayoga, adept in worshipping the goddess Kāmeśvarī, He, free from desires, held the preceptorship for fortyseven years. This senior preceptor, courageous, reached the space that is beyond the physical body, on the tenth day of the bright fortnight of the Śravaṇa month in the year Pārthiva of the Śaka era 1508 (Dūra Śaka). According to scholars, this preceptor was the master of Sadāśivabrahmendra and attained siddhi in Śvetāraṇyam."

[names]
sa = [ "काञ्ची ५७ जगद्गुरु श्री-परमशिवेन्द्र सरस्वती २ आराधना",]
