default_to_none = true
id = "kamalA~jayantI"
tags = [ "Dashamahavidya",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 9
anga_type = "tithi"
anga_number = 30
kaala = "मध्यरात्रिः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Goddess Kamala is 10th of the Dasha Maha Vidyas."

[names]
sa = [ "कमला-जयन्ती",]
