default_to_none = true
id = "tiruccendUr_murugan2_mAcit_tiruvizhA_##3##m_nAL—murugan2_bhavan2i"
tags = [ "TamilnaduTempleFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
anchor_festival_id = "tiruccendUr_mAcit_tiruvizhA_nir2aivu"
offset = -9
jsonClass = "HinduCalendarEventTiming"

[description]
en = "The Tiruchendur Brahmotsavam of Masi each year is very special, wherein all the three temple chariots are dragged and the festival is conducted for twelve days, concluding with a Teppam or Float Festival. This marks the third day of the festival, when Lord Subrahmanya is in procession."

[names]
ta = [ "tiruccendUr murugan2 mAcit tiruvizhA ##3##m nAL—murugan2 bhavan2i",]
