default_to_none = true
id = "azUnyazayana-vratam~4"
tags = [ "SpecialVratam",]
shlokas = """
मदनरत्ने भविष्ये---
श्रीकृष्ण उवाच---
शेते जगत्पतिः कृष्णः श्रिया सार्धं यदा नृप।
अशून्यशयना नाम तदा ग्राह्या तु सा तिथिः॥
कृष्णपक्षे द्वितीयायां श्रावणे मासि भारत।
(अस्मिन् व्रते श्रावणः शुक्लान्तो ग्राह्यः।)
वामनपुराणे---
द्वादश्यादितिथिषु क्रमेण श्रीकृष्ण-काम-यक्षो-मापति-ब्रह्म-विश्वकर्मणां स्वापमभिधाय---
यस्यां तिथ्यां प्रस्वपिति विश्वकर्मा प्रजापतिः।
द्वितीया सा शुभा पुण्या सुपुण्यशयनोचिता॥
तस्यां तिथावर्च्य हरि श्रीवत्साङ्कं चतुर्भजम्।
पर्यङ्कस्थं समं लक्ष्म्या गन्धपुष्पादिभिर्मुने॥
ततो देवाय शय्यायां फलानि प्रक्षिपेत्क्रमात्।
इत्यादिना आषाढ्यव्यवहितद्वितीयायामेवाभिधानात्।
इममुच्चारयेन्मन्त्रं प्रणम्य च जगत्पतिम्---
श्रीवत्सधारि श्रीकान्त श्रीवास श्रीपतेऽव्यय।
गार्हस्थ्यं मा प्रणाशं मे यातु धर्मार्थकामदम्॥
शुचयो मा प्रणश्यन्तु मा प्रणश्यन्तु निर्जराः।
याम्यगा मा प्रणश्यन्तु मत्तो दम्पत्यभेदतः॥
(शुचयोऽग्नयः। निर्जरा देवाः। याम्यगाः पितरः।)
लक्ष्म्या वियुज्यते देव न कदाचिद्यथा भवान्।
तथा कलत्रसम्बन्धो देव मा मे वियुज्यताम्॥
लक्ष्म्या न शून्यं वरद यथा ते शयनं सदा।
शय्या ममाप्यशून्यास्तु तथाऽत्र मधुसूदन।
विष्णुरहस्ये तु---
पत्नी भर्तुर्वियोगं च भर्ता भार्यासमुद्भवम्।
नाप्नुवन्ति यथा दुःखं दम्पत्यानि तथा कुरु॥
यथा श्रिया युतो विष्णुर्लक्ष्मीर्देव त्वया यथा।
प्रसादात्तव देवेश भक्तिरस्तु तथाऽऽवयोः॥
मा स्म पुत्राः प्रणश्यन्तु मा धनं मा कुलक्रमः।
अग्नयो मा प्रणश्यन्तु गृहभङ्गस्तु माऽऽवयोः॥ इत्येते मन्त्राः।
एवं प्रसाद्य पूजां च कृत्वा लक्ष्म्यास्तथा हरेः।
चन्द्रायार्घ्यस्तथा देयो दध्यक्षतफलादिभिः।
अर्घ्यमन्त्रः---
गगनाङ्गणसन्दीप क्षीराब्धिमथनोद्भव।
भाभासितदिगाभोग रमानुज नमोऽस्तु ते॥ इति।
नक्तं प्रणम्यायतने हरिं भुञ्जीत वाग्यतः।
ब्राह्मणाय द्वितीयेऽह्नि शय्या देयाश्च दक्षिणाः॥
यानि तत्र महाबाहो काले सन्ति फलानि च।
मधुराणि न तीव्राणि न चापि कटुकानि च॥
दातव्यानि नृपश्रेष्ठ स्वशक्त्या शयनेऽनघ।
मधुराणि च दत्वा तु मनोवल्लभतां व्रजेत्।
तस्मात्कटुकतीव्राणि स्त्रीलिङ्गानि च वर्जयेत्॥
खर्जूरमातुलिङ्गानि स्थितेन शिरसा सह।
(स्थितेन शिरसा दृढनारीकेलफलेनेत्यर्थः।)
एतान्येव तु विप्रस्य गाङ्गेय सहितानि च॥
द्वितीयेऽह्नि प्रदेयानि भच्या शक्या च भारत।
वासोदानं तथा धान्यं फलदानसमन्वितम्॥
एवं करोति यः सम्यङ्नरो मासचतुष्टयम्।
सप्तजन्मत्रयं वीर गृहभङ्गो न जायते॥ इति।
पाद्मे---
गीतवादित्रनिर्घोषं देवदेवस्य कारयेत्।
घण्टा वाद्यमशक्तस्य सर्ववाद्यमयी यतः॥
एवं सम्पूज्य गोविन्दमश्नीयात्तैलवर्जितम्।
नक्तमक्षारलवणं यावन्मासचतुष्टयम्॥
ततः प्रभाते सञ्जाते लक्ष्मीपतिसमन्विताम्।
दीपान्नभोजनैर्युक्तां शय्यां दद्याद्विचक्षणः॥
पादुकोपानहच्छत्रचामरासनसंयुताम्।
अभीष्टोपस्करैर्युक्तां शुक्लपुष्पाम्बरैर्वृताम्॥
सोपधानकविश्रामां फलैर्नानाविधैर्युताम्।
तथाऽऽभरणधान्यैश्च यथाशक्ति-समन्विताम्॥
अव्यङ्गा गौश्च विप्राय वैष्णवाय कुटुम्बिने।
दातव्या वेदविदुषे न बकव्रतिने क्वचित्॥
तत्रोपवेश्य दम्पत्यमलङ्कृत्य विधानतः।
पत्न्यास्तु भोजनं दद्याद्भक्ष्यभोज्यसमन्वितम्॥
ब्राह्मणस्यापि सौवर्णीमुपस्करसमन्विताम्।
प्रतिमां देवदेवस्य सोदकुम्भां निवेदयेत्॥
एवं यस्तु पुमान्कुर्यादशून्यशयनं हरेः।
न तस्य वित्तविरहः कदाचिदपि जायते।
नारी वा विधवा राजन्यावच्चन्द्रार्कतारकम्। इति।
मात्स्ये---
न विरूपं न शोकार्तं दम्पत्यं जायते क्वचित्।
न पुत्रपशुरत्नानि क्षयं यान्ति द्विजोत्तम॥
सप्तकल्पसहस्राणि सप्तकल्पशतानि च।
कुर्वन्नशून्यशयनं सूर्यलोके महीयते॥ इति।
अस्मिन् चन्द्रोदये पूजाविधानाच्चन्द्रोदयव्यापिन्येव तिथि ग्राह्या। दिनद्वयेऽपि तत्सत्त्वासत्त्वयोः परैव।
चतुर्ष्वसितपक्षेषु मासेषु श्रावणादिषु।
अशून्याख्यं व्रतं कुर्याज्जयया तु फलाधिकम्। इति वचनात्।
"""
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 7
anga_type = "tithi"
anga_number = 17
kaala = "चन्द्रोदयः"
priority = "paraviddha"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Bhagavan Mahavishnu sleeps with Devi Mahalakshmi on this day. Do Puja by placing the Bhagavan/Devi on a new bed with pillow/blanket. Do danam of same after puja."

[names]
sa = [ "अशून्यशयन-व्रतम्",]
