jsonClass = "HinduCalendarEvent"
default_to_none = true
id = "â˜…cUDAmaNi-candra-grahaNam~(kEtugrasta)"
tags = [ "RareDays", "Eclipses",]

[timing]
jsonClass = "HinduCalendarEventTiming"
default_to_none = true
