default_to_none = true
id = "gOpadma-vrata-samApanam"
tags = [ "SpecialVratam",]
references_secondary = [ "https://madhwafestivals.wordpress.com/2016/09/28/go-padma-vrata/",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 8
anga_type = "tithi"
anga_number = 12
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "गोपद्म-व्रत-समापनम्",]
