id = "bhAgyanagare_marUnmattoplavaH_1979"
jsonClass = "HinduCalendarEvent"

[timing]
month_type = "gregorian"
anga_type = "day"
month_number = 11
anga_number = 23
year_start = 1979
year_start_era = "gregorian"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """
On this Friday, crazed Muslim mobs _esecrated and burned the temple of Bhagyalakshmi at Charminar in Hyderabad - They broke the main Murti of Lakshmi. The riots went on for 10 days and the shops of Marwadis were destroyed.

## Background
In 1979, dramatic events shook the Muslim world: revolution in Iran at the hands of Imam Khomeini, the occupation of Afghanistan by the Soviet Army, while in Mecca a commando of fanatics wreaked havoc at the Muslim holy site. Salahuddin Owaisi of AIMIM called for a Bandh in Hyderabad, even when India had nothing to do with it. 

## Aftermath
The riots stopped only after Saudi Arabia regain control of Grand Mosque in Mecca.  
After the riots, the Congress Government led by then CM Chenna Reddy did not take ANY action against MIM rioters.
"""

[names]
sa = [ "भाग्य-नगरे मरून्मत्तोपप्लवः १९७९",]
