default_to_none = true
id = "kAJcI_2_jagadguru_zrI~surEzvarAcArya_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
गौडः काश्मीरजन्मा कलितपरिचितिः पूर्वतन्त्रे कुमाराद्
ब्रह्मण्यः सर्ववेदः स्फुटशपथपथं श्रीमदाचार्ययोधी।
सन्न्यासं प्रापितस्तं तदनु परिचरन् योगभूमैकसीमा
तस्यादेशेन काञ्च्याम् अवसदथ समाः सप्ततिं कामपीठे॥५॥
वर्षे शुद्धतरे (२६९५) कलेरथ भवे ज्येष्ठे सितद्वादशी-
रात्रौ चित्रितसर्वभूः स यशसा श्रीमान् सुरेशः स्वयम्।
श्रित्वा पुण्यरसां रसेन महता युञ्जन् लयाख्ये पथि
श्लक्ष्णश्रीशिवलिङ्गभूयम् अभजत् साक्षात् सतां पश्यताम्॥६॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-02.jpg"
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 3
anga_type = "tithi"
anga_number = 12
kaala = "अपराह्णः"
year_start = 2696
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "A native of Gauḍadeśa, born in Kashmir, pious, Śri Sureśvara, secured the knowledge of Pūrva Mīmāṁsa from Kumārila Bhaṭṭa, well-versed in Vedas, and avowed to house-holder's life; he engaged in debate with Ācārya and got initiated into asceticism. Then, attending on Ācārya, he reached the highest level in yogic practices and by the directions of the Ācārya, he lived for seventy years at the Kāmapīṭha in Kāñci. Then, in the year 2695 of the Kali era, on the night of the twelfth day of the bright fortnight in the month of Jyeṣṭha of the Bhava year that revered Sureśa, having taken the world by surprise through his fame by traversing throughout the earth, united/merged with the Supreme Being in the path known as Laya obtained the state of beautiful form of Śivaliṅga verily in the presence of on-lookers."

[names]
sa = [ "काञ्ची २ जगद्गुरु श्री-सुरेश्वराचार्य आराधना",]
