default_to_none = true
id = "kAJcI_5_jagadguru_zrI~jJAnAnandEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
जातो मङ्गलनाम्नि चोलविषये नागेशसंज्ञाद् द्विजा-
च्छ्रीज्ञानोत्तम इत्यवाप्तबिरुदो यस्तार्किकाग्रेसरः।
ज्ञानानन्दमुनिस्त्रिषष्टिशरदः सम्मण्ड्य पीठीं गुरोः
सिद्धिं मन्मथमार्गशीर्षसितसप्तम्याम् अवापत्सुधीः॥१२॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-05.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 9
anga_type = "tithi"
anga_number = 7
kaala = "अपराह्णः"
year_start = 2897
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Born of a brahmin called Nāgeśa in the village called Maṅgala of the Chola country, the erudite saint well-known as Śrī Jñānottama, foremost among logicians, having adorned the Pīṭha of preceptors for sixty-three years, attained salvation/siddhi on the seventh day of the bright fortnight in the month of Mārgaśīrṣa of the year Manmatha."

[names]
sa = [ "काञ्ची ५ जगद्गुरु श्री-ज्ञानानन्देन्द्र सरस्वती आराधना",]
