default_to_none = true
id = "kAJcI_29_jagadguru_zrI~pUrNabOdhEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
श्रीपतेस्तनयः कृष्णः पूर्णबोधो दिने हरेः।
ब्रह्मभूतो नभस्यच्छे संयमीश्वर ईश्वरे॥५८॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-29.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 5
anga_type = "tithi"
anga_number = 11
kaala = "अपराह्णः"
year_start = 3719
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Son of Śrīpati, known as Kṛṣṇa before initiation, the great sage Pūrṇabodhendra, merged in Brahman on the Ekādaśi (eleventh) day of the bright fortnight of the month Śravaṇa in the year Īśvara. His preceptorship was for seventeen years."

[names]
sa = [ "काञ्ची २९ जगद्गुरु श्री-पूर्णबोधेन्द्र सरस्वती आराधना",]
