default_to_none = true
id = "pArvatIzvarayOrAndalanavratam"
tags = [ "LessCommonFestivals",]
shlokas = """
तृतीयायां मधोर्देवीं शङ्करेण समन्विताम्।
कुङ्कुमागरुकर्पूरमणिवस्त्रसुगन्धकैः॥
स्रग्गन्धधूपदीपैश्च दमनेन विशेषतः।
आन्दोलयेत्ततो वत्स शिवोमातुष्टये सदा॥
रात्रौ जागरणं कार्यं प्रातर्देया च दक्षिणा।
हेमवस्त्रान्नपानानि ताम्बूलानि स्रजस्तथा।
सौभाग्याय सदा स्त्रीभिः कार्या पुत्रसुखेप्सुभिः॥
---देवीपुराणम् (स्मृतिकौस्तुभे)
"""
references_primary = [ "Smriti Kaustubham p.90",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 1
anga_type = "tithi"
anga_number = 3
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "पार्वतीश्वरयोरान्दोलनव्रतम्",]
