default_to_none = true
id = "caNDEzvara_nAyan2mAr_(20)_gurupUjai"
tags = [ "NayanmarGurupujai",]
references_secondary = [ "63 Nayanmar Saints by Swami Sivananda, published by The Divine Life Society",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "sidereal_solar_month"
priority = "paraviddha"
month_number = 10
anga_type = "nakshatra"
anga_number = 12
kaala = "प्रातः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """
Between the 6th and 9th centuries, in South India, there existed 63 ardent devotees of Bhagavan Shiva, collectively known as the Nayanmars. These devout individuals, hailing from various walks of life including potters, fishermen, farmers, merchants, priests, hunters, and washermen, created devotional songs still sung by followers around the globe. Among these Nayanmars, Appar, Sambandar, and Sundarar, known for their Thevaram hymns, along with Manikkavasagar, are distinguished as the Samayacharyas or the ‘The Four’ (`nAlvar`) revered teachers of the faith. They were instrumental in promoting the Shaiva Siddhanta philosophy and culture, effectively challenging the spread of Jainism and Buddhism. Their teachings centered around the concept that Shiva embodies love, and that embracing love for all beings and existence is essential in connecting with Shiva, the Supreme Being.

Vichara Sarman, later known as Chandesvara Nayanmar, was a prodigious child from Tiruchaijnanallur, a place renowned for Vedic learning and devotion to Bhagavan Shiva. By the age of five, he had self-learned the Vedas and Agamas due to his past life impressions. After his Upanayanam, he formally studied the Vedas under a Guru and aspired for liberation in this life.

One day, Vichara Sarman witnessed a cowherd beating a cow and intervened, admonishing the cowherd for mistreating the sacred animal. He took over the responsibility of tending the cows himself. Under his care, the cows flourished, and there was an abundance of milk, which he used to perform Abhishekam to a mud-constructed Shiva Lingam under an Atti tree (`audumbaravRkSaH`) by the river.

However, a villager witnessed this and complained to the cow owners that Vichara Sarman was wasting milk on mud and sand. His father, Echhadattan, upon hearing the complaint, secretly observed Vichara Sarman's ritual. Misinterpreting his son's devotion, the father attempted to disrupt the ritual, prompting Vichara Sarman to defend the worship by striking his father with a stick, which miraculously turned into an axe and killed his father.

This act was a divine test of Vichara Sarman's devotion. Bhagavan Shiva, impressed by his unwavering devotion, appeared before him with Devi Parvati. Vichara Sarman was transformed into a divine form akin to Bhagavan Shiva and adorned with a garland from the Bhagavan, attaining Saroopya Mukthi (liberation with the attainment of the form of the Bhagavan). The Bhagavan then declared that Vichara Sarman would soon reach Chandikeshvarar's Abode and be worshipped in the same way he had worshipped the Bhagavan with food, clothes, and flowers. Both Vichara Sarman and his father, purified by this supreme act of devotion, attained the abode of Bhagavan Shiva.
"""

[names]
ta = [ "caNDEzvara nAyan2mAr (20) gurupUjai",]
