default_to_none = true
id = "zrI~zESAdri-svAmI~ArAdhanA"
tags = [ "MahapurushaEvents",]
shlokas = """
करुणासागरं शान्तम् अरुणाचलवासिनम्।
श्रीशेषाद्रिगुरुं वन्दे ब्रह्मीभूतं तपोनिधिम्॥
"""
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "solar_month"
priority = "vyaapti"
month_number = 9
anga_type = "tithi"
anga_number = 24
kaala = "अपराह्णः"
year_start = 5030
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """Mahan Seshadri Swamigal (1870–1929) was a revered saint and Jivanmukta who lived in Tiruvannamalai, celebrated for His intense asceticism and miraculous powers. Born in Kanchipuram, His divine nature was evident from a tender age, earning him the famous moniker “Thanga Kai” or “Saint with the Golden Hand”. This title originated from a famous childhood incident where the four-year-old Seshadri touched a statue of Lord Krishna in a shop that was struggling to make sales. By the end of that day, the shopkeeper miraculously sold His entire inventory of 1,000 statues, cementing the belief that Seshadri’s mere touch brought immense prosperity.

At the age of nineteen, Seshadri Swamigal moved to Tiruvannamalai, the abode of Lord Arunachala, where he remained for forty years until His Mahāsamādhi. To avoid public adoration and remain absorbed in His inner bliss, he often feigned madness, wandering the streets and sleeping on the bare ground without a fixed home. He was known to storm into shops and toss items around chaotically; however, rather than being angered, shopkeepers welcomed these disruptions. They understood that His “madness” was a blessing in disguise, as His chaotic presence invariably led to a massive boost in business for them that day.

His life was intimately connected with that of His contemporary, Bhagavan Ramana Maharshi. Arriving in Tiruvannamalai six years before Ramana, Seshadri Swamigal played a crucial, protective role as a guardian to the younger saint. When the young Ramana was absorbed in deep penance in the underground Patala Lingam vault, suffering from insect bites and stones thrown by local urchins, it was Seshadri who stood guard and eventually helped bring him to safety. The two shared a profound, silent spiritual bond, with Ramana Maharshi regarding him with deep respect, often viewing him as an “elder brother" in the spiritual realm.

A staunch devotee of Devi Kamakshi and Bhagavan Arunachala, he emphasised the spiritual potency of Girivalam (circumambulating the holy hill) and Annadānam. Today, His vibrant legacy continues at His Samadhi shrine (https://maps.app.goo.gl/imR6Kh4fhrrwDAqq5) located near Ramanasramam (https://maps.app.goo.gl/VpP3z4XBVsBi2mcq5), which remains a powerful center for meditation and worship for devotees seeking His grace."""

[names]
sa = [ "श्री-शेषाद्रि-स्वामि-आराधना",]
