id = "nArAyaNa-rAvo_hataH"
jsonClass = "HinduCalendarEvent"

[timing]
month_type = "gregorian"
anga_type = "day"
month_number = 8
anga_number = 30
year_start = 1773
year_start_era = "gregorian"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """
In an event that shook the marATha empire, the peshva nArayaNa rAv, brother of the great mAdhavarAv and vishvAs-rAv, was killed on the last day of gaNapati festival (Ananta Chaturdashi) in puNe.

According to popular legend, Raghunathrao had sent a message to Sumer Singh Gardi to fetch Narayanrao using the Marathi word dharaa (धरा) or 'hold' (actual phrase in Marathi - " नारायणरावांना धरा"/"Narayanrao-ana dhara"). This message was intercepted by his wife Anandibai who changed a single letter to make it read as maaraa (मारा) or 'kill' . The miscommunication led the Gardis to chase Narayanrao, who, upon hearing them coming, started running towards his uncles' residence screaming, "Kaka! Mala Vachva!!" ("Uncle! Save me!"). The Gardis followed Narayanrao to his uncle's chamber and the menial Tulaji Pawar pulled him while Sumer Singh Gardi cut him down. At the scene, a total of 11 persons were killed. Historian Sardesai writes that these 11 victims included seven brahmins (including Narayanrao), two Maratha servants and two maids.

## Aftermath
The Chief Justice, Ram Shastri Prabhune was asked to conduct an investigation into the incident, and Raghunathrao, Anandibai and Sumer Singh Gardi were all prosecuted in absentia. Although Raghunathrao was acquitted, Anandibai was declared an offender and Sumer Singh Gardi the culprit. Sumer Singh Gardi died mysteriously in Patna, Bihar in 1775, and Anandibai performed Hindu rituals to absolve her sins. Kharag Singh and Tulaji Pawar were handed over by Hyder Ali back to the government and they were tortured to death.

व्As the result of the murder, senior ministers and generals of the Maratha confederacy formed a regency council , known as the "Baarbhai Council", to conduct of the affairs of the state in the name of his soon to be born son, mAdhavarAv 2.
"""

[names]
sa = [ "नारायणरावो हतः",]
