default_to_none = true
id = "kAJcI_67_jagadguru_zrI~mahAdEvEndra_sarasvatI_5_ArAdhanA"
tags = [ "KanchiAradhanaDays", "CommonFestivals",]
shlokas = """
लक्ष्मीनरसिंहयुगलपुत्रो लक्ष्मीकान्तो गुरुवरसेवाम्।
एकां कृत्वा वटुरपि भिक्षुः काष्ठां प्राप्तो जननम् अतीताम्॥२१॥
त्रिविशलूर्‌ग्रामजातः शिष्यमात्रग्रजासुतः।
त्रैविष्टपैर्दुर्भजं सच्छिष्यतामात्रतोऽभजत्॥२२॥
कलवैनामके ग्रामे स्वगुरोरेव सन्निधौ।
आऽन्तं तस्यैव शुश्रूषां कृत्वा देहान्तम् आप्तवान्॥२३॥
गुरुर्महादेवेन्द्राख्यः सप्ताही सिद्धिम् आययौ।
पराभवे फाल्गुने तु शुक्लायां प्रतिपत्तिथौ॥२४॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-67.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 12
anga_type = "tithi"
anga_number = 1
kaala = "अपराह्णः"
year_start = 5008
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Preceptor by name Mahādevendra adorning Pīṭha attained siddhi on the first day (pratipat) of bright fortnight of Phālguna month in the year Parābhava. The name of this preceptor before initiation was Lakṣminārāyaṇa. His father was well-known as Narasimhaśāstri. This preceptor was well-versed in Ṛgveda. His place of sidhi was Kalavai village in Śalivahana era 1830."

[names]
sa = [ "काञ्ची ६७ जगद्गुरु श्री-महादेवेन्द्र सरस्वती ५ आराधना",]
