default_to_none = true
id = "kAJcI_61_jagadguru_zrI~mahAdEvEndra_sarasvatI_4_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
अद्वैतात्मप्रकाशेन्द्राद् बाल्य आश्रितसंयमः।
नारायण आदिपुरे लिल्येऽनशनतत्परः॥६॥
महादेवेन्द्राख्यो गुरुवर इहाचार्यपदवीं
समाश्चत्वारिंशद् द्विशरदधिका बिभ्रद् अतुलाम्।
महायोगी साक्षात्कृतपरमहाः क्रोधनसमे
तथा ज्येष्ठे शुक्ले नवमसुतिथौ सिद्धिम् अभजत्॥७॥
—पुण्यश्लोकमञ्जरी परिशिष्टम्
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-61.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 3
anga_type = "tithi"
anga_number = 9
kaala = "अपराह्णः"
year_start = 4847
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Here (in this world) the best among preceptors by name Mahādevendra adorned the incomparable seat of preceptor for forty-two years; thus the great Yogi realised the Self and attained siddhi on the ninth day of bright fortnight in the month of Jyeṣṭha in the year Krodhana. Ātmabodha, who wrote a commentary Suṣamā on Śrī Sadāśivabrahmendra’s Gururatnamālika also belonged to this period (a contemporary of this preceptor). Only during this period, the Jagadguru Maṭha moved out of Kāñci. The place where this present preceptor attained siddhi was the wellknown Tiruvottiyur situated in the north of Madras (Śalivahana era 1664)."

[names]
sa = [ "काञ्ची ६१ जगद्गुरु श्री-महादेवेन्द्र सरस्वती ४ आराधना",]
