default_to_none = true
id = "mahAzivarAtriH"
tags = [ "CommonFestivals",]
jsonClass = "HinduCalendarEvent"
shlokas = """
श्रीब्रह्मवैवर्ते महापुराणे ब्रह्मखण्डे सौतिशौनकसंवादे नारदं प्रति शिवोपदेशे भक्ष्याभक्ष्यादिविवरणं नाम सप्तविंशतितमोऽध्यायः---
जन्माष्टमीदिने रामनवमीदिवसे हरेः।
शिवरात्रौ च यो भुङ्क्ते सोऽपि द्विगुणपातकी॥११॥
"""

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "paraviddha"
month_number = 11
anga_type = "tithi"
anga_number = 29
kaala = "निशीथः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "All related events e.g. kAmadahanam"

[names]
sa = [ "महाशिवरात्रिः",]
