default_to_none = true
id = "rambhA~tRtIyA"
tags = [ "SpecialVratam",]
shlokas = """
पुष्पमण्डपिका कार्या रम्भास्तम्भोपशोभिता।
तत्र सम्पूजयेद्देवीं शक्त्या स्वर्णादिनिर्मिताम्॥
वेदेषु सर्वशास्त्रेषु दिवि भूमौ रसातले।
श्रुतो दृष्टश्च बहुशो न शक्त्या रहितः शिवः।
त्वं शक्स्तिस्त्वं स्वधा स्वाहा त्वं सावित्री सरस्वती।
पतिं देहि सुतान्देहि गृहं देवि नमोऽस्तु ते॥
योषितः पुरुषो वाऽपि ख्यातं रम्भाव्रतं भुवि।
भार्यां पुत्रं गृहं भोगान् कुलवृद्धिमवाप्नुयुः॥
"""
references_secondary = [ "Smriti Kaustubha p.118",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 3
anga_type = "tithi"
anga_number = 3
priority = "paraviddha"
kaala = "प्रातः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Rambha Vratam; perform Savitri pooja near Banana tree. Offer naivedyam of bananas prepared with ghee."

[names]
sa = [ "रम्भा-तृतीया",]
