default_to_none = true
id = "mahAdhanurvyatIpAta-snAnam"
tags = [ "SpecialSnanam",]
jsonClass = "HinduCalendarEvent"
shlokas = """
पुष्ये च जन्मनक्षत्रे व्यतीपाते च वैधृतौ।
अमायां च नदीनानं पुनात्यासप्तमं कुलम्॥
व्यतीपात महाबाहो सर्वपापप्रणाशन।
सहस्रबाहो विश्वात्मन् गृहाणार्घ्यं नमोऽस्तु ते॥
"""

[timing]
default_to_none = true
month_type = "sidereal_solar_month"
priority = "puurvaviddha"
month_number = 9
anga_type = "yoga"
anga_number = 17
kaala = "प्राक्तनारुणोदयः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Special `snAnam` on account of `mahAdhanurvyatIpAtam`. `snAnam` on any `vyatIpata` day gives `mahApuNyam`, more so in `dhanurmAsa`."

[names]
sa = [ "महाधनुर्व्यतीपात-स्नानम्",]
