default_to_none = true
id = "dauhitra-pratipat"
tags = [ "CommonFestivals",]
jsonClass = "HinduCalendarEvent"
shlokas = """
अथाश्विनशुक्लप्रतिपदि दौहित्रेण मातामहश्राद्धं कार्यम्॥ 
तदुक्तं हेमाद्रौ---
जातमात्रोऽपि दौहित्रो जीवत्यपि च मातुले।
कुर्यान्मातामहश्राद्धं प्रतिपद्याश्विने सिते॥
इयं च सङ्गवव्यापिनी ग्राह्येति निर्णयदीपे उक्तम्॥
प्रतिपद्याश्विन शुक्ले दौहित्रस्त्वेकपार्वणम्।
श्राद्धं मातामहं कुर्यात् सपिता सङ्गवे सति॥
जातमात्रोपि दौहित्रो जीवत्यपि हि मातुले।
प्रातः सङ्गबयोर्मध्ये याऽश्वयुक्प्रतिपद्भवेत्॥
अत्र सपिता इति विशेषणाज्जीवत्पितृक एवाधिकारी पिण्डरहितं कुर्यात्॥
मुण्डनं पिण्डदानं च प्रेतकर्म च सर्वशः।
न जीवत्पितृकः कुर्याद्गुर्विणीपतिरेव च॥ इति पिण्डनिषेधात्॥
"""

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 7
anga_type = "tithi"
anga_number = 1
kaala = "साङ्गवः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "If the maternal grandfather is no more, grandson must perform shraddha for maternal grandfather. Grandson must seek blessings of his maternal grandparents, and bestow gifts."

[names]
sa = [ "दौहित्र-प्रतिपत्",]
