id = "nava-shera-yuddham"
jsonClass = "HinduCalendarEvent"

[timing]
month_type = "gregorian"
anga_type = "day"
month_number = 3
anga_number = 14
year_start = 1823
year_start_era = "gregorian"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """
On this day, raNajIt singh and his generals (including hari singh) defeated afghAn jihAdi-s and captured peshAvar valley. Azem Khan, after initial attacks, retreated and stayed on the other side of kAbul river - abandoning his ghAzi-s.

## Context
Angered by his defeats, Azem Khan recaptured Peshawar in 1822, he made a call for jihad against the Sikhs; destroyed the Attck bridge and trapped Sikh garrisons west of the sindhu.  Ranjit Singh had already reinforced his forces in Nowshera. Ranjit Singh personally came down and crossed the sindhu under fierce attacks.

## Aftermath
The tribesman of Khattaks and Yousafzais suffered enormous casualties due to the Sikh artillery. Swiftly securing Nowshera, Ranjit Singh's forces captured Peshawar and reached Jamrud itself.
"""

[names]
sa = [ "नवशेर-युद्धम्",]
