default_to_none = true
id = "mAsazivarAtriH"
tags = [ "MonthlyFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "paraviddha"
month_number = 0
anga_type = "tithi"
anga_number = 29
kaala = "निशीथः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Monthly Shivaratri day."

[names]
sa = [ "मासशिवरात्रिः",]
