id = "mAdhavarAvo_bhavati_pradhAnamantrI"
jsonClass = "HinduCalendarEvent"

[timing]
month_type = "gregorian"
anga_type = "day"
month_number = 7
anga_number = 20
year_start = 1761
year_start_era = "gregorian"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """
On this day, shortly after the disaster at pAnIpat, the great mAdhavarAv became peshvA, with Raghunathrao (paternal uncle) as co-regent with Gopikabai, Madhavrao’s mother.

Madhavrao's Peshwaship lasted eleven years and four months, from 20 July 1761 to 18 November 1772, the first two years of which were a period of tutelage as we have already seen. During his last year he was entirely bed-ridden, so that it was only for about eight years that he actively controlled the management of affairs and marked his personal stamp on the administration, His activities may be arranged under four main heads, viz. :

- 1. His Karnatak expeditions for putting down Haidarali; 
- 2. His relations with Nizam Ali ;
- 3. His struggle first against his own uncle and then against the Bhosles of Nagpur ; and lastly
- 4. The revival of Maratha power in the north.
"""

[names]
sa = [ "माधवरावो भवति प्रधानमन्त्री",]
