id = "zorAvara-siMha-mRtyuH"
jsonClass = "HinduCalendarEvent"

[timing]
month_type = "gregorian"
anga_type = "day"
month_number = 12
anga_number = 12
year_start = 1841
year_start_era = "gregorian"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """
On this day died the Kahluria Rajput general Zorawar Singh (under Gulab Singh) on his remarkable Tibetan expedition, after his pilgrimage to mAnasasarovara and kailAsa. Snow had caused supplies to the Dogra army to fail despite Zorawar's preparations. In the early exchange of fire the Rajput general was wounded in his right shoulder but he grabbed a sword in his left hand. The Tibetan horsemen then charged the Dogra position and one of them thrust his lance in Zorawar Singh's chest.
"""

[names]
sa = [ "ज़ोरावरसिंह-मृत्युः",]
