default_to_none = true
id = "madana-trayOdazI"
shlokas = """
चैत्रशुक्लत्रयोदश्यां मदनं चम्पकात्मकम्।
कृत्वा सम्पूज्य यत्नेन वीजयेद्यजनेन तु।
ततः सन्धुक्षितः कामः पुत्रपौत्रसमृद्धिदः॥
"""
references_primary = [ "Smriti Kaustubham p.104",]
tags = [ "LessCommonFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 1
anga_type = "tithi"
anga_number = 13
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "मदन-त्रयोदशी",]
