default_to_none = true
id = "zrIrAmanavamI"
tags = [ "Dashavataram", "CommonFestivals",]
jsonClass = "HinduCalendarEvent"
shlokas = """
चैत्रशुक्लनवम्यां तु मध्याह्ने रघुनन्दनः।
दशाननवधाकाङ्क्षी जज्ञे रामः स्वयं हरिः॥
अवतारदिने पुण्ये हरिमुद्दिश्य भक्तितः।
उपवासादि यत् किञ्चित्तदानन्त्याय कल्पते॥
अकरणे दोषमाह स्मृतिः---
यस्तु रामनवम्यां वै मोहाद्भुक्ते नराधमः।
कुम्भीपाकेषु घोरेषु पच्यते नात्र संशयः॥
(कृत्यसारसमुच्चयः)
श्रीब्रह्मवैवर्ते महापुराणे ब्रह्मखण्डे सौतिशौनकसंवादे नारदं प्रति शिवोपदेशे भक्ष्याभक्ष्यादिविवरणं नाम सप्तविंशतितमोऽध्यायः---
जन्माष्टमीदिने रामनवमीदिवसे हरेः।
शिवरात्रौ च यो भुङ्क्ते सोऽपि द्विगुणपातकी॥११॥
"""
references_primary = [ "Vaidyanatha Dikshitiyam (SVR) p.62",]

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "paraviddha"
month_number = 1
anga_type = "tithi"
anga_number = 9
kaala = "मध्याह्नः"
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "श्रीरामनवमी",]
