default_to_none = true
id = "kAJcI_12_jagadguru_zrI~candrazEkharEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
श्रीचिद्घनेन्द्रनियतः शरदस्त्रिषष्टिं श्रीकामकोटिम् अभिमण्ड्य ततश्च कञ्चित्।
सच्चिद्घनाख्यम् अनुशिष्य वृतोऽपि शिष्यैः श्रीचन्द्रशेखरगुरुः सवपुस्तिरोऽधात्॥२३॥
आनन्दमयम् आनन्दे आषाढ्याषाढपूर्वके।
नवम्याम् अनवम्यं स्वं पदम् आपत् परात्परम्॥२४॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-12.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 4
anga_type = "tithi"
anga_number = 9
kaala = "अपराह्णः"
year_start = 3336
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Initiated by Śrī Cidghanendra, the preceptor Śrī Chandraśekhara, having adorned the Kāmakoṭi Pīṭha for sixty-three years, then having initiated/ imparted on e named Saccidghana, vanished with form in the midst of disciples. He attained his exalted Supreme state on the ninth day of the bright fortnight in the month of Āṣāḍha of the year Ānanda."

[names]
sa = [ "काञ्ची १२ जगद्गुरु श्री-चन्द्रशेखरेन्द्र सरस्वती आराधना",]
