default_to_none = true
id = "karavIra-vratam"
tags = [ "SpecialVratam",]
shlokas = """
करवीर विषावास नमस्ते भानुवल्लभ।
मौलिमण्डन दुर्गादि देवानां सततं प्रिय॥
"""
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 3
anga_type = "tithi"
anga_number = 1
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Perform puja of `karavIra` plants/flowers and then offer them in `arcanA`."

[names]
sa = [ "करवीर-व्रतम्",]
