default_to_none = true
id = "kAJcI_16_jagadguru_zrI~ujjvala_zaGkarEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
सूनुः केशवशङ्करस्य तपतीतीरोद्भवो नैष्ठिकः
श्रीमान् अच्युतकेशवः श्रितपदो वञ्चीश्वरे गीष्पतेः।
आदेशात् कृतसंयमश्च विमतान् आमूलम् उन्मूलयन्
आकाश्मीरम् अगान्महायतिरिति ख्यात्योज्ज्वलः शङ्करः॥३२॥
अष्टात्रिंशद् अथातिवाह्य शरदः पीठे जगद्देशिक-
स्यासीद् दिग्-रस-वार्धि-वह्निषु (३४६८) कलेर्यात्स्वक्षयेऽच्छे वृषे।
अष्टम्याम् अपहर्षशोकम् अजरं ब्रह्मैव यः शाश्वतं
काश्मीरेषु कलापुरे यदधुनाऽप्याख्यायतेऽस्याख्यया॥३३॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-16.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 3
anga_type = "tithi"
anga_number = 8
kaala = "अपराह्णः"
year_start = 3468
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Born on the banks of river Tapati as the son of Śaṅkarakeśavasya and avowed to rigid celibacy Śrī Acyutakeśava, known as Ujjvalaśaṅkara, after being initiated by Gīṣpati, patronised by Vañcīśavara, uprooted the rival schools and with fame the great saint reached Kashmir. Then having spent thirty-eight years in the Pīṭha of the Universal Preceptor, He merged in Brahman, the eternal free from joy and sorrow and the everlasting on the eighth day of the bright fortnight in Vṛṣa month of the year Akṣaya in the Kali era 3468 in the place called Kalāpur in Kashmir."

[names]
sa = [ "काञ्ची १६ जगद्गुरु श्री-उज्ज्वल शङ्करेन्द्र सरस्वती आराधना",]
