default_to_none = true
id = "naminandiyaDigaL_nAyan2mAr_(27)_gurupUjai"
tags = [ "NayanmarGurupujai",]
references_secondary = [ "63 Nayanmar Saints by Swami Sivananda, published by The Divine Life Society",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "sidereal_solar_month"
priority = "paraviddha"
month_number = 2
anga_type = "nakshatra"
anga_number = 8
kaala = "प्रातः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """Between the 6th and 9th centuries, in South India, there existed 63 ardent devotees of Bhagavan Shiva, collectively known as the Nayanmars. These devout individuals, hailing from various walks of life including potters, fishermen, farmers, merchants, priests, hunters, and washermen, created devotional songs still sung by followers around the globe. Among these Nayanmars, Appar, Sambandar, and Sundarar, known for their Thevaram hymns, along with Manikkavasagar, are distinguished as the Samayacharyas or the ‘The Four’ (`nAlvar`) revered teachers of the faith. They were instrumental in promoting the Shaiva Siddhanta philosophy and culture, effectively challenging the spread of Jainism and Buddhism. Their teachings centered around the concept that Shiva embodies love, and that embracing love for all beings and existence is essential in connecting with Shiva, the Supreme Being.

Nami Nandi Adigal, a devout Brahmana from Emaperur in the Chola kingdom, dedicated his life to worshipping Bhagavan Shiva in Tiruvarur. One day, driven by a desire to light numerous lamps in the temple as extolled in the Shiva Agamas, he sought ghee from a nearby house. However, the Jaina inhabitant mockingly suggested using water instead. Distressed, Nandi Adigal prayed to Bhagavan Shiva and was divinely instructed to use water from a nearby tank for lighting the lamps. Miraculously, the lamps burned brightly with water, astonishing the Jainas and leading to a decline in Jainism as people turned to Shaivism.

Recognising his devotion, the Chola king appointed Nandi Adigal as the head of the temple. He zealously conducted the Panguni Uttaram festival at Tirumanali, drawing worshippers of all castes. One night, feeling unpurified by the contact with people of various castes, he hesitated to enter his home. As he waited for his wife to bring him water to bathe, he fell asleep and dreamt of Bhagavan Shiva, who revealed that all born in Tiruvarur were His ganas! Awakening, Nandi Adigal narrated this story to his wife, and performed his worship. In the morning, he went back to Tiruvarur and saw that the people of Tiruvarur bore the form of Bhagavan Shiva! As he prostrated to them, they all resumed their original forms --- thus a divine Lila being enacted by the Bhagavan.

Settling in Tiruvarur, Nandi Adigal devoted himself to serving the Bhagavan and His devotees, earning praise as 'Anipon' (pure gold) from the Nayanmar Appar. He ultimately attained the sublime abode of Bhagavan Shiva, exemplifying pure devotion and service."""

[names]
ta = [ "naminandiyaDigaL nAyan2mAr (27) gurupUjai",]
