default_to_none = true
id = "kAJcI_21_jagadguru_zrI~sArvabhaumaguruH_candracUDEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
अर्चाचन्दनपेषणाद् भगवतः श्रीशङ्करेन्द्रार्चित-
स्यारूढः पदवीं कवेरनुसृतेर्हर्षस्य भूत्वा नृपः।
काश्मीरेषु विरज्य विक्रम-मृतौ गृह्णन् गुरोः प्राक्तनात्
सन्न्यासं स हि कोङ्कणाच्युतसुतः श्रीचन्द्रचूडोऽभवत्॥४५॥
अब्दान् देवनदीतटे दश नयन् आचार्यभूतो भुवो
धन्वन्तर्यवतारम् आर्यमधुरं निक्षिप्य पीठे निजे।
दत्त्वाऽस्मै परिपूर्णबोधबिरुदं भेजे व्यये चाव्ययं
धाम स्वं जननाष्टमीनिशि हरेः श्रीचन्द्रचूडाश्रमी॥४६॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-21.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 5
anga_type = "tithi"
anga_number = 23
kaala = "अपराह्णः"
year_start = 3548
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Son of Śrī Acyutaśarmā of Koṅkaṇadeśa, having offered his services of preparing sandal paste for the worship of Śrī Chandramoulīśvara, He was offered kingship of Kashmir by King Harṣa for his poetical wisdom/merits. Having ruled Kashmir for a short period, He came back to his preceptor Arbhakaśaṅkara and got initiated into asceticism with the name Sārvabhauma Chandracūḍendra Sarasvatī. Preceptor Śrī Chandracūḍendra Sarasvatī leading for ten years a pious life on the banks of Ganges, establishing on his throne revered Madhura the incarnation of Dhanvantari and adorning him with the title Paripūrṇabodha reached/attained his Lord’s immortal abode on the night of Kṛṣṇajanmāṣṭamī in the year Vijaya."

[names]
sa = [ "काञ्ची २१ जगद्गुरु श्री-सार्वभौमगुरुः चन्द्रचूडेन्द्र सरस्वती आराधना",]
