default_to_none = true
id = "kAJcI_11_jagadguru_zrI~zivAnanda_cidghanEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
कर्णाटोज्ज्वलसूनुरीश्वरवटुः श्रित्वा सुरेशं चिरात्
श्रीभाष्याद्युपलभ्य तस्य च धुरामासाद्य पीठे वसन्।
निन्ये तत्र शिवाः (४५) समाः शिव इव श्रेयोऽर्थिनां देहिनां
दातुं श्रेय उपागतोऽयमिव यः श्रीचिद्घनाख्यो बभौ॥२१॥
प्राप्तं क्षीरसरित्तटाद् हरिरिति ख्यातं च वात्स्यायनं
पीठे स्वे विनिवेश्य दत्तनियमं सञ्चार्य च प्रक्रियाम्।
कल्यब्दे च विरोधिकृत्यनुतपं(पः?) शुद्धे दशम्यामगात्
स्वं रूपं परमं सुधीशतनुतः श्रीचिद्घनश्चिद्घनम्॥२२॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-11.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 11
anga_type = "tithi"
anga_number = 10
kaala = "अपराह्णः"
year_start = 3273
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "The boy Īśvara, son of Ujjvala bhaṭṭa of Karnataka, known as Cidghana, who approached Sureśvara and acquired the knowledge of bhāṣyas etc., having got his (Sureśvara’s) responsibility and remaining in the Pīṭha there, this Cidghana spent forty-five years as if Śiva Himself had come there to grant liberation to those who seek liberation. Revered by the wise, Cidghana having placed Vātsyāyāna, the initiated who was hailed as Hari arrived from Milky Ocean, and imparting the precepts He had attained his form, the pure consciousness on the tenth day of the bright fortnight in the month of Jyeṣṭha in the year Virodhikṛt of the Kali era."

[names]
sa = [ "काञ्ची ११ जगद्गुरु श्री-शिवानन्द चिद्घनेन्द्र सरस्वती आराधना",]
