default_to_none = true
id = "mahAlaya-pakSa-tarpaNa-pUrtiH"
tags = [ "SpecialPeriodEnd", "CommonFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
anchor_festival_id = "mahAlaya-pakSa-ArambhaH"
offset = 16
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Mahalaya Paksha Tarpana of 16 days ends today."

[names]
sa = [ "महालय-पक्ष-तर्पण-पूर्तिः",]
