default_to_none = true
id = "dhUmAvatI~jayantI"
tags = [ "Dashamahavidya",]
references_secondary = [ "http://hindupad.com/dhumavati-jayanti-maa-dhumavathi-jayanthi/",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 3
anga_type = "tithi"
anga_number = 8
kaala = "मध्यरात्रिः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Goddess Dhumavati is 7th of the Dasha Maha Vidyas."

[names]
sa = [ "धूमावती-जयन्ती",]
