default_to_none = true
id = "hEramba-mahAgaNapati_mahAsaGkaTahara-caturthI-vratam"
tags = [ "MonthlyVratam", "SankataharaChaturthiVratam",]
shlokas = """
गणाधिपस्त्वं देवेश चतुर्थ्यां पूजितो मया।
कष्टान्मां मोचयेशान सर्वमिष्टं च देहि मे॥

यदा सङ्क्लेशितो मर्त्यो नानादुःखैश्च दारुणैः।
तदा कृष्णे चतुर्थ्यां वै पूजनीयो गणाधिपः॥ (भविष्यपुराणम्)

श्रावणकृष्णचतुर्थ्यां प्रारभ्य कृष्णचतुर्थीषु यावज्जीवमेकविंशतिवर्षाणि एकवर्षं वा सङ्कटचतुर्थीव्रतं कार्यम्॥
अशक्तौ प्रतिवर्षं श्रावणचतुर्थ्यामेव कार्यम्॥
"""
jsonClass = "HinduCalendarEvent"
references_primary = [ "Dharma Sindhu p.56",]

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Special vrata day for Ganesha. In this month, Ganesha is worshipped as `hEramba-mahAgaNapatiH`. Fast during the day and pray to Ganesha after moonrise, as follows:"

[names]
sa = [ "हेरम्ब-महागणपति महासङ्कटहर-चतुर्थी-व्रतम्",]
