default_to_none = true
id = "64_yOginI-pUjA"
tags = [ "LessCommonFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 5
anga_type = "tithi"
anga_number = 30
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "६४ योगिनी-पूजा", "ग्रामदॆवता-पूजा",]
