default_to_none = true
id = "kAJcI_54_jagadguru_zrI~vyAsAcala_mahAdEvEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
काञ्चीकामेश्वरार्यात् समजनि कमलाम्बोदरात् कुप्पणाख्यो
यः पूर्णानन्दयोगिप्रवरपदरतेः प्राप पीठीम् अमुष्य।
भाष्यं त्रिः सप्तकृत्वश्चटुलम् अचकलद् यो नवाब्द्यां प्रहृष्यन्।
 अक्षय्याषाढकृष्णप्रतिपदि स महादेवनामाऽऽप सिद्धिम्॥१०७॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-54.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 4
anga_type = "tithi"
anga_number = 16
kaala = "अपराह्णः"
year_start = 4608
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Born as the son of Kāmeśvara and Kamalāmbā of Kāñci, the one named Kupanna who having received the initiation and preceptorship with the name Mahādeva, conducted the lectures on Bhāṣya ably for twenty-one times in nine years rejoicingly, attained siddhi on the pratipad of black fortnight in the month of Āṣāḍha of the year Akṣaya. As He stayed ever in the Vyāsācala, He is known as Vyāsācala and the author of Vyāsācaliya and other works. He attained siddhi in Vyāsācala."

[names]
sa = [ "काञ्ची ५४ जगद्गुरु श्री-व्यासाचल महादेवेन्द्र सरस्वती आराधना",]
