default_to_none = true
id = "mahAlaya-pakSa-samApanam"
tags = [ "SpecialPeriodEnd", "CommonFestivals",]
references_primary = [ "Smriti Muktaphalam Shraddha Kanda Uttarabhaga",]
jsonClass = "HinduCalendarEvent"
shlokas = """
स्मृत्यन्तरे---
अमा पातश्च सङ्क्रान्तिस्तथा वैधृतिरेव च।
अष्टकाश्चैव मन्वादिर्युगादिश्च महालयः॥
चन्द्रसूर्योपरागश्च गजच्छाया तथैव च।
द्रव्यब्राह्मणसम्पत्तिः श्राद्धकालाः प्रकीर्तिताः॥
आषाढ्याः पञ्चमे पक्षे कन्यासंस्थे दिवाकरे।

यो वै श्राद्धं नरः कुर्यादेकस्मिन्नपि वासरे।
तस्य संवत्सरं यावत् तृप्तास्स्युः पितरो ध्रुवम्॥
---वैद्यनाथ-दीक्षितीये श्राद्धकाण्डे-उत्तरभागे
पितृमेधसारे---
सिंहान्तकृष्णपक्षस्यादौ मध्येऽन्ते वा कन्यार्कसङ्क्रमे कृत्स्नः पक्षो महालये प्रशस्तः,
पञ्चम्यादिदशम्याद्यष्टम्यादि वा दर्शान्तं क्वचिद्दिने वा यथाशक्ति महालय-श्राद्धं कुर्यात् इति।
प्रतिपदादिदर्शान्तं शुक्लप्रतिपदन्तं वा श्राद्धं कर्तुमशक्तश्चेत् पञ्चम्यादि दर्शान्तमष्टम्यादिदर्शान्तं
दशम्यादि दर्शान्तं वा चतुर्थ्या ऊर्ध्वमनिषिद्धे एकस्मिन् दिने वा यथाशक्ति कुर्यादित्यर्थः।
---वैद्यनाथ-दीक्षितीये श्राद्धकाण्डे-उत्तरभागे
वृद्धमनुः---
नभस्यस्यापरः पक्षो यत्र कन्यां व्रजेद् रविः।
स महालयसंज्ञः स्यात् गजच्छायाह्वयस्तथा॥
मार्कण्डेयः---
कन्यागते सवितरि दिनानि दश पञ्च च।
पार्वणेनैव विधिना तत्र श्राद्धं विधीयते॥
श्राद्धं कुर्वन्नमावास्यामन्नेन पुरुषः शुचिः।
सर्वान् कामानवाप्नोति स्वर्गं वाऽत्यन्तमश्नुते॥

कुर्यादपरपक्षीयं मासि प्रौष्ठपदे द्विजः।
श्राद्धं पित्रोर्यथावित्तं तद्बन्धूनां च वित्तवान्॥१९॥
अयने विषुवे कुर्याद् व्यतीपाते दिनक्षये।
चन्द्रादित्योपरागे च द्वादश्यां श्रवणेषु च॥२०॥
तृतीयायां शुक्लपक्षे नवम्यामथ कार्तिके।
चतसृष्वप्यष्टकासु हेमन्ते शिशिरे तथा॥२१॥
माघे च सितसप्तम्यां मघाराकासमागमे।
राकया चानुमत्या च मासर्क्षाणि युतान्यपि॥२२॥
द्वादश्यामनुराधा स्याच्छ्रवणस्तिस्र उत्तराः।
तिसृष्वेकादशी वासु जन्मर्क्षश्रोणयोगूयुक्॥२३॥
त एते श्रेयसः काला नृणां श्रेयोविवर्धनाः।
कुर्यात्सर्वात्मनैतेषु श्रेयोऽमोघं तदायुषः॥२४॥
एषु स्‍नानं जपो होमो व्रतं देवद्विजार्चनम्।
पितृदेवनृभूतेभ्यो यद्दत्तं तद्ध्यनश्वरम्॥२५॥
---श्रीमद्भागवते ७-१४"""

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 6
anga_type = "tithi"
anga_number = 30
kaala = "अपराह्णः"
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "महालय-पक्ष-समापनम्",]
