default_to_none = true
id = "candana-pUjA"
tags = [ "LessCommonFestivals",]
shlokas = """
यः करोति तृतीयायां कृष्णं चन्दन-भूषितम्।
वैशाखस्य सिते पक्षे स यात्यच्युतमंन्दिरम्॥
"""
references_primary = [ "Dharma Sindhu p.38",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "paraviddha"
month_number = 2
anga_type = "tithi"
anga_number = 3
kaala = "मध्याह्नः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = ""

[names]
sa = [ "चन्दन-पूजा",]
