default_to_none = true
id = "bhadrakALI~jayantI"
tags = [ "OtherJayantis",]
references_secondary = [ "http://hindupad.com/bhadrakali-jayanti/",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 2
anga_type = "tithi"
anga_number = 26
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "भद्रकाळी-जयन्ती",]
