default_to_none = true
id = "buddha~jayantI"
tags = [ "Dashavataram", "LessCommonFestivals",]
shlokas = """
आश्विनशुक्लदशम्यां सायं बुद्धोऽभूत्॥
---धर्मसिन्धौ
नमो बुद्धाय शुद्धाय दैत्यदानवमोहिने।
म्‍लेच्छप्रायक्षत्रहन्त्रे नमस्ते कल्किरूपिणे॥२२॥
---श्रीमद्भागवते महापुराणे पारमहंस्यां संहितायां दशमस्कन्धे चत्वारिंशोऽध्यायः
श्रीवराह उवाच---
मत्स्यं कूर्मं वराहं च नरसिंहं च वामनम्॥
रामं रामं च कृष्णं च बुद्धं चैव च कल्किनम्।  
एवं दशावतारांश्च पूजयेद् भक्तिसंयुतः॥२११-६९॥  
पद्मपुराणे---
मत्स्यं कूर्मं च वाराहं नारसिंहं च वामनम्।
रामं रामं च कृष्णं च बुधं कल्किं नमोऽस्तु ते॥६-६६-५१॥
स्मृतिमिक्ताफले---
अवतारदिने पुण्ये हरिमुद्दिश्य भक्तितः।
उपवासादि यत् किञ्चित्तदानन्त्याय कल्पते॥
"""
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "puurvaviddha"
month_number = 7
anga_type = "tithi"
anga_number = 10
kaala = "सूर्यास्तमयः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Buddha Avatara day. In many reckonings of the Dashavataras of Mahavishnu, Buddha is considered. Quoted above are shlokas from Shri Varaha Puranam and Shrimad Bhagavatam. Note that Buddha is a ‘generic name’ for an enlightened person, and this Buddha is very much distinct from Gautama Buddha, who propounded the Bauddha mata/Buddhism."

[names]
sa = [ "बुद्ध-जयन्ती",]
