default_to_none = true
id = "tulA-kAvErI-snAna-samApanam"
tags = [ "TamilnaduTempleFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
anchor_festival_id = "muDavan2_muzhukku"
offset = -1
jsonClass = "HinduCalendarEventTiming"

[description]
en = "End of Tula Kaveri Snanam. Also known as `ta:kaDaimugam`."

[names]
sa = [ "तुला-कावेरी-स्नान-समापनम्",]
