default_to_none = true
id = "muttusvAmI~dIkSita~jayantI"
tags = [ "MahapurushaEvents", "CommonFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "sidereal_solar_month"
priority = "paraviddha"
month_number = 12
anga_type = "nakshatra"
anga_number = 3
kaala = "प्रातः"
year_start = 4875
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "मुत्तुस्वामि-दीक्षित-जयन्ती",]
