id = "ahmedAbAd-blasts-2008"
jsonClass = "HinduCalendarEvent"

[timing]
month_type = "gregorian"
anga_type = "day"
month_number = 7
anga_number = 26
year_start = 2008
year_start_era = "gregorian"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """
On this day, 21 synchronised bomb blasts took place within a span of few minutes - around 56 died, and 200 injured. Diabolically, 2 blasts took place inside the premises of two hospitals, about 40 minutes after the initial series of blasts. One of the blasts in the hospitals occurred when injured victims of the initial series of blasts were being admitted there. Several bombs were defused in the succeding hours.

## Context
Carried out by Indian Mujahideen, an offshoot of Students Islamic Movement of India. In their email traced to Mumbai, they said: "In the name of Allah the Indian Mujahideen strike again! Do whatever you can, within 5 minutes from now, feel the terror of Death!”.

This came after May 13 Jaipur bombings (63 killed), 25 July bengaLUru bombings and was followed by Delhi bombings. 

## Aftermath
Maulana Abdul Halim, a SIMI mastermind, was arrested a few days later. Several others were later arrested. In 2022, 38 Muslim terrorists were awarded death penalty, while 11 were given life imprisonment.
"""

[names]
sa = [ "२००८ वर्षे कर्णावत्यां विस्फोटाः",]
