default_to_none = true
id = "aSTanAga-pUjA"
tags = [ "SpecialPuja",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 4
anga_type = "tithi"
anga_number = 17
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "अष्टनाग-पूजा", "ंअनस Pउज",]
