default_to_none = true
id = "tripura~bhairavI~jayantI"
tags = [ "Dashamahavidya",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 9
anga_type = "tithi"
anga_number = 15
kaala = "मध्यरात्रिः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Goddess Tripura Bhairavi is 5th of the Dasha Maha Vidyas."

[names]
sa = [ "त्रिपुर-भैरवी-जयन्ती",]
