default_to_none = true
id = "vEGkaTAcalE_padmAvatI-pariNayOtsavaH"
tags = [ "AndhraTempleFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = """The celestial wedding of Bhagavan Srinivasa and Devi Padmavati is a grand festival held annually in the month of Vaishakha. The beautifully adorned Parinayotsavam Mandapam, set amidst the Narayanagiri gardens, serves as the enchanting venue for this three-day event, celebrated under the moonlit sky. The festivities unfold on the auspicious days of Navami, Dashami, and Ekadashi in the month of Vaishakha, featuring Sri Malayappaswami, Shri Venkateshwara's festival deity. Each day, he makes a grand entrance on different Vahanas: the Gaja (elephant), Ashva (horse), and Garuda (eagle), while Devi-s Sridevi and Bhudevi grace the event on separate palanquins.

Following the wedding rituals at the Parinayotsava Mandapam, a traditional 'Koluvu' gathering takes place, filled with the recitation of Vedic hymns and devotional songs. The Bhagavan, accompanied by Sridevi and Bhudevi, then majestically returns to the temple.

Each day's festivities are marked by unique traditional rituals. On the first day, the arrival of Bhagavan Malayappa Swami on the celestial Gaja Vahanam, along with his consorts on their palanquins, is a sight to behold. The traditional wedding ceremony is conducted, where the Bhagavan is seated in the ornately decorated Parinaya Mandapam, with his consorts positioned opposite him.

The ceremony includes several traditional rituals such as Edurukolu (mutual reception), Pula Bantata (game of flower balls), and Vastra Dharanam (offering of new clothes). These customs are observed over all three days. The grand finale of the divine marriage is marked by a spectacular display of fireworks, adding to the ceremony's splendor. The event concludes with a procession where Bhagavan Malayappa Swami, along with Devi-s Sridevi and Bhudevi, return to the main temple."""

[names]
sa = [ "वेङ्कटाचले पद्मावती-परिणयोत्सवः",]
