default_to_none = true
id = "nEca_nAyan2mAr_(59)_gurupUjai"
tags = [ "NayanmarGurupujai",]
references_secondary = [ "63 Nayanmar Saints by Swami Sivananda, published by The Divine Life Society",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "sidereal_solar_month"
priority = "paraviddha"
month_number = 12
anga_type = "nakshatra"
anga_number = 4
kaala = "प्रातः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """Between the 6th and 9th centuries, in South India, there existed 63 ardent devotees of Bhagavan Shiva, collectively known as the Nayanmars. These devout individuals, hailing from various walks of life including potters, fishermen, farmers, merchants, priests, hunters, and washermen, created devotional songs still sung by followers around the globe. Among these Nayanmars, Appar, Sambandar, and Sundarar, known for their Thevaram hymns, along with Manikkavasagar, are distinguished as the Samayacharyas or the ‘The Four’ (`nAlvar`) revered teachers of the faith. They were instrumental in promoting the Shaiva Siddhanta philosophy and culture, effectively challenging the spread of Jainism and Buddhism. Their teachings centered around the concept that Shiva embodies love, and that embracing love for all beings and existence is essential in connecting with Shiva, the Supreme Being.

Nesa Nayanmar, hailing from Kampili, was a weaver by profession and a fervent devotee of Bhagavan Shiva. His devotion was characterized by three key virtues: his mind was constantly focused on the divine feet of Bhagavan Shiva, his lips ceaselessly chanted the sacred Panchakshara Mantra, and his hands were always engaged in serving the Bhagavan's devotees. These practices of devotion, japa, and service garnered him the grace of Bhagavan Shiva.

Nesa Nayanmar's life also exemplifies the profound impact of God's name. Like Sirapulli Nayanmar, he showed that constant repetition of a divine mantra can lead to a state of continuous remembrance of God, transcending daily activities and even extending into sleep."""

[names]
ta = [ "nEca nAyan2mAr (59) gurupUjai",]
