default_to_none = true
id = "kAJcI_44_jagadguru_zrI~pUrNabOdhEndra_sarasvatI_2_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
कार्णाटो हरिपण्डितः शिवसुतः श्रीपूर्णबोधाख्यया बिभ्राणोऽनुपदं जगद्गुरुपदं वर्षांश्च षड्विंशतिम्।
धाम्नि स्वे परमे जगाम निलयं वर्षे प्रमाथ्याह्वये कृष्णप्रौष्ठपदत्रयोदशतिथौ ब्राह्मे क्षणे ब्रह्मवित्॥८७॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-44.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 6
anga_type = "tithi"
anga_number = 28
kaala = "अपराह्णः"
year_start = 4141
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Son of Śiva of Karnataka called Haripaṇḍita subsequently known by the name Śrī Pūrṇabodha (after initiation) held the preceptorship of the Pīṭha (Jagatgurupada) for twenty-six years. This realised preceptor merged in his illustrious effulgence in the early hours on the trayodaśī of Kṛṣṇapakṣa in the month Bhādrapada of the year Pramāthī."

[names]
sa = [ "काञ्ची ४४ जगद्गुरु श्री-पूर्णबोधेन्द्र सरस्वती २ आराधना",]
