default_to_none = true
id = "tiruccendUr_murugan2_AvaNit_tiruvizhA_##4##m_nAL—yAn2ai_vAhanattil_murugan2-ambAL_bhavan2i"
tags = [ "TamilnaduTempleFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
anchor_festival_id = "tiruccendUr_AvaNit_tiruvizhA_nir2aivu"
offset = -8
jsonClass = "HinduCalendarEventTiming"

[description]
en = "The Tiruchendur Brahmotsavam of Avani each year is very special. The festival is conducted for twelve days. This marks the fourth day of the festival, when both Subrahmanya and Ambal are taken out in procession on an elephant `vAhanam`."

[names]
ta = [ "tiruccendUr murugan2 AvaNit tiruvizhA ##4##m nAL—yAn2ai vAhanattil murugan2-ambAL bhavan2i",]
