default_to_none = true
id = "cAturmAsyavrata-ArambhaH"
tags = [ "VratamStart", "SpecialPeriodStart", "CommonFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 4
anga_type = "tithi"
anga_number = 10
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Chaaturmasya begins; 4 months; Pradakshina to Pippala; Deeparadhana in temple; Saraswati Pooja; 1st month no vegetables; 2nd month no curds; 3rd month no milk; 4th month no dals;"

[names]
sa = [ "चातुर्मास्यव्रत-आरम्भः",]
