default_to_none = true
id = "zukla-caturthI-vratam"
tags = [ "MonthlyVratam", "ShuklaChaturthiVratam",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "puurvaviddha"
month_number = 0
anga_type = "tithi"
anga_number = 4
kaala = "मध्याह्नः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Shukla Chaturthi Vratam for Lord Ganesha."

[names]
sa = [ "शुक्ल-चतुर्थी-व्रतम्",]
