default_to_none = true
id = "zyAmaLAnavarAtra-samApanam"
tags = [ "Navaratri", "SpecialPeriodEnd",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 11
anga_type = "tithi"
anga_number = 9
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "श्यामळानवरात्र-समापनम्",]
