default_to_none = true
id = "nikSubhArka-saptamI"
tags = [ "SpecialVratam", "LessCommonFestivals",]
references_primary = [ "Bhavisyat Purana",]
references_secondary = [ "Chaturvarga Chintamani",]
shlokas = """
सूर्यभक्ता तु या नारी ध्रुवं सा पुरुषो भवेत्।
स्त्री चैवाप्युत्तमं नाथं यत् कृत्वा लभते शृणु॥
निक्षुभार्कव्रतं भानोः सदा प्रीतिविवर्धनम्।
अवियोगकरं वीर धर्मकामार्थसाधकम्॥
सप्तम्यामथ षष्ठ्यां वा सङ्क्रान्तौ भानवे दिने।
हविषा हविषा होमं सोपवासः समाचरेत्॥
निक्षुभार्कस्य चैवार्चां कृत्वा स्वर्णमयीं शुभाम्। 
राजतीं वाथ वाक्षीं वा स्नापयेच्च घृतादिभिः॥
"""
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "puurvaviddha"
month_number = 11
anga_type = "tithi"
anga_number = 22
kaala = "मध्याह्नः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "`nikSubhA` is the `patnI` of Surya Bhagavan. Worship Her along with `arka` (Surya) on `nikSubhArka-saptamI` day."

[names]
sa = [ "निक्षुभार्क-सप्तमी",]
