default_to_none = true
id = "appUdiyaDigaL_nAyan2mAr_(25)_gurupUjai"
tags = [ "NayanmarGurupujai",]
references_secondary = [ "63 Nayanmar Saints by Swami Sivananda, published by The Divine Life Society",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "sidereal_solar_month"
priority = "paraviddha"
month_number = 10
anga_type = "nakshatra"
anga_number = 24
kaala = "प्रातः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """
Between the 6th and 9th centuries, in South India, there existed 63 ardent devotees of Bhagavan Shiva, collectively known as the Nayanmars. These devout individuals, hailing from various walks of life including potters, fishermen, farmers, merchants, priests, hunters, and washermen, created devotional songs still sung by followers around the globe. Among these Nayanmars, Appar, Sambandar, and Sundarar, known for their Thevaram hymns, along with Manikkavasagar, are distinguished as the Samayacharyas or the ‘The Four’ (`nAlvar`) revered teachers of the faith. They were instrumental in promoting the Shaiva Siddhanta philosophy and culture, effectively challenging the spread of Jainism and Buddhism. Their teachings centered around the concept that Shiva embodies love, and that embracing love for all beings and existence is essential in connecting with Shiva, the Supreme Being.

Appudi Nayanmar, the 25th of the Nayanmars, was a devout Shiva worshipper from a Brahmana family in Thingalur, Chola kingdom. He lived the life of an ideal householder and had heard of the glories of Tirunavukkarasar (Appar). Although never meeting him, Appudi worshipped Appar as his Guru, believing Bhagavan Shiva manifested as the Guru to guide seekers. He named everything after Appar – children, water sheds for pilgrims, and even household items --- to constantly remember and experience his Guru's grace.

Appar himself, unaware of Appudi's devotion, stumbled upon one of the water-sheds named after him during his travels. Curious, he visited Appudi, asking him as to why he named the shed after some person rather than himself. Not recognizing Appar, Appudiyadigal indignant at this question, passionately defended the name's significance, recounting the the spiritual triumphs and miracles of Thirunavukkarasu Swamigal! Appar, a true and humble bhakta, then revealed his identity, merely recounting himself as a humble soul who sought Shiva's feet owing to a colic disease, and returned to Shavism, having been cured by the Bhagavan. Overjoyed at this revelation, Appudi invited Appar to have a meal. Tragedy struck when Appudi's son, sent to fetch a banana leaf for Appar's meal, died from a snake bite. Determined not to disrupt the service to Appar, Appudi concealed the child's corpse.

Upon learning of the boy's demise, Appar, deeply affected, instructed the body be placed in front of the temple. He then sang a hymn, miraculously reviving the boy. The parents, in their unshakeable devotion, regretted only the delay this incident caused in Appar's meal. Appar blessed the family, stayed with them for a while, and Appudi's profound devotion to his Guru earned him divine grace.
"""

[names]
ta = [ "appUdiyaDigaL nAyan2mAr (25) gurupUjai",]
