default_to_none = true
id = "vaizAkha-mAsa-ArambhaH"
tags = [ "SpecialDays", "SpecialPeriodStart",]
shlokas = """
वैशाखे मासियोदद्यात्तक्रंतापविनाशनम्॥४१॥
विद्यावान्धनवान्भूमौ जायते नात्र संशयः॥
न तक्रसदृशं दानं घर्मकालेषु विद्यते॥४२॥
तस्मात्तक्रं प्रदातव्यमध्वश्रांतद्विजातये॥
जंबीरसुरसोपेतं लसल्लवणमिश्रितम्॥४३॥
यस्तक्रमरुचिघ्नंतुदत्त्वामोक्षमवाप्नुयात्॥
यो दद्याद्दधिखंडंतुवैशाखेघर्मशांतये॥४४॥
तस्य पुण्यफलं वक्तुं नाहं शक्नोमि भूमिप॥
यो दद्यात्तंडुलान्दिव्यान्मधुसूदनवल्लभे॥४५॥
स लभेत्पूर्णमायुष्यं सर्वयज्ञफलं लभेत्॥
यो घृतं तेजसो रूपं गव्यं दद्याद्द्विजातये॥
सोऽश्वमेधफलं प्राप्य मोदते विष्णुमंदिरे॥४६॥
उर्वारुगुडसंमिश्रं वैशाखे मेषगे रवौ॥
सर्वपापविनिर्मुक्तः श्वेतद्वीपे वसेद्ध्रुवम्॥४७॥
यश्चेक्षुदंडं सायाह्ने दिवा तापोपशान्तये॥
ब्राह्मणायचयोदद्यात्तस्य पुण्यमनंतकम्॥४८॥
वैशाखे पानकं दत्त्वा सायाह्ने श्रमशान्तये॥
सर्वपापविनिर्मुक्तो विष्णोः सायुज्यमाप्नुयात्॥४९॥
सफलं पानकं मेषमासे सायं द्विजातये॥
दद्यात्तेन पितॄणांतुसुधापानंनसंशयः।५०॥
वैशाखे पानकं चूतसुपक्वफलसंयुतम्॥
तस्य सर्वाणि पापानि विनाशं यांति निश्चितम्॥५१॥
—स्कन्दपुराणे द्वितीये वैष्णवखण्डे वैशाखमाहात्म्ये तृतीये अध्याये
"""
references_primary = [ "Skanda Puranam",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 2
anga_type = "tithi"
anga_number = 1
jsonClass = "HinduCalendarEventTiming"

[description]
en = "`vaizAkha-mAsaH` begins today --- special for various `dAnam`'s such as buttermilk, `pAnakam` etc. Brings unlimited `puNyam`!"

[names]
sa = [ "वैशाख-मास-आरम्भः",]
