default_to_none = true
id = "kAJcI_3_jagadguru_zrI~sarvajJAtmEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
ताम्रारोधसि वर्धनात् समुदितः सन्न्यासितः सप्तमात्
प्रागेवात्मविवादहृष्टमनसा श्रीशङ्करेणैव यः।
तत्पीठे ससुरेश्वरं समनयद् वर्षांश्च यः सप्ततिं
चत्वारिंशतमास्त सद्वयमसावब्दान् स्वयं तन्मठे॥७॥
आचार्यप्रियपद्मपादचरणाम्भोजद्वयीसेवनाद्
ऊढद्वारवतीमठाय मुनये ब्रह्मस्वरूपात्मने।
श्रद्धाराद्धपदाय तत्त्वमतुलं चिन्मुद्रया निर्दिशन्-
नेवैक्यं समगान्निजेन महसा सर्वज्ञसंज्ञो मुनिः॥८॥
कल्यब्दैः स हयाग्निलोकनयनैर् (२७३७) वर्षे नले माधवे
लिल्ये कृष्णचतुर्दशीमनु महस्याम्नायशैलान्तिके।
ग्रन्थैर्यत्कलितैर्न्यदर्शि विशदं सङ्क्षेपशारीरक-
प्रख्यैरद्वयसूत्रभाष्यगहनच्छन्नः पदार्थोच्चयः॥९॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-03.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 2
anga_type = "tithi"
anga_number = 29
kaala = "अपराह्णः"
year_start = 2738
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "This Sarvajñātman, who was born to Vardhana got initiated into asceticism even before the age of seven by Śri Śaṅkara himself on being delighted to have had debate with him on the banks of river Tāmraparṇi; he spent seventy years along with Sureśvara in that Pīṭha and then lived in that Maṭha for forty two years. The sage known as Sarvajña attained union with his own Self by doing service at the lotus feet of Śri Padmapāda, who was dear to the Ācārya (Śri Śaṅkara) and imparting the unparallel doctrine through Cinmudrā to the saint by name Brahmasvarūpa who served with love and faith at the feet of the master who was holding the pontiff-dom of the Dvāravatī maṭha. The sage Sarvajñātman whose works such as Saṁkṣepaśārīraka showed clearly/elaborately the collective meaning of the words hidden in the great commentatorial works on Advaita merged in the Supreme on the fourteenth day of the dark fortnight in the month of Vaiśākha in the Nala year of the Kali era 2737 at Kāñci Śri Śaṅkara Maṭha."

[names]
sa = [ "काञ्ची ३ जगद्गुरु श्री-सर्वज्ञात्मेन्द्र सरस्वती आराधना",]
