default_to_none = true
id = "yamatarpaNam"
tags = [ "CommonFestivals",]
jsonClass = "HinduCalendarEvent"
shlokas = """
माघकृष्णचतुर्दश्यां यमतर्पणमीरितम्॥
अनर्काभ्युदिते काले स्नात्वा सन्तर्पयेद्यमम्।
द्विसप्तनामभिः प्रोक्तैः सर्वपापविमुक्तये॥
तिलदर्भाम्बुभिः कार्यं तर्पणं द्विजभोजनम्।
"""
references_primary = [ "Naradiya Puranam, Adhyaaya 123",]

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "paraviddha"
month_number = 11
anga_type = "tithi"
anga_number = 29
jsonClass = "HinduCalendarEventTiming"

[description]
en = """
Perform `tarpaNam` to Yama Dharmaraja.
एकैकेन तिलैर्मिश्रान् दद्यात् त्रींस्त्रीन् जलाञ्जलीन्।
संवत्सरकृतं पापं तत्क्षणादेव नश्यति॥
कृष्णपक्षे चतुर्दश्यां यां काञ्चित् सरितं प्रति।
यमुनायां विशेषेण नियतस्तर्पयेद् यमम्॥
यत्र क्वचन नद्यां हि स्नात्वा कृष्णचतुर्दशीम्।
सन्तर्प्य धर्मराजं तु मुच्यते सर्वकिल्बिषैः॥
दक्षिणभिमुखो भूत्वा तिलैः सव्यं समाहितः।
देवतीर्थेन देवत्वात् तिलैः प्रेताधिपो यतः॥

१. यमं तर्पयामि। (त्रिः)
२. धर्मराजं तर्पयामि।
३. मृत्युं तर्पयामि।
४. अन्तकं तर्पयामि।
५. वैवस्वतं तर्पयामि।
६. कालं तर्पयामि।
७. सर्वभूतक्षयं तर्पयामि।
८. औदुम्बरं तर्पयामि।
९. दध्नं तर्पयामि।
१०. नीलं तर्पयामि।
११. परमेष्ठिनं तर्पयामि।
१२. वृकोदरं तर्पयामि।
१३. चित्रं तर्पयामि।
१४. चित्रगुप्तं तर्पयामि।


"""

[names]
sa = [ "माघ-यम-तर्पणम्",]
