default_to_none = true
id = "candra-grahaNam~(kEtugrasta)"
tags = [ "RareDays", "Eclipses",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Lunar eclipse, where the Moon is at the ‘Ketu node’."

[names]
sa = [ "चन्द्र-ग्रहणम्~(केतुग्रस्त)",]
