default_to_none = true
id = "★cUDAmaNi-candra-grahaNam~(rAhugrasta)"
tags = [ "RareDays", "Eclipses",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "★चूडामणि-चन्द्र-ग्रहणम्-(राहुग्रस्त)",]
