default_to_none = true
id = "kAJcI_6_jagadguru_zrI~zuddhAnandEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
वेदारण्यजवैद्यभर्वुतनयः श्रीविश्वनाथाभिधो
ज्ञानानन्दमुनेरवाप्य नियमं काञ्चीपदे स्थापितः।
शुद्धानन्दमुनीश्वरः स शरदः सैकामशीतिं धुराम्
आचार्यस्य वहन्नवाप च नलज्येष्ठाच्छषष्ठ्यां लयम्॥१३॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-06.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 3
anga_type = "tithi"
anga_number = 6
kaala = "अपराह्णः"
year_start = 2978
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Śrī Viśvanātha, son of Vaidyabharva of Vedāraṇya, received initiation from sage Jñānānanda, became Śuddhānandamunīśvara was established in Kāñcī; having carried on the responsibilities of the preceptor for eighty-one years, he secured union on the sixth day of the bright fortnight in the year Nala."

[names]
sa = [ "काञ्ची ६ जगद्गुरु श्री-शुद्धानन्देन्द्र सरस्वती आराधना",]
