default_to_none = true
id = "kAraikkAl_ammaiyAr_(24)_gurupUjai"
tags = [ "NayanmarGurupujai",]
references_secondary = [ "63 Nayanmar Saints by Swami Sivananda, published by The Divine Life Society",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "sidereal_solar_month"
priority = "paraviddha"
month_number = 12
anga_type = "nakshatra"
anga_number = 15
kaala = "प्रातः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """Between the 6th and 9th centuries, in South India, there existed 63 ardent devotees of Bhagavan Shiva, collectively known as the Nayanmars. These devout individuals, hailing from various walks of life including potters, fishermen, farmers, merchants, priests, hunters, and washermen, created devotional songs still sung by followers around the globe. Among these Nayanmars, Appar, Sambandar, and Sundarar, known for their Thevaram hymns, along with Manikkavasagar, are distinguished as the Samayacharyas or the ‘The Four’ (`nAlvar`) revered teachers of the faith. They were instrumental in promoting the Shaiva Siddhanta philosophy and culture, effectively challenging the spread of Jainism and Buddhism. Their teachings centered around the concept that Shiva embodies love, and that embracing love for all beings and existence is essential in connecting with Shiva, the Supreme Being.

Karaikal Ammaiyar, originally named Punithavathy, was born into a prosperous Vaisya family. Her parents, Danadathan and his wife, were devout and virtuous. Punithavathy, a fervent devotee of Bhagavan Shiva from childhood, married Paramadattan, a wealthy merchant. They led an exemplary life until an incident tested her devotion.

One day, after receiving two mangoes from Paramadattan, Punithavathy encountered a famished Shiva Yogi and offered him one of the mangoes. When Paramadattan requested the second mango at mealtime, Punithavathy prayed for divine assistance. Miraculously, another mango appeared, which she served to her husband. Astounded by its divine taste, Paramadattan questioned its origin. Upon learning the truth, he found it inconceivable to live as her husband, considering her divine qualities.

Paramadattan left for a foreign land under the guise of business, settled in the Pandyan kingdom, remarried, and named his daughter after Punithavathy, out of his deep regard for her. When Punithavathy's relatives learned of his whereabouts, they took her to meet him. Paramadattan, receiving her with his new family, fell at her feet, worshipping her as a goddess.

Realising Paramadattan's perception of her, Punithavathy prayed to Bhagavan Shiva for a demoniacal form to renounce her physical charm. Her prayer was answered, transforming her into a skeletal form. She then journeyed to Kailasa, the abode of Bhagavan Shiva and Parvati. Overflowing with devotion, and considering the sacredness of Kailasa, she considered it a sin to set her foot on the holy mountain, and travelled the final stretch on her head! As Parvati Devi was astounded by her strange form and unique devotion, Bhagavan Shiva narrated the greatness of Ammaiyar to Her.

Acknowledging her exceptional devotion, Bhagavan Shiva welcomed her warmly and offered her a boon. Punithavathy requested perpetual, undiluted devotion to Bhagavan Shiva, freedom from rebirth, and the privilege to sing his praises during his cosmic dance. Bhagavan Shiva granted her wishes and directed her to Thiruvalangadu, where she spent the rest of her life singing hymns in praise of the Bhagavan."""

[names]
ta = [ "kAraikkAl ammaiyAr (24) gurupUjai",]
