default_to_none = true
id = "tiruccendUr_murugan2_teppam"
tags = [ "TamilnaduTempleFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
anchor_festival_id = "tiruccendUr_mAcit_tiruvizhA_nir2aivu"
offset = -1
jsonClass = "HinduCalendarEventTiming"

[description]
en = "The Tiruchendur Brahmotsavam of Masi each year is very special, wherein all the three temple chariots are dragged and the festival is conducted for twelve days, concluding with a Teppam or Float Festival. This marks the eleventh and penultimate day of the festival. The main feature of the day is the 'float' festival or `ta:teppam`."

[names]
ta = [ "tiruccendUr murugan2 teppam",]
