default_to_none = true
id = "kOkila-vratam"
tags = [ "SpecialVratam",]
jsonClass = "HinduCalendarEvent"
shlokas = """
कोकिलाव्रतमप्यत्र प्रोक्तं तद्विधिरुच्यते।
पूर्णिमायां समारभ्य व्रतं स्नायाद् बहिर्जले॥१८॥
पूर्णतं श्रावणे मासि गौरीरूपां च कोकिलाम्।
स्वर्णपक्षां रत्ननेत्रां प्रवालमुखपङ्कजाम्॥१९॥
कस्तूरीवर्णसंयुक्तामुत्पन्नां नन्दने वने।
चूतचम्पकवृक्षस्थां कलगीतनिनादिनीम्॥२०॥
चिन्तयेत् पार्वतीं देवीं कोकिलारूपधारिणीम्।
गन्धाद्यैः प्रत्यहं प्रार्च्चेल्लिखितां वर्णकैः पटे॥२१॥
ततो व्रतान्ते हैमीं वा तिलपिष्टमयीं द्विज।
दद्याद्विप्राय मंत्रेण भक्त्या सस्वर्णदक्षिणाम्॥२२॥
देवीं चैत्ररथोत्पन्ने कोकिले हरवल्लभे।
सम्पूज्य दत्ता विप्राय सर्वसौख्यकरी भव॥२३॥
द्विजं सुवासिनीस्त्रिंशदेकां वा भोजयेत्ततः।
वस्त्रादिदक्षिणां शक्त्या दत्त्वा नत्वा विसर्जयेत्॥२४॥
एवं या कुरुते नारी कोकिलाव्रतमुत्तमम्।
सा लभेत्सुखसौभाग्यं सप्तजन्मसु नारद॥२५॥
"""
references_primary = [ "Naradiya Puranam, Adhyaya 124",]

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "puurvaviddha"
month_number = 4
anga_type = "tithi"
anga_number = 15
kaala = "सूर्यास्तमयः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "The Kokila vratam is performed for a month, beginning this day, until the Full Moon day of Shravana Masa. Performed by women, Devi Parvati is worshipped in the form of a Kokila, i.e. cuckoo, with golden wings, jewelled eyes, lotus-like face, etc. A woman performing this vratam attains happiness and saubhagyam for seven births."

[names]
sa = [ "कोकिल-व्रतम्",]
