default_to_none = true
id = "bhISmASTamI"
tags = [ "SpecialPuja", "CommonFestivals", "CommonFestivals",]
references_secondary = [ "Smriti Kaustubha p.480", "Laugakshi Smriti", "Padma Puranam"]
shlokas = """
माघमासि सिताष्टम्यां सलिले भीष्मतर्पणम्।
श्राद्धं च ये नराः कुर्युस्ते स्युः सन्ततिभागिनः॥
अष्टमीदिवसे चैव भीष्मतर्पणमाचरेत्।
दद्यात् प्रदद्याद् भीष्माय तर्पणं प्रतिवत्सरम्॥
तेन तर्पणमात्रेण सहस्रद्विजभोजने।
यत्फलं कथितं सद्भिस्तदवाप्नोत्यसंशयः॥
शुक्लाष्टम्यां तु माघस्य दद्याद्भीष्माय यो जलम्।
संवत्सरकृतं पापं तत्क्षणादेव नश्यति॥
ब्राह्मणाद्याश्च ये वर्णाः दद्युर्भीष्माय नो जलम्।
संवत्सरकृतं तेषां पुण्यं नश्यति सत्तम॥

उदकदानमन्त्रः---
वैयाघ्रपादगोत्राय साङ्कृत्यप्रवराय च।
गङ्गापुत्राय भीष्माय प्रदास्येऽहं तिलोदकम्।
अपुत्राय ददाम्येतत् सलिलं भीष्मवर्मणे॥
भीष्मं तर्पयामि।

अर्घ्यप्रदानम्---
\twolineshloka*
सत्यव्रताय शुचये गाङ्गेयाय महात्मने।
अर्घ्यं ददामि भीष्माय सोमवंशोद्भवा।य च॥
भीष्माय नमः इदमर्घ्यम्। भीष्माय नमः इदमर्घ्यम्। भीष्माय नमः इदमर्घ्यम्।

वसूनामवताराय शन्तनोरात्मजाय च।
अर्घ्यं ददामि भीष्माय आजन्मब्रह्मचारिणे॥
भीष्माय नमः इदमर्घ्यम्। भीष्माय नमः इदमर्घ्यम्। भीष्माय नमः इदमर्घ्यम्।

प्रार्थना---
भीष्मः शान्तनवो वीरः सत्यवादी जितेन्द्रियः।
आभिरद्भिरवाप्नोतु पुत्रपौत्रोचिताः क्रियाः॥
"""
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "puurvaviddha"
month_number = 11
anga_type = "tithi"
anga_number = 8
kaala = "मध्याह्नः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Bhishma obtained mukti on this day; offer tarpana to Bhishma (even those with parents). Brings health, long life and harmony in family."

[names]
sa = [ "भीष्माष्टमी",]
