id = "mAdhava-rAvAntimAdeshaH"
jsonClass = "HinduCalendarEvent"

[timing]
month_type = "gregorian"
anga_type = "day"
month_number = 9
anga_number = 30
year_start = 1772
year_start_era = "gregorian"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """
On this day, shortly before his untimely death, one of the finest peshva-s, mAdhava rAv issued his final will with the following points.

- 1. All my debts should be paid even by using, if necessary, my private purse  in the possession of Guruji (Mahadaji Ballal) :
- 2. The system of farming the revenues is found oppressive to the ryots: it should be modified after a careful enquiry.
- 3. The two holy places Prayag and Benares should be released from Muslim control. This was the ardent desire of my sires and now is the time to carry it out.
- 4. My mother's desire to perform the pilgrimage of Benares should be fulfilled as soon as convenient.
- 5. The obsequies of Bhau Saheb should be performed next February, whether aunt Parwatibai becomes sati or not.
- 6. The annuities assigned to the worthy Brahmans of Benares should be regularly paid and continued in heredity.
- 7. Dinners in connection with my funeral rites should be served to two lacs of Brahmans each with half an anna for dakshana.
- 8. Dadasaheb should have five lacs of jagir assigned for his maintenance in order to keep him contented.
- 9. The charities of the Shravan month should be continued as long as the administration brings in at least 5 lacs of revenue yearly.

The responsible officers swore in the presence of Ganapati that they would execute all these wishes.
"""

[names]
sa = [ "माधव-रावान्तिमादेशः",]
