default_to_none = true
id = "kAraDaiyAn2_nOn2bu"
tags = [ "CommonFestivalsTamilnadu",]
shlokas = """
दोरं गृह्णामि सुभगे सहारिद्रं धराम्यहम्।
भर्तुरायुष्य-सिद्ध्यर्थं सुप्रीता भव सर्वदा॥
"""
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = """
Tradition in South India (especially Tamil Nadu), where all women perform this `nOnbu` praying for their husband's long life. This vratam was peformed by Savitri in the forest, following which she redeemed his life from Lord Yama.

Generally in orthodox Tamil families, the married women fast till the vrata time; and after tying the holy thread, they will eat nonbu adai and fast the rest of the day and eat milk and any fruit(preferably banana) in the night. The thread has to be tied till the next year's festival. Till then, during bath, one applies turmeric powder to the rope.
"""
sa = """
पत्युर् दीर्घायुष्यं कामयन्त्यः सनैवेद्यं सुपूजितं व्रत-सूत्रं किञ्चन +उपोष्य पत्न्यः स्वकण्ठेषु बन्धयन्ति।
"""

[names]
sa = [ "सावित्री-व्रतम्",]
ta = [ "kAraDaiyAn2 nOn2bu", "caraDu-paNDigai",]
