default_to_none = true
id = "kAJcI_8_jagadguru_zrI~kaivalyAnandayOgEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
श्रीशैलीयशिवय्यसूनुरदधात् तस्याज्ञया तत् पदं मङ्गण्णार्य इति श्रुतः परमहो कैवल्ययोगिप्रथः।
आरूढः शिवराजयोगपदवीं तिष्ठंस्त्र्यशीतिं समाः सिद्धोऽभूत् स च सर्वधारिमकरक्रान्तौ च सायाहनि॥१६॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-08.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 10
anga_type = "tithi"
anga_number = 14
kaala = "अपराह्णः"
year_start = 3130
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Son of Śivayya of Śrīśaila, known as Manganna, held that position by his directions and became well-known as Kaivalya Yogi, ascended to the status of a Rājayogi and remaining (in that position) for eighty three years accomplished realisation in the evening of Makarasaṅkrānti of the year Sarvadhāri."

[names]
sa = [ "काञ्ची ८ जगद्गुरु श्री-कैवल्यानन्दयोगेन्द्र सरस्वती आराधना",]
