default_to_none = true
id = "kAJcI_68_jagadguru_zrI~candrazEkharEndra_sarasvatI_7_ArAdhanA"
tags = [ "KanchiAradhanaDays", "CommonFestivals",]
shlokas = """
महास्वामीति विख्यातस्त्वष्टषष्टो जगद्गुरुः।
हारीतेऽन्वय उद्भूत उत्कृष्टे नाम धामनि॥२५॥
पञ्चोने वर्षसाहस्रपञ्चके विगते कलौ।
जयवर्षे वृषे मासि मैत्रर्क्षे कृष्णपक्षके॥२६॥
प्रतिपत्तिथिमध्याह्ने स्वामिनाथेति कीर्तितः।
महालक्ष्मीसुब्रह्मण्यदम्पत्योस्तपसः फलम्॥२७॥
रुजाऽपहृतदेहत्वे पूर्वयोर्गुरुनाथयोः।
तदाज्ञया स सन्न्यस्तो वयस्यूनत्रयोदशे॥२८॥
चन्द्रशेखरेति पुण्यनाम बिभ्रत् स आश्रमी।
सर्वज्ञमूर्तिस्त्रिर्यात्रां भारतस्याचरत् पदा॥२९॥
प्रत्यक्षं दैवतं भूत्वा धर्मे चाकृष्य मार्दवात्।
लोकान् समनुजग्राह वर्षाणां शतकं शुभम्॥३०॥
काञ्च्यां विदेहकैवल्यं प्रापद्यत मुनीश्वरः।
श्रीमुखे मार्गकृष्णे स द्वादश्याम् अपराह्णके॥३१॥
—पुण्यश्लोकमञ्जरी
"""
references_primary = [ "Punya Shloka Manjari",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 9
anga_type = "tithi"
anga_number = 27
kaala = "अपराह्णः"
year_start = 5095
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = ""

[names]
sa = [ "काञ्ची ६८ जगद्गुरु श्री-चन्द्रशेखरेन्द्र सरस्वती ७ आराधना",]
