default_to_none = true
id = "zrI~gOvinda_bhagavatpAda_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 8
anga_type = "tithi"
anga_number = 15
kaala = "अपराह्णः"
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "श्री-गोविन्द भगवत्पाद आराधना",]
