default_to_none = true
id = "haya-pUjA"
tags = [ "LessCommonFestivals",]
shlokas = """
उच्चैःश्रवाः पूजनीयः पञ्चम्यां चैत्रशुक्लके।
तत्रैव पूज्या गन्धर्वास्तुरगाणां तु बान्धवाः।
पत्रवानर्कपर्णश्च प्रत्युक्तश्च महायशाः॥
भीमश्चित्ररथश्चैव विख्यातः सर्वविद्वशी।
तथा शालिशिराः श्रीमान्प्रद्युम्नश्च महायशाः॥
नारदश्च कलिङ्गश्च गन्धर्वश्च हहाहुहूः।
सुबाहुस्तुम्बुरुश्चैव तथा चित्ररथः प्रभुः॥
चित्राङ्गदश्च विख्यातश्चित्रसेनश्च वीर्यवान्।
सिद्धपूर्वश्च बदरीपर्णाशश्च महायशाः॥
ब्रह्मचारी रतिगुणः सुपर्णोऽतिबलस्तथा।
विश्वावसुः सुरेन्द्रश्च गन्धर्वोऽतिपराक्रमः॥
इत्येते पूजनीयास्तु गन्धैरुच्चावचैस्तथा। 
मोदकैर्लापिकाभिश्च परमानेन चाक्षतैः॥
दध्ना गुडेन पयसा शालिपिष्टेन भूरिशः।
धूपैर्माल्यैस्तथा दीपैर्द्विजानां स्वस्तिवाचनैः॥
एवं हि पूजिताः सम्यक् तुरगाणां तु बान्धवाः।
बलमायुः प्रयच्छन्ति सङ्ग्रामेष्वपराजयम्॥
आरोग्यपरमां पुष्टिं तथैव च विधेयताम्। 
नरो वाऽप्यथवा नारी व्रतमेतत्समाचरेत्॥
चैत्रस्य शुक्लपञ्चम्यां शुचिः स्नाता उपोषिता।
प्रभाते पारणं कृत्वा देवविप्रान्प्रपूज्य च।
लभते साऽथवा सोऽपि स्वमनोरथजं फलम्॥
---मदनरत्ने पाद्मे पातालखण्डे (स्मृति-कौस्तुभे)
"""
references_primary = [ "Smriti Kaustubham p.92--93",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 1
anga_type = "tithi"
anga_number = 5
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Celebrating the birth of `uccaizravA` horse, offer puja to horses or even Lord Hayagriva."

[names]
sa = [ "हय-पूजा",]
