default_to_none = true
id = "zyAmaLAnavarAtra-ArambhaH"
tags = [ "Navaratri", "SpecialPeriodStart",]
references_secondary = [ "Vaidikasri Feb 2016",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 11
anga_type = "tithi"
anga_number = 1
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Shyamala Devi specially blesses musicians; honour musicians in this period."

[names]
sa = [ "श्यामळानवरात्र-आरम्भः",]
