default_to_none = true
id = "jayantI~mahAdvAdazI"
tags = [ "RareDays", "Combinations",]
jsonClass = "HinduCalendarEvent"
references_primary = [ "`padma-purANam`",]
shlokas = """
जया च विजया चैव जयन्ती पापनाशिनी।
सर्वपापहराश्चैताः कर्तव्याः फलकाङ्क्षिभिः॥४॥
यदा च शुक्लद्वादश्यां प्राजापत्यं हि जायते॥८॥
जयन्ती नाम सा प्रोक्ता सर्वपापहरा तिथिः।
सप्तजन्मकृतं पापं स्वल्पं वा यदि वा बहु॥९॥
प्रक्षालयति गोविन्दस्तस्यामभ्यर्चितो ध्रुवम्।
---श्रीपाद्मे महापुराण उत्तरखण्ड उमापतिनारदसंवादे उत्पन्नैकादशीकृतमुरवधो नाम चत्वारिंशोऽध्यायः॥४०॥
"""

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"


[description]
en = "Shukla Dvadashi tithi, combined with Rohini nakshatra. Jayā, Vijayā, Jayantī, and Pāpanāśinī—all these days have the power to destroy sins and should be observed by those seeking specific benefits. When Dvādaśī in the bright half coincides with Rohiṇī, it is called Jayantī. This day also removes sins. Worshipping Viṣṇu on this day undoubtedly cleanses one of all sins, whether small or great, committed during the past seven lifetimes."

[names]
sa = [ "जयन्ती-महाद्वादशी",]
