default_to_none = true
id = "pApanAzinI~mahAdvAdazI"
tags = [ "RareDays", "Combinations",]
jsonClass = "HinduCalendarEvent"
references_primary = [ "`padma-purANam`",]
shlokas = """
जया च विजया चैव जयन्ती पापनाशिनी।
सर्वपापहराश्चैताः कर्तव्याः फलकाङ्क्षिभिः॥४॥
यदा वै शुक्लद्वादश्यां पुष्यं भवति कर्हिचित्॥१०॥
तदा तु सा महापुण्या भविता पापनाशिनी।
यो ददाति तिलप्रस्थं नित्यं संवत्सरं प्रति॥११॥
उपवासं च यस्तस्यां करोत्येतत्समं स्मृतम्।
तस्यां जगत्पतिर्देवस्तुष्टः सर्वेश्वरो हरिः॥१२॥
प्रत्यक्षतां प्रयात्येव तत्रानन्तफलं स्मृतम्।
सगरेण ककुत्स्थेन नहुषेण च साधितः॥१३॥
तस्यामाराधितः कृष्णो दत्तवानखिलं भुवि।
वाचिकान्मानसाद्वापि कायजाच्च विशेषतः॥१४॥
सप्तजन्मकृतात्पापान्मुच्यते नात्र संशयः।
तामेकां समुपोष्याथ पुण्यनक्षत्रसंयुताम्॥१५॥
एकादशीसहस्रस्य फलं प्राप्नोति मानवः।
स्नानं दानं जपो होमः स्वाध्यायो देवतार्चनम्॥१६॥
यत्तस्यां क्रियते किञ्चित्तदक्षयफलं स्मृतम्।
तस्मादेषा प्रकर्तव्या यत्नेन फलकाङ्क्षिभिः॥१७॥
---श्रीपाद्मे महापुराण उत्तरखण्ड उमापतिनारदसंवादे उत्पन्नैकादशीकृतमुरवधो नाम चत्वारिंशोऽध्यायः॥४०॥
"""

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Shukla Dvadashi tithi, combined with Pushya nakshatra. Jayā, Vijayā, Jayantī, and Pāpanāśinī—all these days have the power to destroy sins and should be observed by those seeking specific benefits. When Dvādaśī in the bright half coincides with Puṣya, it becomes the highly meritorious Pāpanāśinī. The religious merit of giving a prastha of sesame seeds to a brāhmaṇa every day for a year is said to be equal to the merit of fasting on Pāpanāśinī. Bhagavan Viṣṇu, the lord of all and the ruler of the world, is pleased and appears in person, bestowing endless rewards on those who fast on this day. Viṣṇu, worshipped on this day by Sagara, Kakutstha, and Nahuṣa, granted them everything on earth. There is no doubt that fasting on this day absolves one from sins of speech, mind, and body committed during the past seven lifetimes. A person who fasts on Pāpanāśinī, when it coincides with the star Puṣya, gains the merit of fasting on a thousand Ekādaśīs. Acts such as bathing, giving gifts, reciting hymns, performing sacrifices, self-study, and deity worship on this day are said to yield inexhaustible rewards. Therefore, those who seek such benefits should carefully observe a fast on this day."

[names]
sa = [ "पापनाशिनी-महाद्वादशी",]
