default_to_none = true
id = "unmIlanI~mahAdvAdazI"
tags = [ "RareDays", "Combinations", "SpecialVratam",]
jsonClass = "HinduCalendarEvent"
shlokas = """
एकादशी अहोरात्रं प्रभाते घटिका भवेत्॥३२॥
उन्मीलनी तु सा ज्ञेया विशेषेण हरिप्रिया।
त्रैलोक्ये यानि तीर्थानि पुण्यान्यायतनानि च॥३३॥
कोट्यंशे नैव तुल्यानि मखा वेदास्तपांसि च।
उन्मीलनी समं किञ्चिन्न भूतं न भविष्यति॥३४॥
...
उन्मीलनीमनुप्राप्य यैः कृतं केशवार्चनम्॥३९॥
पापचक्रसमूहस्य राशयः पतिताः क्षणात्।
यस्मिन्मासे महीपाल तिथिरुन्मीलनी भवेत्॥४०॥
तन्मासनाम्ना गोविंदः पूजनीयः प्रयत्नतः।
---श्रीपाद्मे महापुराण उत्तरखण्ड उमापतिनारदसंवादे उन्मीलनीव्रतं नाम सप्तत्रिंशोऽध्यायः॥३७॥
"""

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "When the Ekadashi tithi is incident at sunrise on two consecutive days, the second day, where there is association with Dvadashi tithi, is known as `unmIlanI` is one of the eight `mahAdvAdazI`s. The day on which Ekādaśī continues through day and night and extends for a ghaṭikā into the next day is known as Unmīlanī, and it is especially beloved by Bhagavan Viṣṇu. The combined sanctity of all holy and sacred places in the three worlds pales in comparison to even a fraction of the merit of Unmīlanī, as do sacrifices and austerities. There has never been, nor will there ever be, anything like Unmīlanī! The moment one worships Bhagavan Viṣṇu on the Unmīlanī day, all their accumulated (heaps of) sins fall (away) instantly. O king, Bhagavan Viṣṇu should be worshipped with great effort, using the name of the month in which the Unmīlanī day occurs."

[names]
sa = [ "उन्मीलनी-महाद्वादशी",]
