default_to_none = true
id = "vijayA~zravaNa-mahAdvAdazI"
tags = [ "RareDays", "Combinations", "SpecialVratam",]
references_primary = [ "`padma-purANam`",]
jsonClass = "HinduCalendarEvent"
shlokas = """
जया च विजया चैव जयन्ती पापनाशिनी।
सर्वपापहराश्चैताः कर्तव्याः फलकाङ्क्षिभिः॥४॥
यदा च शुक्लद्वादश्यां नक्षत्रं श्रवणं भवेत्॥६॥
विजया सा समाख्याता तिथीनामुत्तमा तिथिः।
सहस्रगुणितं दानं यस्यां वै विप्रभोजनम्॥७॥
होमस्तथोपवासश्च सहस्राधिकफलप्रदः।
---श्रीपाद्मे महापुराण उत्तरखण्ड उमापतिनारदसंवादे उत्पन्नैकादशीकृतमुरवधो नाम चत्वारिंशोऽध्यायः॥४०॥
श्रवणद्वादशीव्रते नदीसङ्गमे स्नात्वा कलशे स्वर्णमयं जनार्दननामानं विष्णुं
सम्पूज्य वस्त्रयज्ञोपवीतोपानहच्छत्रादि समर्प्य उपोष्य पारणादिने दध्योदनयुतं 
वस्त्रवेष्टितं जलपूर्णघटं छत्रादियुतां पूजितां सपरिवारां तां प्रतिमां च दद्यात्॥
तत्र मन्त्रः---
नमो नमस्ते गोविन्द बुधश्रवणसंज्ञक।
अघौघसङ्क्षयं कृत्वा सर्वसौख्यप्रदो भव॥
---धर्मसिन्धौ
हेमाद्रौ मत्स्यपुराणे---
द्वादशी श्रवणायुक्ता कृत्स्ना पुण्यतमा तिथिः।
न तु सा तेन संयुक्ता तावत्येव प्रशस्यते॥
श्रवणशब्द स्त्रीलिङ्गोऽपीति हेमाद्रिः। श्रवणस्पृष्टेति पाठान्तरं च।
हेमाद्राविमां प्रकृत्य नारदीय पुराणे---
तिथिनक्षत्रयोर्योगो योगश्चैव नराधिप।
द्विकलो यदि लभ्येत स ज्ञेयो ह्याष्टयामिकः॥
---पुरुषार्थचिन्तामणौ
तत्रैकादश्यां द्वादशीश्रवणयोगे सैवोपोष्या।
एकादशी द्वादशी च वैष्णव्यमपि तत्र चेत्।
तद्विष्णुशृङ्खलं नाम विष्णुसायुज्यकृद् भवेत्॥ इति विष्णुधर्मोक्तेः।
नारदीयेऽपि---
संस्पृश्यैकादशीं राजन् द्वादशीं यदि संस्पृशेत्।
श्रवणं ज्योतिषां श्रेष्ठं ब्रह्महत्यां व्यपोहति॥
द्वादशी श्रवणस्पृष्टा स्पृशेदेकादशीं यदि।
स एव वैष्णवो योगो विष्णुशृङ्खलसंज्ञितः॥ इति हेमाद्रौ मात्स्योक्तेश्च।
दिनद्वये द्वादशी-श्रवणयोगेऽपि पूर्वा। निर्णयामृते त्वस्य पूर्वार्धमन्यथा पठितम्---
द्वादशी श्रवणर्क्षं च स्पृशेदेकादशीं यदि। इति।
तेन हेमाद्रिमते एकादश्याः श्रवणयोगाभावेऽपि तद्युक्त-द्वादशीयोगमात्रेण विष्णुशृङ्खलं भवति।
---निर्णयसिन्धौ
यदा द्वादश्यां श्रवणनक्षत्रं भवेत् तदा शुद्धैकादशीमपि परित्यज्य द्वादश्यामेवोपवसेत्।
तथा च नारदः---
शुक्ला वा यदि वा कृष्णा द्वादशी श्रवणान्विता।
तयोरेवोपवासश्च त्रयोदश्यां तु पारणम्॥
एकादश्यां त्वविद्धायां द्वादश्यां श्रवणं यदि।
उपोष्या द्वादशी पुण्या सर्वपापक्षयावहा॥ इति।
स्मृत्यन्तरेऽपि---
एकादशीं परित्यज्य द्वादशीं समुपोषयेत्।
पूर्वोपवासजं पुण्यं सर्वं प्राप्नोत्यसंशयम्॥ इति।
शक्तस्तूपवासद्वयं कुर्यात्।
एकादशीमपोष्यैव द्वादशीं समुपोषयेत्।
तत्र द्विधोपवासः स्यादुभयोर्देवता हरिः॥ इति।
अत्र देवतैक्यात्पूर्वोपवासस्य पारणं नास्तीत्युक्तं भवति।
विद्धायामपि द्वादश्यां फलाधिक्यमुक्तं स्मृत्यन्तरे---
द्वादश्येकादशीयुक्ता तत्र च श्रवणं यदि।
सा विष्णुशृङ्खला ज्ञेया सायुज्यफलदायिनी॥
गौतमोऽपि---
द्वादशीं श्रवणर्क्षं च स्पृशेदेकादशी यदि।
स एव वैष्णवो योगो विष्णुशृङ्खलसंज्ञकः॥ इति।
इयं च श्रवणद्वादशी नित्या---
द्वादशीं श्रवणोपेतां यो नोपोष्यति दुर्मतिः।
पञ्चसंवत्सरकृतं पुण्यं तस्य विनश्यति॥
इत्यकरणे प्रत्यवायस्मरणात् 
---वैद्यनाथ-दीक्षितीये
कृत्यसारसमुच्चये कार्तिकमासकृत्ये---
मत्स्यपुराणे---
द्वादशीशुक्लपक्षे तु नभस्ये श्रवणं यदि।
उपोष्यकादशीं तत्र द्वादशीमप्युपोषयेत्॥
द्वादश्यां तु दिने भाद्रे हृषीकेशर्क्षसंयुते।
उपवासद्वयं कुर्याद् विष्णुप्रीणनतत्परः॥
ब्रह्माण्डे---
द्वादश्येकादशी सौम्यः श्रवणं च चतुष्टयम्।
देवदुन्दुभियोगोऽयं शतमन्युफलप्रदः॥
नभस्ये भाद्रे, हृषीकेशर्क्षं श्रवणा, सौम्यो बुधः। मन्युर्यज्ञः। 
वराहपुराणे---
एकादशीमुपोष्यैव द्वादशीमप्युपोषयेत्।
न चात्र विधिलोपः स्यादुभयोर्दैवता हरिः॥
"""

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Shukla Dvadashi tithi, combined with Shravana nakshatra. Jayā, Vijayā, Jayantī, and Pāpanāśinī—all these days have the power to destroy sins and should be observed by those seeking specific benefits. Dvadashi tithi, combined with Shravana nakshatra is extremely special. In this case, it is acceptable to skip the Ekadashi fast and fast primarily on Shravana Dvadashi. Those who are able to fast on both days may fast on both days. The Shravana Dvadashi fast is `nitya`, meaning there is a `pratyavAya` for not performing it. It is said the the `puNya` accumulated over the previous five years is destroyed, by not fasting on Shravana Dvadashi."

[names]
sa = [ "विजया~श्रवण-महाद्वादशी",]
