default_to_none = true
id = "(yama)-dIpa-trayOdazI"
tags = [ "CommonFestivals",]
shlokas = """
आश्विनस्यासिते पक्षे त्रयोदश्यां निशामुखे।
यमदीपं बहिर्दद्यात् अपमृत्युर्विनश्यति॥
मृत्युना पाशदण्डाभ्यां कालेन श्यामया सह।
त्रयोदश्यां दीपदानात् सूर्यजः प्रीयतां मम॥

दीपदानम्---
ततः प्रदोषसमये दीपान् दद्यान्मनोहरान्।
ब्रह्मविष्णुशिवादीनां भवनेषु मठेषु च॥
प्राकारोद्यानवापीषु प्रतोलीनिष्कुटेषु च।
कन्दरासु विविक्तासु हस्तिशालासु चैव हि॥
दीपदाने मन्त्रः (प्राच्यनिबन्धे)---
अग्निर्ज्योती रविर्ज्योतिश्चन्द्रो ज्योतिस्तथैव च।
उत्तमः सर्वज्योतीनां दीपोऽयं प्रतिगृह्यताम्॥
"""
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 7
anga_type = "tithi"
anga_number = 28
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Do `dAnaM` of `dIpam`, light deepam outside the house."

[names]
sa = [ "(यम)-दीप-त्रयोदशी",]
