default_to_none = true
id = "kAJcI_62_jagadguru_zrI~candrazEkharEndra_sarasvatI_4_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
संयत्सु विक्लवे लोके पीठम् आरूढवान् महान्।
इतिहासगर्भगूढनामधामादिपूर्वकः॥८॥
अनाम सर्वनामैतद् ब्रह्मेतीव प्रदर्शयन्।
जयत्यभयदश्चन्द्रशेखरेन्द्रो यतीश्वरः॥९॥
श्रीमठं कुम्भघोणं योऽनयन्नयविद् आत्मवान्।
तत्रैव संस्थितो यत्र मठोऽब्दद्विशतीं स्थितः॥१०॥
श्रीचन्द्रशेखरेन्द्रः सप्तत्रिंशत्समाः स्थितः पीठे।
शुभकृति पुष्ये कृष्णद्वितीयतिथ्याम् इयाय कैवल्यम्॥११॥
—पुण्यश्लोकमञ्जरी परिशिष्टम्
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-62.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 10
anga_type = "tithi"
anga_number = 17
kaala = "अपराह्णः"
year_start = 4884
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Preceptor Śrī Chandraśekharendra having remained in the Pīṭha for thirty-seven years attained Siddhi on Kṛṣṇadvitīya of Puṣya month in the year Subhakṛt. Śrī Maṭha moved to Kumbhaghona town during the period of this ācārya; his siddhi was also in Kumbhaghona. Śivāṣṭapadī, a lyrical work on the model of Gitagovinda of Śrī Jayadeva was composed only by this ācārya. His siddhi was during Śalivahana era 1705."

[names]
sa = [ "काञ्ची ६२ जगद्गुरु श्री-चन्द्रशेखरेन्द्र सरस्वती ४ आराधना",]
