default_to_none = true
id = "kAJcI_37_jagadguru_zrI~vidyAghanEndra_sarasvatI_3_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
भालचन्द्रसुतः सूर्यनारायणसमाह्वयः।
श्रीचिदानन्दशिष्योऽभूच्छ्रीविद्याघनदेशिकः॥७२॥
प्रपन्नः श्रीविद्यां कथमपि स विद्याघनगुरुस्तुरुष्काक्रान्तेऽपि व्यधित धुरम् आचार्यसहजाम्।
इह त्रिंशद्वर्षान् प्रभवशरदः पुष्यबहुलद्वितीयायां प्रापत् परम् उपरमं प्रौढनियमी॥७३॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-37.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 10
anga_type = "tithi"
anga_number = 17
kaala = "अपराह्णः"
year_start = 3889
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Son of Bālacandrasuta named Sūryanārāyaṇa, Śrī Vidyāghanadeśika was the disciple of Śrī Cidānanda. The preceptor Śrī Vidyāghana, mastering the Śrīvidyā held the responsibilities of the preceptor despite the atrocities of Turuṣkas for thirty years. The staunch adherent of asceticism, He reached the highest state of Bliss on the second day of the black fortnight in the month of Puṣya in the year Prabhava. This preceptor Vidyāghana, searching a worthy disciple to adorn the seat of the Pīṭha, reached Cidambaram where He handed over the responsibilities of governing (the Maṭha) to Dhīraśaṅkarendra and attained siddhi there itself. His preceptorship was for thirty years."

[names]
sa = [ "काञ्ची ३७ जगद्गुरु श्री-विद्याघनेन्द्र सरस्वती ३ आराधना",]
