default_to_none = true
id = "cidambarE_dhvajArOhaNam_or_paJcamUrti_rathOtsavaH"
tags = [ "TamilnaduTempleFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
anchor_festival_id = "naTarAjar_An2i_tirumaJcan2am"
offset = -9
jsonClass = "HinduCalendarEventTiming"

[description]
en = "The Brahmotsavam of Nataraja at Chidambaram happens specially around the Aani Thirumanjana festival each year, for ten days. On this day, there is a special rathotsava, with the panchamurtis."

[names]
sa = [ "चिदम्बरे ध्वजारोहणम्/पञ्चमूर्ति रथोत्सवः",]
