default_to_none = true
id = "sarvanadI-rajasvalA~2"
tags = [ "CommonFestivals",]
shlokas = """
अत्रिः---
सिंहकर्कटयोर्मध्ये सर्वा नद्यो रजस्वलाः।
न स्नानादीनि कर्माणि तासु कुर्वीत मानवः॥
योगयाज्ञवल्क्यः---
रजोदुष्टेऽम्भसि स्नानं वर्ज्यं नद्यादिषु द्विजैः।
कदर्थितं रजस्तेषां सन्ध्योपास्तिश्च तर्पणम्
व्याघ्रपादः---
सिंहकर्कटयोर्मध्ये सर्वा नद्यो रजस्वलाः।
तासु स्नानं न कुर्वीत वर्जयित्वा समुद्रगाः॥
कात्यायनः---
कर्कटादौ रजोदुष्टा गोमती वासरत्रयम्।
चन्द्रभागा सती सिन्धुः सरयूनर्मदा तथा॥
अत्रापवादमाह मरीचिः---
आदित्यदुहिता गङ्गा प्लक्षजाता सरस्वती।
रजसा नाभिभूयन्ते ये चान्ये नदसंज्ञिताः॥
मार्कण्डेयः---
कालिन्दी गौतमी गङ्गा वेणिका च सरस्वती।
सामर्थ्यादाभिजात्याच रजो नाभिभवत्यमूः॥
जाह्नव्यादित्यसम्भूता प्लक्षजाता सरस्वती।
रजसा नैव दुष्यन्ति नदाः कृष्णा च वेणिका॥
वामनपुराणे---
सरस्वती नदी पुण्या तथा वैतरणी नदी।
आपगा च महापुण्या गङ्गा मन्दाकिनी तथा॥
मधुप्रवाहांऽशुमती कौशिकी पापनाशिनी।
दृषद्वती महापुण्या तथा वैतरणी नदी॥
एतासामुदकं पुण्यं वर्षाकाले प्रवर्द्धितम्।
रजस्वलात्वमेतासां विद्यते न कदाचन॥
यमः---
गङ्गा धर्मोद्भवा पुण्या यमुना च सरस्वती।
अन्तर्गतरजोयोगाः सर्वाहःस्वपि चामलाः॥
कालादर्शः---
सिंहकर्कटयोर्नद्यः सर्वा एव रजस्वलाः।
त्रिदिनं स्युर्महानद्यो गोदां पेण्णां सरस्वतीम्।
भागीरथीं च कालिन्दी नदान् शोणादिकान् विना॥
केचित्तु–--
या निस्सृता नदाः प्रोक्ता याश्च गङ्गेति कीर्तिताः।
एतासां कर्कटे भानौ रजोदोषो न विद्यते॥
कावेरीतुङ्गभद्रा च कृष्णवेणी च गौतमी।
भागीरथी च विख्याता पञ्चगङ्गाः प्रकीर्तिताः॥
कात्यायन:
उपाकर्मणि चोत्सर्गे प्रेतस्नाने तथैव च।
चन्द्रसूर्यग्रहे चैव रजोदोषो न विद्यते॥
महदम्बुसमं वाऽपि यदि तिष्ठेत् पुरातनम्।
नवाम्बु मिश्रितं तेन न दुष्टमिति सूरयः॥ 
व्याघ्रपादः---
अभावे कूपवापीनामनपायिपयोभृताम्।
रजोदुष्टेऽपि पयसि ग्रामभोगो न दुष्यति॥
"""
references_primary = [ "Vaidyanatha Dikshitiyam (SVR) Part 2 p.328--334",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "sidereal_solar_month"
month_number = 4
anga_type = "day"
anga_number = 2
jsonClass = "HinduCalendarEventTiming"

[description]
en = "One must not bathe in many (small) rivers during the rainy season. Especially for the first three days of Karkataka masa, these rivers are impure. However, this does not apply to the Mahanadis, owing to their greatness, including Ganga, Yamuna, Sarasvati, Godavari, Kaveri, Shona, Penna, and the Pancha Gangas (Kaveri, Tungabhadra, Krishnaveni, Gautami, Bhagirathi). Exceptions are made in the case of Upakarma, Utsarga, Grahanam, Preta snanam etc., and when new water can be mixed in these rivers, and when there is a lack of other water sources."

[names]
sa = [ "सर्वनदी-रजस्वला",]
