default_to_none = true
id = "kuGgiliyakkalaya_nAyan2mAr_(11)_gurupUjai"
tags = [ "NayanmarGurupujai",]
references_secondary = [ "63 Nayanmar Saints by Swami Sivananda, published by The Divine Life Society",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "sidereal_solar_month"
priority = "paraviddha"
month_number = 5
anga_type = "nakshatra"
anga_number = 19
kaala = "प्रातः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """
Between the 6th and 9th centuries, in South India, there existed 63 ardent devotees of Bhagavan Shiva, collectively known as the Nayanmars. These devout individuals, hailing from various walks of life including potters, fishermen, farmers, merchants, priests, hunters, and washermen, created devotional songs still sung by followers around the globe. Among these Nayanmars, Appar, Sambandar, and Sundarar, known for their Thevaram hymns, along with Manikkavasagar, are distinguished as the Samayacharyas or the ‘The Four’ (`nAlvar`) revered teachers of the faith. They were instrumental in promoting the Shaiva Siddhanta philosophy and culture, effectively challenging the spread of Jainism and Buddhism. Their teachings centered around the concept that Shiva embodies love, and that embracing love for all beings and existence is essential in connecting with Shiva, the Supreme Being.

Kungiliya Kalaya Nayanmar, a Brahmana from Tirukadavur in the Chola kingdom, was renowned for his devotion to Bhagavan Shiva, symbolised by his constant burning of incense before the deity. The temple in Tirukadavur housed the Amrita Lingam, which originated from a pot of nectar transformed into a Lingam. The temple's deity, Amrita Ghateshwarar, was worshipped by Markandeya, leading to his immortality. The goddess of the temple, Abhirami Amman, was venerated by Abhirami Bhattar, whose devotion led to a miraculous transformation of the moon's phase.

Despite experiencing sudden poverty, Nayanmar continued his devotion, even selling his property to maintain his ritual of burning incense. One day, his wife, willing to support his devotion, offered her sacred Mangalyam to sell for food. However, when Nayanmar went to sell it, he was so captivated by the offer of high-quality incense from a hawker (Bhagavan Shiva in disguise) that he exchanged the Mangalyam for it, forgetting his family's hunger.

Bhagavan Shiva, impressed with the couple's devotion, blessed them with wealth. Nayanmar's wife prepared a meal and awaited his return. When Nayanmar went to the temple with the incense, Bhagavan Shiva appeared to him, acknowledging his devotion and instructing him to return home. Astonished, Nayanmar found his house transformed into a place of prosperity and shared his newfound wealth with other Shiva Bhaktas.

Nayanmar's devotion was further exemplified in Tiruppanandal, where he straightened the leaning Lingam of Arunasatesar, which had tilted to accept a garland from a devotee. Using a rope of divine love, Nayanmar miraculously righted the Lingam, a feat that astonished and earned him further reverence.

After spending more time serving Bhagavan Shiva and His devotees, Nayanmar eventually attained the divine abode, leaving a legacy of unwavering devotion and service to the Bhagavan.
"""

[names]
ta = [ "kuGgiliyakkalaya nAyan2mAr (11) gurupUjai",]
