default_to_none = true
id = "mInAkSI_azva_vAhanam"
tags = [ "TamilnaduTempleFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
anchor_festival_id = "mIn2AkSI_tirukkalyANam"
offset = -5
jsonClass = "HinduCalendarEventTiming"

[description]
en = """
Rous Peter, a British collector who administered Madurai from 1812-1828, was known for his deep respect for the Meenakshi temple. He would dismount his horse, remove his hat and boots when passing the temple, earning him the nickname ‘Peter Pandian’. Legend tells that one stormy night, a three-year-old girl with tinkling anklets led him out of his house moments before it collapsed. Believing it was Goddess Meenakshi herself who saved him, Peter commissioned golden stirrups (Padukas) adorned with 412 rubies, 72 emeralds, and 80 diamonds as an offering. These "Peter Padukas" are still used during the 5th day of the annual Chithirai festival when the Devi rides Her horse. His devotion was so deep that he chose to settle in Madurai rather than return to England after his retirement.
From: https://x.com/AnObserversView/status/1777654948647571495
"""

[names]
ta = [ "mIn2AkSI taGga kudirai vAhan2am",]
