jsonClass = "HinduCalendarEvent"
default_to_none = true
id = "ta__tiruccendUr murugan2 AvaNit tiruvizhA ##5##m nAL"
script_priority = "ta"
tags = [ "TamilnaduTempleFestivals",]

[timing]
jsonClass = "HinduCalendarEventTiming"
default_to_none = true
anchor_festival_id = "ta__tiruccendUr AvaNit tiruvizhA nir2aivu"
offset = -7
