default_to_none = true
id = "kAJcI_20_jagadguru_zrI~mUkazaGkarEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
जातः खल्वाटवीराद् गणककुलमणेः साधु विद्यावतीतो
मूको मूकार्भनामा भुवनगुरुपदाम्भोजरेणोर्महिम्ना।
व्यक्तप्रौढोक्तिराप्त्वोपनयनमखिलाम्नायजातं च ताताद्
गृह्णन् सन्न्यासम् आसीत् परम् अधिजगदाचार्यपीठं स धीरः॥४३॥
श्रीशङ्करेन्द्रः श्रितमातृगुप्तम् आधाय वर्णाश्रमधर्मपालम्।
सैकोनषष्टित्रिशते शकेऽब्दे सिद्धिं गतः श्रावणपूर्णिमायाम्॥४४॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-20.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 5
anga_type = "tithi"
anga_number = 15
kaala = "अपराह्णः"
year_start = 3538
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Dumb boy, as He was named born of Khalvāṭavīra, the gem in the family of gaṇakas, got the ability to speak eloquently through the greatness of (the grace of) the Universal Preceptor, invested with sacred thread, and initiated into the entire scripture by his father and taking up asceticism, He remained in the seat of Universal preceptor. Preceptor Śaṅkarendra (Arbhakaśaṅkara), after installing Mātṛgupta, the ardent follower of the precepts of varṇāśrama (enjoined for respective classes of people) attained Siddhi on the full moon day in the month of Śravaṇa of the Śaka year 359. (In the Sanskrit and Tamil explanations on Pages 22 & 23, Matrugupta appears to be a patron of Sankarendra along with Ramilla, Sri Harsha etc.)"

[names]
sa = [ "काञ्ची २० जगद्गुरु श्री-मूकशङ्करेन्द्र सरस्वती आराधना",]
