[CHANDRA_MASA_NAMES]
sa = [
    'चैत्रः',
    'वैशाखः',
    'ज्यैष्ठः',
    'आषाढः',
    'श्रावणः',
    'भाद्रपदः',
    'आश्वयुजः',
    'कार्त्तिकः',
    'मार्गशीर्षः',
    'पौषः',
    'माघः',
    'फाल्गुनः',
]

[KARANA_NAMES]
sa = [
    'किंस्तुघ्नः',
    'बवः',
    'बालवः',
    'कौलवः',
    'तैतिलः',
    'गरः',
    'वणिजः',
    'विष्टिः',
    'बवः',
    'बालवः',
    'कौलवः',
    'तैतिलः',
    'गरः',
    'वणिजः',
    'विष्टिः',
    'बवः',
    'बालवः',
    'कौलवः',
    'तैतिलः',
    'गरः',
    'वणिजः',
    'विष्टिः',
    'बवः',
    'बालवः',
    'कौलवः',
    'तैतिलः',
    'गरः',
    'वणिजः',
    'विष्टिः',
    'बवः',
    'बालवः',
    'कौलवः',
    'तैतिलः',
    'गरः',
    'वणिजः',
    'विष्टिः',
    'बवः',
    'बालवः',
    'कौलवः',
    'तैतिलः',
    'गरः',
    'वणिजः',
    'विष्टिः',
    'बवः',
    'बालवः',
    'कौलवः',
    'तैतिलः',
    'गरः',
    'वणिजः',
    'विष्टिः',
    'बवः',
    'बालवः',
    'कौलवः',
    'तैतिलः',
    'गरः',
    'वणिजः',
    'विष्टिः',
    'शकुनिः',
    'चतुष्पात्',
    'नाग',
]

[KRISHNA_EKADASHI_NAMES]
sa = [
    'वरूथिनी',
    'अपरा',
    'योगिनी',
    'कामिका',
    'अजा',
    'इन्दिरा',
    'रमा',
    'उत्पन्ना',
    'सफला',
    'षट्तिला',
    'विजया',
    'पापमोचनी',
    'परमा',
]

[SANKATAHARA_CHATURTHI_NAMES]
sa = [
    'विकट',
    'एकदन्त',
    'कृष्णपिङ्गल',
    'गजानन',
    'हेरम्ब',
    'विघ्नराज',
    'वक्रतुण्ड',
    'गणाधिप',
    'आखुरथ',
    'लम्बोदर',
    'द्विजप्रिय',
    'भालचन्द्र',
    'विभुवन',
]

[NAKSHATRA_NAMES]
sa = [
    'अश्विनी',
    'अपभरणी',
    'कृत्तिका',
    'रोहिणी',
    'मृगशीर्षम्',
    'आर्द्रा',
    'पुनर्वसुः',
    'पुष्यः',
    'आश्रेषा',
    'मघा',
    'पूर्वफल्गुनी',
    'उत्तरफल्गुनी',
    'हस्तः',
    'चित्रा',
    'स्वाती',
    'विशाखा',
    'अनूराधा',
    'ज्येष्ठा',
    'मूला',
    'पूर्वाषाढा',
    'उत्तराषाढा',
    'श्रवणः',
    'श्रविष्ठा',
    'शतभिषक्',
    'पूर्वप्रोष्ठपदा',
    'उत्तरप्रोष्ठपदा',
    'रेवती',
]

[PUSHKARA_NAMES]
sa = [
    'गङ्गा',
    'नर्मदा',
    'सरस्वती',
    'यमुना',
    'गोदावरी',
    'कृष्णा',
    'कावेरी',
    'ताम्रपर्णी',
    'सिन्धु',
    'भद्रा',
    'भीमरथी',
    'प्राणहिता',
]

[RASHI_NAMES]
sa = [
    'मेषः',
    'वृषभः',
    'मिथुनम्',
    'कर्कटः',
    'सिंहः',
    'कन्या',
    'तुला',
    'वृश्चिकः',
    'धनुः',
    'मकरः',
    'कुम्भः',
    'मीनः',
]

[RASHI_SUFFIXED_NAMES]
sa = [
    'मेष-राशिः',
    'वृषभ-राशिः',
    'मिथुन-राशिः',
    'कटक-राशिः',
    'सिंह-राशिः',
    'कन्या-राशिः',
    'तुला-राशिः',
    'वृश्चिक-राशिः',
    'धनुर्-राशिः',
    'मकर-राशिः',
    'कुम्भ-राशिः',
    'मीन-राशिः',
]

[SHUKLA_EKADASHI_NAMES]
sa = [
    'कामदा',
    'मोहिनी',
    'पाण्डव-निर्जला',
    'शयन',
    'पवित्रोपान',
    'परिवर्तिनी',
    'पापाङ्कुशा',
    'उत्थान',
    'मोक्षदा',
    'पुत्रदा',
    'जया/भैमी',
    'आमलकी',
    'पद्मिनी',
]

[TITHI_NAMES]
sa = [
    'शुक्ल-प्रथमा',
    'शुक्ल-द्वितीया',
    'शुक्ल-तृतीया',
    'शुक्ल-चतुर्थी',
    'शुक्ल-पञ्चमी',
    'शुक्ल-षष्ठी',
    'शुक्ल-सप्तमी',
    'शुक्ल-अष्टमी',
    'शुक्ल-नवमी',
    'शुक्ल-दशमी',
    'शुक्ल-एकादशी',
    'शुक्ल-द्वादशी',
    'शुक्ल-त्रयोदशी',
    'शुक्ल-चतुर्दशी',
    'पौर्णमासी',
    'कृष्ण-प्रथमा',
    'कृष्ण-द्वितीया',
    'कृष्ण-तृतीया',
    'कृष्ण-चतुर्थी',
    'कृष्ण-पञ्चमी',
    'कृष्ण-षष्ठी',
    'कृष्ण-सप्तमी',
    'कृष्ण-अष्टमी',
    'कृष्ण-नवमी',
    'कृष्ण-दशमी',
    'कृष्ण-एकादशी',
    'कृष्ण-द्वादशी',
    'कृष्ण-त्रयोदशी',
    'कृष्ण-चतुर्दशी',
    'अमावास्या',
]

[TITHI_NAMES_ABBR]
sa = [
    'शु-प्रथमा',
    'शु-द्वितीया',
    'शु-तृतीया',
    'शु-चतुर्थी',
    'शु-पञ्चमी',
    'शु-षष्ठी',
    'शु-सप्तमी',
    'शु-अष्टमी',
    'शु-नवमी',
    'शु-दशमी',
    'शु-एकादशी',
    'शु-द्वादशी',
    'शु-त्रयोदशी',
    'शु-चतुर्दशी',
    'पौर्णमासी',
    'कृ-प्रथमा',
    'कृ-द्वितीया',
    'कृ-तृतीया',
    'कृ-चतुर्थी',
    'कृ-पञ्चमी',
    'कृ-षष्ठी',
    'कृ-सप्तमी',
    'कृ-अष्टमी',
    'कृ-नवमी',
    'कृ-दशमी',
    'कृ-एकादशी',
    'कृ-द्वादशी',
    'कृ-त्रयोदशी',
    'कृ-चतुर्दशी',
    'अमावास्या',
]

[VARA_NAMES]
sa = [
    'भानुः',
    'सोमः',
    'मङ्गलः',
    'बुधः',
    'गुरुः',
    'शुक्रः',
    'शनिः',
]

[VARA_NAMES_ALT]
sa = [
    'भानुः',
    'इन्दुः',
    'भौमः',
    'सौम्यः',
    'गुरुः',
    'भृगुः',
    'स्थिरः',
]

[SAMVATSARA_NAMES]
sa = [
    'प्रभवः',
    'विभवः',
    'शुक्लः',
    'प्रमोदः',
    'प्रजापतिः',
    'अङ्गिराः',
    'श्रीमुखः',
    'भावः',
    'युवा',
    'धाता',
    'ईश्वरः',
    'बहुधान्यः',
    'प्रमाथी',
    'विक्रमः',
    'वृषः',
    'चित्रभानुः',
    'सुभानुः',
    'तारणः',
    'पार्थिवः',
    'व्ययः',
    'सर्वजित्',
    'सर्वधारी',
    'विरोधी',
    'विकृतिः',
    'खरः',
    'नन्दनः',
    'विजयः',
    'जयः',
    'मन्मथः',
    'दुर्मुखः',
    'हेमलम्बः',
    'विलम्बः',
    'विकारी',
    'शार्वरी',
    'प्लवः',
    'शुभकृत्',
    'शोभनः',
    'क्रोधी',
    'विश्वावसुः',
    'पराभवः',
    'प्लवङ्गः',
    'कीलकः',
    'सौम्यः',
    'साधारणः',
    'विरोधिकृत्',
    'परितापी',
    'प्रमादी',
    'आनन्दः',
    'राक्षसः',
    'नलः',
    'पिङ्गलः',
    'कालयुक्तिः',
    'सिद्धार्थी',
    'रौद्रः',
    'दुर्मतिः',
    'दुन्दुभिः',
    'रुधिरोद्गारी',
    'रक्ताक्षः',
    'क्रोधनः',
    'क्षयः',
]

[YOGA_NAMES]
sa = [
    'विष्कम्भः',
    'प्रीतिः',
    'आयुष्मान्',
    'सौभाग्यः',
    'शोभनः',
    'अतिगण्डः',
    'सुकर्म',
    'धृतिः',
    'शूलः',
    'गण्डः',
    'वृद्धिः',
    'ध्रुवः',
    'व्याघातः',
    'हर्षणः',
    'वज्रम्',
    'सिद्धिः',
    'व्यतीपातः',
    'वरीयान्',
    'परिघः',
    'शिवः',
    'सिद्धः',
    'साध्यः',
    'शुभः',
    'शुक्लः',
    'ब्रह्म',
    'इन्द्रः',
    'वैधृतिः',
]

[AYANA_NAMES]
sa = [
    'उत्तरायणम्',
    'उत्तरायणम्',
    'उत्तरायणम्',
    'दक्षिणायनम्',
    'दक्षिणायनम्',
    'दक्षिणायनम्',
    'दक्षिणायनम्',
    'दक्षिणायनम्',
    'दक्षिणायनम्',
    'उत्तरायणम्',
    'उत्तरायणम्',
    'उत्तरायणम्',
]

[RTU_MASA_NAMES_SHORT]
sa = [
    'मधुः',
    'माधवः',
    'शुक्रः',
    'शुचिः',
    'नभः',
    'नभस्यः',
    'इषः',
    'ऊर्जः',
    'सहः',
    'सहस्यः',
    'तपः',
    'तपस्यः',
]

[RTU_MASA_NAMES]
sa = [
    'मधु-मासः',
    'माधव-मासः',
    'शुक्र-मासः',
    'शुचि-मासः',
    'नभो-मासः',
    'नभस्य-मासः',
    'इष-मासः',
    'ऊर्ज-मासः',
    'सहो-मासः',
    'सहस्य-मासः',
    'तपो-मासः',
    'तपस्य-मासः',
]

[RTU_NAMES]
sa = [
    'वसन्तऋतुः',
    'वसन्तऋतुः',
    'ग्रीष्मऋतुः',
    'ग्रीष्मऋतुः',
    'वर्षऋतुः',
    'वर्षऋतुः',
    'शरदृतुः',
    'शरदृतुः',
    'हेमन्तऋतुः',
    'हेमन्तऋतुः',
    'शिशिरऋतुः',
    'शिशिरऋतुः',
]

[GRAHA_NAMES.sa]
sun = 'सूर्यः'
moon = 'चन्द्रः'
jupiter = 'गुरुः'
venus = 'शुक्रः'
mercury = 'बुधः'
mars = 'मङ्गलः'
saturn = 'शनैश्चरः'
rahu = 'राहुः'

[[SHUULAM.sa]]
dik = 'प्रतीची'
end_muhuurta = 12
parihaara = 'गुडम्'

[[SHUULAM.sa]]
dik = 'प्राची'
end_muhuurta = 8
parihaara = 'दधि'

[[SHUULAM.sa]]
dik = 'उदीची'
end_muhuurta = 12
parihaara = 'क्षीरम्'

[[SHUULAM.sa]]
dik = 'उदीची'
end_muhuurta = 16
parihaara = 'क्षीरम्'

[[SHUULAM.sa]]
dik = 'दक्षिणा'
end_muhuurta = 20
parihaara = 'तैलम्'

[[SHUULAM.sa]]
dik = 'प्रतीची'
end_muhuurta = 12
parihaara = 'गुडम्'

[[SHUULAM.sa]]
dik = 'प्राची'
end_muhuurta = 8
parihaara = 'दधि'

[SA_TO_TAMIL]
"चन्द्रास्तमयः" = 'சந்த்ராஸ்தமனம்'
"क्षेत्रम्" = 'குறிப்பிட்ட ஊருக்கான தகவல்கள்'
"चन्द्रोदयः" = 'சந்த்ரோதயம்'
"चान्द्रमानम्" = 'சாந்த்ரமானம்'
"अहोरात्रम्" = 'நாள் முழுவதும்'
"तिथिः" = 'திதி'
"दिनं" = 'தேதி'
"पक्षः" = 'பக்ஷம்'
"नक्षत्रम्" = 'நக்ஷத்ரம்'
"योगः" = 'யோகம்'
"मासः" = 'மாஸம்'
"ऋतुः" = 'ருதுஃ'
"अयनम्" = 'அயனம்'
"करणम्" = 'கரணம்'
"राशिः" = 'ராஶிஃ'
"लग्नम्" = 'லக்னம்'
"चन्द्राष्टम-राशिः" = 'சந்த்ராஷ்டம-ராஶிஃ'
"शूलम्" = 'ஶூலம்'
"वासरः" = 'வாஸரம்'
"दिन-विशेषाः" = 'தின-விஶேஷங்கள்'
"संवत्सरः" = 'ஸம்வத்ஸரம்'
"सूर्यास्तमयः" = 'ஸூர்யாஸ்தமனம்'
"सूर्योदयः" = 'ஸூர்யோதயம்'
"सौरमानम्" = 'ஸௌரமானம்'
"दिनान्तः" = 'தினாந்தம்'
"अपराह्ण-कालः" = 'அபராஹ்ண-காலம்'
"राहुकालः" = 'ராஹுகாலம்'
"यमघण्टः" = 'யமகண்டம்'
"गुलिककालः" = 'குலிககாலம்'
"परिहारः" = 'பரிஹாரம்'
"गुडम्" = 'வெல்லம்'
"दधि" = 'தயிர்'
"क्षीरम्" = 'பால்'
"तैलम्" = 'எண்ணெய்'
"प्राची" = 'கிழக்கு'
"उदीची" = 'வடக்கு'
"दक्षिणा" = 'தெற்கு '
"प्रतीची" = 'மேற்கு'

[ARAB_MONTH_NAMES]
ar = [
    'Al-Muḥarram',
    'Ṣafar',
    'Rabīʿ alʾ Awwal/Ūlā',
    'Rabīʿ ath-Thānī/ al-ʾĀkhir',
    'Jumādā al-ʾAwwal/ʾŪlā',
    'Jumādā ath-Thāniyah/ al-ʾĀkhirah',
    'Rajab',
    'Shaʿbān',
    'Ramaḍān',
    'Shawwāl',
    'Ḏū al-Qaʿdah',
    'Ḏū al-Ḥijjah',
]

[TIPU_ABJAD_MONTH_NAMES]
fa = [
    'Aḥmadi',
    'Bahārī',
    '''Ja'fari''',
    'Dārāī',
    'Hashimī',
    'Wāsēī',
    'Zabarjadī',
    'Haidarī',
    '''Ṭūlu'ī''',
    'Yūsafī',
    'Ezidī',
    'Bayāḍī',
]

[TIPU_ABTATH_MONTH_NAMES]
fa = [
    'Aḥmadi',
    'Bahārī',
    'Taqī',
    'Ṭhamarī',
    '''Ja'farī''',
    'Haidarī',
    'Khusravī',
    'Dīnī',
    'Dhākirī',
    'Raḥmānī',
    'Rāzī',
    'Rabānī',
]

[SIDEREAL_SOLAR_MONTH_NAMES]
ta = [
    'चित्तिरै',
    'वैगासि',
    'आनि',
    'आडि',
    'आवणि',
    'पुरट्टासि',
    'ऐप्पसि',
    'कार्त्तिगै',
    'मार्गऴि',
    'तै',
    'मासि',
    'पङ्गुनि',
]
ml = [
    'मेटं',
    'इटवं',
    'मिथुनं',
    'कर्क्कटकं',
    'चिङ्ङं',
    'कन्नि',
    'तुलां',
    'वृश्चिकं',
    'धनु',
    'मकरं',
    'कुंभं',
    'मीनं',
]
as = [
    'ब’हाग',
    'जेठ',
    'आहार',
    'शाओण',
    'भाद',
    'आहिन',
    'काति',
    'आघोण',
    'पोह',
    'माघ',
    'फागुन',
    'च’त',
]
pa = [
    'विसाख',
    'जेठ',
    'हाड़्ह',
    'साओण',
    'भादों',
    'अस्सू',
    'कत्तक',
    'मग्घर',
    'पोह',
    'माघ',
    'फग्गण',
    'चेत',
]
