default_to_none = true
id = "dattAtrEya~jayantI"
tags = [ "OtherAvatarams", "CommonFestivals",]
shlokas = """
आदौ ब्रह्मा मध्ये विष्णुरन्ते देवः सदाशिवः।
मूर्तित्रयस्वरूपाय दत्तात्रेय नमोऽस्तु ते॥
"""
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "puurvaviddha"
month_number = 9
anga_type = "tithi"
anga_number = 15
kaala = "प्रदोषः"
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "दत्तात्रेय-जयन्ती",]
