default_to_none = true
id = "kAJcI_58_jagadguru_zrI~AtmabOdhEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
वृद्धाचलप्रभवविश्वमखीन्द्रसूनुर्-
विश्वेश्वरः परशिवार्यपदं प्रपन्नः।
आसेतुशीतगिरि कल्पितजैत्रयात्र
आद्यात् स शङ्करगुरोरतिहृद्य आसीत्॥६॥
विश्वाधिकस्वधिषणत्वत एनमाहुर्-
विश्वाधिकेन्द्रम् अनघा नवशङ्करं च।
श्रीरुद्रभाष्यमुखभूरितरप्रबन्ध-
सन्धानकौशलम् अमुष्य किमप्यमेयम्॥७॥
द्वापञ्चाशतम् उद्वहन् गुरुधुराम् अब्दानवाच्यां दिशि
प्रस्थाने गरुडापगातटभुवि प्रापत् पदं शाश्वतम्।
बोधेन्द्रार्यविसृष्टविष्टरधुरो विश्वाधिकेन्द्रस्तुला-
कृष्णाष्टम्यहनीश्वरे हृदि दधत् सोमार्धचूडामणिम्॥८॥
—पुण्यश्लोकमञ्जरी परिशिष्टम्
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-58.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 8
anga_type = "tithi"
anga_number = 23
kaala = "अपराह्णः"
year_start = 4739
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Viśveśvara was the son of Viśvamakhindra; resorting to the fact of Paraśivārya, known as Navaśaṅkara from the first preceptor toured all places successfully, from Setu (Rāmeśvaram) to Sītāgiri (Himalayas). Since He possessed intellect more than anyone in the Universe, men of wisdom call him Viśvādhika and Navaśaṅkara. His erudition in composing works such as Rudra bhāṣya is beyond words—immeasurable. The preceptor Viśvādhikendra carrying out the responsibilities of preceptor for fifty-two years, (later) handing over the responsibilities to Bodhendrārya, and proceeding in southern direction reached eternal abode, meditating on Lord Śiva with the crescent moon in the crown, on the banks of river Garuḍa on the eighth day of the black fortnight in the month of Tulā of the year Īśvara. This preceptor Śrī Navaśaṅkara residing on the banks of river Tridaśa was revered by eminent men, departed in the southern direction and attained siddhi on the banks of river Garuḍa after handing over the responsibilities to the disciple Śrī Bhagavannāma Bodhendra. "

[names]
sa = [ "काञ्ची ५८ जगद्गुरु श्री-आत्मबोधेन्द्र सरस्वती आराधना",]
