default_to_none = true
id = "kAJcI_42_jagadguru_zrI~brahmAnandaghanEndra_sarasvatI_2_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
सुब्रह्मण्यभवो नियम्य नरसम्भट्टोऽथ गङ्गाधराद्
ब्रह्मानन्दघनाभिधोऽधित धुरां द्व्यूनाः समास्त्रिंशतम्।
लिल्येऽधीश्वरम् ईश्वरोर्जबहुलाष्टम्याम् असौ सङ्गवे
घुष्यन्नेव हि सूत्रभाष्यविषयान् अन्तेवसद्भ्यः पटु॥८५॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-42.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 8
anga_type = "tithi"
anga_number = 23
kaala = "अपराह्णः"
year_start = 4079
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Then Narasambhaṭṭa, son of Subrahmanya, having been initiated by Gaṅgādhara got the appellation Brahmānandaghana held the preceptorship of the Pīṭha for twenty-eight years. This great preceptor merged in the Lord Īśvara as He was teaching the disciples the Brahmasūtra, bhāṣya etc. in the early morning of Aṣṭami of Kṛṣṇapakṣa in the month of Kārtika in the year Īśvara."

[names]
sa = [ "काञ्ची ४२ जगद्गुरु श्री-ब्रह्मानन्दघनेन्द्र सरस्वती २ आराधना",]
