default_to_none = true
id = "kaNampulla_nAyan2mAr_(47)_gurupUjai"
tags = [ "NayanmarGurupujai",]
references_secondary = [ "63 Nayanmar Saints by Swami Sivananda, published by The Divine Life Society",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "sidereal_solar_month"
priority = "paraviddha"
month_number = 8
anga_type = "nakshatra"
anga_number = 3
kaala = "प्रातः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """Between the 6th and 9th centuries, in South India, there existed 63 ardent devotees of Bhagavan Shiva, collectively known as the Nayanmars. These devout individuals, hailing from various walks of life including potters, fishermen, farmers, merchants, priests, hunters, and washermen, created devotional songs still sung by followers around the globe. Among these Nayanmars, Appar, Sambandar, and Sundarar, known for their Thevaram hymns, along with Manikkavasagar, are distinguished as the Samayacharyas or the ‘The Four’ (`nAlvar`) revered teachers of the faith. They were instrumental in promoting the Shaiva Siddhanta philosophy and culture, effectively challenging the spread of Jainism and Buddhism. Their teachings centered around the concept that Shiva embodies love, and that embracing love for all beings and existence is essential in connecting with Shiva, the Supreme Being.

Kanampulla Nayanmar, a wealthy resident of Irukkuvelur, was renowned for his profound devotion to Bhagavan Shiva. Committed to using his wealth solely for divine service, he devoted himself to lighting lamps in Shiva shrines and singing praises of the Bhagavan. To demonstrate the depth of his devotion, Bhagavan Shiva tested him by taking away his wealth. Undeterred, Kanampulla Nayanmar moved to Chidambaram and continued his services by selling his possessions to buy ghee for the lamps. Eventually, he exhausted all his resources and resorted to selling grass, specifically Kanampul, which earned him the name Kanampulla Nayanmar. One day, when he couldn't sell any grass, he remained steadfast in his duty to light the temple lamp. With no other resources left, he ingeniously used the grass as a wick to keep the lamp burning. Realizing that the grass was insufficient, he moved his head closer to the lamp, using his own hair as a wick to keep the flame burning. This ultimate act of devotion moved Bhagavan Shiva, who appeared before Kanampulla Nayanmar and bestowed his blessings upon him."""

[names]
ta = [ "kaNampulla nAyan2mAr (47) gurupUjai",]
