default_to_none = true
id = "pArvaNa-vratam_15"
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
anchor_festival_id = "sthAlIpAkaH_16"
offset = -1
jsonClass = "HinduCalendarEventTiming"

[description]
en = "`pArvaNavratam` on the eve of `pUrNa-sthAlIpAkaH`."
sa = """

## गृहस्थव्रतम्
पक्षान्ता उपवस्तव्याः, पक्षादयो ऽभियष्टव्याः। किञ्च - 'अथापराह्ण एवाप्लुत्यौपवसथिकं दम्पती भुञ्जीयातां यद् एनयोः काम्यं स्यात्- सर्पिर् मिश्रं स्यात् कुशलेन'।  

'अबहुवादी स्यात्। सत्यं विवदिषेत्। अध एवैतां रात्रिं शयीयाताम्। तौ खलु जाग्रन्-मिश्राव् एवैतां रात्रिं विहरेयाताम् इतिहास-मिश्रेण वा केनचिद् वा। जुगुप्सेयातां त्व् एवाव्रत्येभ्यः कर्मभ्यः।' 

परेद्युर् होमाय सम्भारसम्भरणादयो व्यवस्थाः कार्याः।

## प्रायश्चित्तार्थम् अपि किञ्चद् व्रतम्
"पर्वणि वा तिलभक्ष उपोष्य वा श्वोभूत उदकमुपस्पृश्य सावित्रीं प्राणायामशः सहस्रकृत्व आवर्तयेद् अप्राणायामशो वा" इत्य् आपस्तम्बधर्मसूत्रेषु। 
"""

[names]
sa = [ "पार्वणव्रतम् पूर्णिमायाम्",]
