jsonClass = "HinduCalendarEvent"
default_to_none = true
id = "ta__kapAlI viDaiyAr2r2i nir2aivu"
tags = [ "TamilnaduTempleFestivals",]

[timing]
jsonClass = "HinduCalendarEventTiming"
default_to_none = true
anchor_festival_id = "ta__kar2pagAmbALâ€“kapAlIzvarar tirukkalyANam"
offset = 11
