default_to_none = true
id = "raMgabharI_EkAdazI"
tags = [ "UttarPradeshTempleFestivals",]
references_secondary = [ "https://www.jansatta.com/religion/rangbhari-ekadashi-puja-vidhi-vrat-katha-in-hindi-rangbhari-ekadashi-2018-know-where-and-how-india-is-celebrated-do-this-like-worship/586320/",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Rangbhari Ekadashi, observed in the month of Phalguna, is an important festival in Varanasi associated with Lord Shiva and Goddess Parvati. This day marks Shiva's return to Kashi with Parvati after their wedding, and devotees welcome the divine couple with joy and festivities. It is an early celebration of Holi in Kashi, where devotees gather at the Kashi Vishwanath Temple to offer prayers, sing hymns, and shower coloured powder (gulal) on the idols of Shiva and Parvati. The festival involves fasting, worship, and community gatherings, as devotees seek blessings for health, prosperity, and harmony. This day marks the beginning of Holi celebrations in Kashi, drawing people together in a jubilant display of colours, music, and devotion to Lord Shiva."

[names]
sa = [ "रंगभरी एकादशी",]
