default_to_none = true
id = "★ravivAra-mahAzivarAtriH"
tags = [ "CommonFestivals",]
shlokas = """
अस्यां (माघकृष्णचतुर्दश्यां) रविवारादियोगे प्राशस्त्यमुक्तं स्कान्दे---
माघकृष्णचतुर्दश्यां रविवारो भवेद्यदा।
भौमो वाऽपि भवेद्देवि कर्तव्यं व्रतमुत्तमम्॥
शिवयोगस्य योगे वै तद्भवेत्तूत्तमोत्तमम्।
"""
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "O Devi! When the fourteenth day of the dark half of Māgha falls on a Sunday, or even on a Tuesday, an excellent vrata must be observed. When it is combined with the yoga of Shivayoga, it becomes the best of the best★ (uttamottamam)."

[names]
sa = [ "★रविवार-महाशिवरात्रिः",]
