default_to_none = true
id = "Arumukha-nAvalar-gurupUjai"
tags = [ "NayanarGurupujai",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
year_start = 1879
year_start_era = "gregorian"
month_type = "sidereal_solar_month"
priority = "paraviddha"
month_number = 8
anga_type = "nakshatra"
anga_number = 10
kaala = "प्रातः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """
## Event
On 5 December, at his residence, माहेश्वर-s gathered to recite the द्राविड-स्तोत्र around him, knowing that the hour of his शिवपदप्राप्ति was fast approaching. Sporting रुद्राक्ष-s all over his person, sipping गङ्गाजल & having applied the sacred ash from चिदम्बरम्, मदुरै, काशि & तिरुचॆन्दूर्, he looked like a veritable शिवगण-नायक, who was merely in human guise on earth. At around 9 PM, he lifted his weak hands, one last time, to place upon his head as a humble salutation to the supreme god of gods & then gave up his last breath.

## Context
Śrī Nāvalar’s last public discourse was on आडि-स्वाति of the tamizh calendar in 1879, the गुरुपूजा of श्री-सुन्दरमूर्ति-नायनार्, the friend of महादेव. His health began to deteriorate over the next few months. The daily आत्मार्थ-पूजा he would do with so much devotion; he was unable to do it any longer & a शिवाचार्य from वेदारण्यम् would do it on his behalf.

## Major celebrations
 In सिंहपुरी, the गुरुपूजा of आऱुमुख-नावलर् (the day he attained शिवपद) is done without fail at शॆण्पक (चम्पक) विनायक temple every year on मघा-नक्षत्र of कार्त्तिका-मास as per the tamizh calendar.
"""

[names]
ta = [ "Arumukha-nAvalar-gurupUjai",]
