id = "shivarAjena_dAsagrahaNa-rodhaH"
jsonClass = "HinduCalendarEvent"

[timing]
month_type = "julian"
anga_type = "day"
month_number = 8
anga_number = 26
year_start = 1677
year_start_era = "gregorian"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Shivaji declared to the Dutch: 'In the days of the Moorish [Muslim] government it was allowed for you to buy male slaves and female slaves here [the Karnatak), and to transport the same, without anyone preventing that. But now you may not, as long as I am master of these lands, buy male or female slaves, nor transport them. And in case you were to do the same, and would want to bring [slaves] aboard, my men will oppose that and prevent it in all ways, and also not allow that they may be brought back in your house; this you must observe and comply with.'"

[names]
sa = [ "शिवराजेन दसग्रहणरोधः",]
