default_to_none = true
id = "kAJcI_47_jagadguru_zrI~candrazEkharEndra_sarasvatI_3_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
श्रीकण्ठः शुकदेवशर्मतनयः कुण्डीनदीकूलभूर्वाग्मी वाङ्मयतत्त्वसङ्ग्रहपटुर्धृष्टो वटुर्द्राविडः।
बोधेन्द्रार्यकृपागृहीतनियमः श्रीचन्द्रचूडाख्यया तिष्ठन् काञ्चिमठे बभार स धुराम् आचार्यकीं भूतले॥९१॥
मङ्खश्रीजयदेवकृष्णसुहलप्रष्ठैर्महिष्ठैर्वृतो विद्वद्भिः परितः क्षितिं विरचयन् यात्रां विजैत्रां व्रती।
विद्यालोलकुमारपालनृपतेः संसत्समुत्तंसितं हेमाचार्यमपि व्यपाकृत गिरा वागष्टकव्याकृतम्॥९२॥
ध्यायंस्तारकम् आर्तिहारकम् असौ श्रीचन्द्रचूडाश्रमी
ज्वाला-भावविकार-दृग्-जलधिभिः (४२६७) काले कलौ कालिते।
आस्थायासनम् अष्टषष्टिशरदः श्रीपार्थिवे पार्थिवं
चैत्रे चित्रम् अपर्वपर्वणि जहद्देहं विदेहोऽभवत्॥९३॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-47.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 1
anga_type = "tithi"
anga_number = 30
kaala = "अपराह्णः"
year_start = 4267
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Śrīkaṇṭha, son of Śukadevaśharma on the banks of the river Kunḍī (Kunṭī) was a drāviḍa (a southerner), eloquent, wellversed in scriptures and courageous; having received the initiation into asceticism from the compassionate preceptor Bodhendra with the name Śrī Chandracūḍa, He held the responsibilities of preceptorship on earth by remaining in Kāṅci Maṭha. This preceptor surrounded by eminent scholarpoets Maṅka, Śrī Jayadeva, Kṛṣṇa, Suhala, carrying out digvijaya throughout the earth defeated in debate the exponent of Jainism Hemācārya, whose presence embellished the assembly of King Vidyālola Kumārapāla. This preceptor Śrī Chandracūḍa meditating on the mystic syllable that dispels grief/removes misery, adorning the seat (of preceptor) for sixty-eight years, became Videha by giving up the wondrous physical body on the New moon day in Caitra month of the year Pārthiva in the Kali era 4267. This renowned preceptor followed Śrī Jayadeva, Kṛṣṇamiśra, Suhala and others, adored by King Jayasimha and Kumārapāla, destroyed the arrogance of the Jaina exponent Hemācārya and attained the final beatitude at Aruṇācala."

[names]
sa = [ "काञ्ची ४७ जगद्गुरु श्री-चन्द्रशेखरेन्द्र सरस्वती ३ आराधना",]
