id = "kAnhojI-pralobhanam"
jsonClass = "HinduCalendarEvent"

[timing]
month_type = "julian"
anga_type = "day"
month_number = 6
anga_number = 16
year_start = 1659
year_start_era = "gregorian"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """
On this day, Shia King "Imam" Ali Adil Shah unsuccessfully tried to threaten and pursuade kAnhojI jedhe to side with Afzal Khan against shivAjI, accusing him of "troubling Muslims". kAnhojI refused, afzal destroyed temples and was himself killed and routed by shivAjI.

## Translated firman (from Farsi)
I BEGIN IN THE NAME OF MERCIFUL AND KIND GOD.  
THE WHOLE WORLD BELONGS TO GOD.  
IMMAM ALI ALI ADILSHA  
son of MAHOMED ADILSHAH.  

This gracious Royal Firman is issued to KANHOJI JEDHE, TO WIT :-  
Since the beginning of the year 1059, Shivaji out of narrow-mindedness and evil propensittes has started troubling the Mahomedans residing in the Province of Konkan belonging to the Nizamshahi. He has also plundered them.  

He has captured many forts in the Padshahi (our) Province; therefore in order to drive him out and conquer him, we have appointed Afzulkhan possessed of valour and prestige, the most capable and efficient of our noblemen, the most vadiant, resourceful and successful Ruler, (the noblest of our chiefs who is always victorious) the Chief Commander, as the Governor of that Province, and we have sent him there with his most valiant army. He has been sent by us. 

You must carry out his commands and fulfil his requirements to his complete satisfaction. You must loyally obey all his commands and help him, so that Shivaji may be driven out and uprooted root and branch. You must not give his men and volunteers, wherever they may be or from wheresoever they may come, any quarter or opportunity - but must kill them. You must give a good account of yourself to this Court and then whatever Afzulkhan may write to us and recommend about rewarding your services and honouring you, will be done by us. Whatever Afzulkhan may say or write regarding our services and whatever he may direct you to do, you will obey implicitly. You should carry out his wishes and this will bring you a good result. You must act according to the orders contained in this Royal 

Firman written on the 5th day of Shavval in the year 1069. (16-6-1659 Julian).
"""

[names]
sa = [ "कान्होजी-प्रलोभनम्",]
