default_to_none = true
id = "varakunda-caturthI"
tags = [ "SpecialPuja",]
shlokas = """
माघशुक्लचतुर्थ्यां तु कुन्दपुष्पैः सदाशिवम्।
सम्पूज्य यो हि नक्ताऽऽशी सम्प्राप्नोति श्रियं नरः॥

सुमन्तुरुवाच---
माघे मासि तथा शुक्ला या चतुर्थी महीपते।
सा शान्ता शान्तिदा नित्यं शान्तिं कुर्यात् सदैव हि॥६॥
स्नानदानादिकं कर्म सर्वमस्यां कृतं विभो।
भवेत्सहस्रगुणितं प्रसादात्तस्य दन्तिनः॥७॥
कृतोपवासो यस्तस्यां पूजयेद्विघ्ननायकम्।
तस्य होमादिकं कर्म भवेत्साहस्रिकं नृप॥८॥
लवणं च गुडं शाकं गुडापूपांश्च भारत।
दत्वा भक्त्या तु विप्रेभ्यः फलं साहस्रिकं भजेत्॥९॥
विशेषतः स्त्रियो राजन् पूजयन्तो गुरुं नृप।
गुडलवणघृतैर्वीर सदा स्युर्भाग्यसंयुताः॥१०॥
(श्रीभविष्ये महापुराणे शतार्धसाहस्र्यां संहितायां ब्राह्मे पर्वणि चतुर्थीकल्पे सुखावहाङ्गारकचतुर्थीव्रतनिरूपणं नामैकत्रिंशोऽध्यायतः) 
"""
references_primary = [ "Nirnaya Sindhu 162",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "puurvaviddha"
month_number = 11
anga_type = "tithi"
anga_number = 4
kaala = "प्रदोषः"
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "शान्ता~वरकुन्द-चतुर्थी",]
