default_to_none = true
id = "pUrNimA~vratam"
tags = [ "MonthlyFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 0
anga_type = "tithi"
anga_number = 15
kaala = "सूर्योदयः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "`pUrNimA vratam` is commonly observed for Lord Satyanarayana."

[names]
sa = [ "पूर्णिमा-व्रतम्",]
