default_to_none = true
id = "pApAGkuzA-EkAdazI"
tags = [ "MonthlyVratam", "EkadashiVratam",]
jsonClass = "HinduCalendarEvent"
shlokas = """
पक्षे पक्षे च कर्तव्यमेकादश्यामुपोषणम्।
यदीच्छेद्विष्णुसायुज्यं श्रियं सन्ततिमात्मनः।
एकादश्यां न भुञ्जीत पक्षयोरुभयोरपि॥

अद्य स्थित्वा निराहारः श्वोभूते परमेश्वर।
भोक्ष्यामि पुण्डरीकाक्ष शरणं मे भवाच्युत॥
प्रमादादथवाऽऽलस्याद्धरे केशव माधव।
व्रतस्यास्य च वै विघ्नो न भवेत्त्वत्प्रसादतः॥
--पद्मपुराणे

एकादश्युपवासफलं प्रोक्तं पाद्ममहापुराणे---
शङ्खोद्धारे नरः स्नात्वा दृष्ट्वा देवं गदाधरम्॥३५॥
एकादश्युपवासस्य कलां नार्हति षोडशीम्।
सङ्क्रान्तिषु चतुर्लक्षं यो ददाति नृपोत्तम॥३६॥
एकादश्युपवासस्य कलां नार्हति षोडशीम्।
प्रभासक्षेत्रे यत्पुण्यं ग्रहणे चन्द्रसूर्ययोः॥३७॥
तत्फलं जायते नूनमेकादश्युपवासिनः।
केदारे चोदकं पीत्वा पुनर्जन्म न विद्यते॥३८॥
तथा चैकादशी पार्थ गर्भवासक्षयङ्करी।
अश्वमेधस्य यज्ञस्य पृथिव्यां यत्फलं लभेत्॥३९॥
तस्माच्छतगुणं पुण्यमेकादश्युपवासिनः।
तपस्विनो गृहे यस्य भुञ्जते च द्विजोत्तमाः॥४०॥
तत्फलं जायते नूनमेकादश्युपवासिनः।
गोसहस्रेण यत्पुण्यं दत्वा वेदान्तपारगे॥४१॥
तस्माच्छतगुणं पुण्यमेकादश्युपवासिनः।
येषां देहे त्रयो देवा ब्रह्मविष्णुमहेश्वराः॥४२॥
वसन्ति तेषां ते तुल्या एकादश्युपवासिनः।
ते नराः पुण्यकर्माणो ये भक्ता हरिपूजकाः॥४३॥
एकादशीव्रतस्यापि पुण्यसङ्ख्या न विद्यते।
एतत्पुण्यं भवेत् तस्य यत्सुरैरपि दुर्लभम्॥४४॥
एकादशीसमं नास्ति व्रतं पापप्रणाशनम्॥११८॥
---श्रीपाद्मे महापुराणे पञ्चपञ्चाशत्साहस्र्यां संहितायामुत्तरखण्डे उमामहेश्वरसंवादे एकादश्युत्पत्ति-मुरवधो नाम चत्वारिंशोऽध्यायः॥४०॥
"""

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = """The Shukla-paksha Ekadashi of `Azvayuja` month is known as `pApAGkuzA-EkAdazI`.

The fruits of fasting on Ekādaśī are greatly extolled in the Padma Purana—

A person who bathes at Śaṃkhoddhāra and beholds the image of Viṣṇu does not acquire even a sixteenth of the merit earned by fasting on Ekādaśī. O noble king, even if one gives four lakhs of coins on the days of the Sun's transition between Zodiac signs, it does not equal even a sixteenth of the merit from an Ekādaśī fast! Indeed, fasting on Ekādaśī grants the same religious merit as bathing at Prabhāsa during a lunar or solar eclipse. One who drinks the sacred water at Kedāra is freed from rebirth, and likewise, fasting on Ekādaśī removes the cycle of rebirth. 

The merit from an Ekādaśī fast is a hundred times greater than the reward of performing an Ashvamedha sacrifice on earth. Fasting on Ekādaśī yields a hundredfold more merit than gifting a thousand cows to a learned brāhmaṇa. Those who fast on Ekādaśī are considered equal to those whose bodies are inhabited by Brahma, Viṣṇu, and Śiva. The merit from observing the Ekādaśī vow is immeasurable, and difficult to obtain even by the Devas. There is no other vow like that of the Ekādaśī, that destroys sins."""

[names]
sa = [ "पापाङ्कुशा-एकादशी",]
