default_to_none = true
id = "kUrma-kalpAdiH"
tags = [ "KalpadiDays",]
shlokas = """
अथ कल्पादयो राजन्कथ्यन्ते तिथयः शुभाः।
यासु श्राद्ध कृते तृप्तिः पितॄणामक्षया भवेत्॥
(३० कल्पादयः प्रदिष्टाः)
---हेमाद्रौ नागरखण्डे
ब्रह्मणो यद्दिनादर्वाक्कल्पस्यादिः प्रकीर्तितः।
वैशाखस्य तृतीयायां कृष्णायां फाल्गुनस्य च॥
पञ्चमी चैत्रमासस्य तस्यैवान्या तथा परा।
शुक्ला त्रयोदशी माघे कार्तिकस्य तु सप्तमी॥
नवमी मार्गशीर्षस्य सप्तैताः संस्मराम्यहम्।
कल्पानामादयो ह्येता दत्तस्याक्षय्यकारकाः॥
---मत्स्यपुराणे
"""
references_primary = [ "Smriti Kaustubham p.87--88",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 1
anga_type = "tithi"
anga_number = 5
kaala = "अपराह्णः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "`kUrma-kalpAdiH` is observed on this day. Performing `zrAddha` on this day gives `akSayatRpti` to `pitr`s. Although there are 30 Kalpadis described in various puranas, 7 of them are particularly special."

[names]
sa = [ "कूर्म-कल्पादिः",]
