default_to_none = true
id = "tirunIlakaNTha_nAyan2mAr_(2)_gurupUjai"
tags = [ "NayanmarGurupujai",]
references_secondary = [ "63 Nayanmar Saints by Swami Sivananda, published by The Divine Life Society",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "sidereal_solar_month"
priority = "paraviddha"
month_number = 10
anga_type = "nakshatra"
anga_number = 16
kaala = "प्रातः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """
Between the 6th and 9th centuries, in South India, there existed 63 ardent devotees of Bhagavan Shiva, collectively known as the Nayanmars. These devout individuals, hailing from various walks of life including potters, fishermen, farmers, merchants, priests, hunters, and washermen, created devotional songs still sung by followers around the globe. Among these Nayanmars, Appar, Sambandar, and Sundarar, known for their Thevaram hymns, along with Manikkavasagar, are distinguished as the Samayacharyas or the ‘The Four’ (`nAlvar`) revered teachers of the faith. They were instrumental in promoting the Shaiva Siddhanta philosophy and culture, effectively challenging the spread of Jainism and Buddhism. Their teachings centered around the concept that Shiva embodies love, and that embracing love for all beings and existence is essential in connecting with Shiva, the Supreme Being.

The 2nd of these Nayanmars was `tirunIlakaNTha nAyan2mAr`, a dedicated devotee of Bhagavan Shiva who lived in Chidambaram, and was a potter by profession. He revered Bhagavan Shiva's devotees and often gifted them with clay begging bowls he crafted, finding great joy in this service.

Tiru Neelakanta Nayanmar worshipped Bhagavan Shiva in his form as Neelakanta, drawing inspiration from the deity's act of consuming poison to protect the world. He believed fervently that those who sought refuge in Bhagavan Shiva would be absolved of their sins and attain His divine abode.

Despite his virtuous life, Neelakanta once succumbed to lust and visited a prostitute. His pious wife discerned this but chose to serve him as usual, resolving privately to abstain from sexual relations with him. When Neelakanta approached her passionately, she swore by Bhagavan Neelakanta and inadvertently used "us" instead of "me." Taking her words to heart and their vow to Bhagavan Shiva, Neelakanta decided never to touch any woman again, a testament to his deep devotion.

The couple lived on, keeping their vow secret. As they aged, Bhagavan Shiva chose to unveil Neelakanta's spiritual greatness. Disguised as a Shiva Yogi, Bhagavan Shiva entrusted Neelakanta with a special bowl, claiming it could purify anything it touched. Later, when Bhagavan Shiva returned for the bowl, he miraculously made it disappear, leading Neelakanta to admit its loss. Accused of theft and unable to touch his wife due to their vow, the situation escalated to a court hearing.

At the court, Neelakanta revealed their secret of celibacy. As they held the ends of a stick and immersed themselves in a tank, a miracle occurred. They emerged youthful and radiant. Bhagavan Shiva and Mother Parvathy then appeared, declaring that due to their self-control and devotion, Neelakanta and his wife would live eternally youthful in the divine abode. This story showcases the power of devotion, celibacy, and the unassuming nature of true virtue.
"""

[names]
ta = [ "tirunIlakaNTha nAyan2mAr (2) gurupUjai",]
