default_to_none = true
id = "kAJcI_18_jagadguru_zrI~yOgatilaka_surEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
दुर्दीदिविं समभिभूय तथाऽस्य साह्यासक्तं च जीवम् अपवार्य सधैर्यम् उक्त्या।
सम्पूजितः सदसि राजसुरेन्द्रमुख्यैः योगी सुरेन्द्रनियमी युयुजे पदे स्वे॥३९॥
महाराष्ट्रः सर्वैरपि च विनुतो माथुर इति प्रपन्नः सन्न्यासं रस-वसु-जलध्यग्निषु (३४८६) कलेः।
दशैवाध्युष्याब्दान् अधिमठम् अयं योगितिलकः सुरेन्द्रः स्वं मार्गे प्रतिपदि सिते प्राप निलयम्॥४०॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-18.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 9
anga_type = "tithi"
anga_number = 1
kaala = "अपराह्णः"
year_start = 3486
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "The austere preceptor Surendra after defeating boldly in debate the materialist Durdhivi and his companion Jīva, being honoured by King Surendra in his Court merged in his original state. Preceptor Surendra, a Maharashtrian, revered by all as Mādhura, resorted to asceticism, an adept in Yogic practices, governed the Maṭha for only ten years and reached his abode on the first day of the bright fortnight in the month of Mārgaśīrṣa of the Tāraṇa year in the Kali era 3486."

[names]
sa = [ "काञ्ची १८ जगद्गुरु श्री-योगतिलक सुरेन्द्र सरस्वती आराधना",]
