default_to_none = true
id = "yama_or_bhrAtR-dvitIyA"
tags = [ "CommonFestivals",]
jsonClass = "HinduCalendarEvent"
shlokas = """
कार्तिके शुक्लपक्षस्य द्वितीयायां युधिष्ठिर।
यमो यमुनया पूर्वं भोजितः स्वगृहे तदा॥१८॥
द्वितीयायां महोत्सर्गे नारकीयाश्च तर्पिताः।
पापेभ्यो विप्रमुक्तास्ते मुक्ताः सर्वे विबन्धना।
भ्रामिता नर्तितास्तुष्टाः स्थिताः सर्वे यदृच्छया॥१९॥
तेषां महोत्सवो वृत्तो यमराष्ट्रे सुखावहः।
ततो यमद्वितीया सा प्रोक्ता लोके युधिष्ठिर॥२०॥
अस्यां निजगृहे पार्थ न भोक्तव्यमतो बुधैः।
स्नेहेन भगिनीहस्ताद्भोक्तव्यं पुष्टिवर्द्धनम्॥२१॥
दानानि च प्रदेयानि भगिनीभ्यो विधानतः।
स्वर्णालंकारवस्त्राद्यैः पूजासत्कारभोजनैः॥२२॥
सर्वा भगिन्यः संपूज्या अभावे प्रतिपत्तिगाः।
पितृव्यभगिनी हस्तात्प्रथमायां युधिष्ठिर॥२३॥
मातुलस्य सुताहस्ताद्वितीयायां पुनर्नृप।
पितृमातृस्वसारौ ये तृतीयायां तयोः करात्॥२४॥
भोक्तव्यं सहजायाश्च भगिन्या हस्ततः परम्।
सर्वासु भगिनीहस्ताद्भोक्तव्यं बलवर्द्धनम्॥२५॥
धन्यं यशस्यमायुष्यं धर्मकामार्थवर्द्धनम्।
व्याख्यातं सकलं स्नेहात्सरहस्यं मया तव॥२६॥
यस्यां तिथौ यमुनया यमराजदेवः
सम्भोजितो जगति सत्त्वरसौहृदेन।
तस्यां स्वसुः करतलादिह यो भुनक्ति
प्राप्नोति वित्तमथ भोज्यमनुत्तमं सः॥२७॥

॥इति श्रीभविष्ये महापुराणे उत्तर-पर्वणि श्रीकृष्णयुधिष्ठिरसंवादे यमद्वितीयाव्रतमाहात्म्यं नाम चतुर्दशोऽध्यायः॥१४॥
"""

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "paraviddha"
month_number = 8
anga_type = "tithi"
anga_number = 2
kaala = "अपराह्णः"
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "यम/भ्रातृ-द्वितीया",]
