default_to_none = true
id = "kAJcI_36_jagadguru_zrI~citsukhAnandEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
ख्यातः सुरेश इति सोमगिरेस्तनूजः क्षीरापगातटभवोऽभवद् आश्रमीन्द्रः।
श्रीचित्सुखेन्द्रचरणानुचरः प्रचारदूरोऽध्युवास मठमेव गुरोर्नियोगात्॥७०॥
श्रीचित्सुखानन्दगुरुः सच्चित्सुखमयं पदम्।
आललम्बे हेमलम्बिन्याश्विने सितपर्वणि॥७१॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-36.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 7
anga_type = "tithi"
anga_number = 15
kaala = "अपराह्णः"
year_start = 3859
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Son of Somagiri, dwelling on the banks of river Pālār (Kṣīrapagā), known as Sureśa, (He) became the preceptor. A disciple of Śrī Citsukhendra, disinterest in campaigns/travels, He, on the directions of his preceptor-teacher, remained in the Maṭha itself. He, the preceptor, Śrī Citsukhānanda attained/ clung on to the state of Bliss on the day of Paurṇamī in the month of Aśvinī of the year Hevilambi. Also known as Cidānanda, He attained siddhi in Kañci itself. His preceptorship was for twenty-one years."

[names]
sa = [ "काञ्ची ३६ जगद्गुरु श्री-चित्सुखानन्देन्द्र सरस्वती आराधना",]
