default_to_none = true
id = "gO-trirAtri-vratam~1"
tags = [ "SpecialVratam",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 6
anga_type = "tithi"
anga_number = 13
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Agastya arghya danam"

[names]
sa = [ "गो-त्रिरात्रि-व्रतम्",]
