default_to_none = true
id = "kAJcI_41_jagadguru_zrI~gaGgAdharEndra_sarasvatI_2_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
अप्पण्णाख्य उमेशभट्टतनयो भीमातटीसम्भवः श्रीविद्यानिरतः श्रितो गुरुपदं श्रीकामकोटीमठे।
पञ्चत्रिंशतम् अध्युवास शरदः श्रीशारदापीठिकां सौम्यः सौम्यनभस्सितप्रतिपदि प्रेयाय गङ्गाधरः॥८४॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-41.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 5
anga_type = "tithi"
anga_number = 1
kaala = "अपराह्णः"
year_start = 4051
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Appanna, son of Umeśabhaṭṭa, on the banks of river Bhīmā, engrossed in Śrīvidyā became preceptor after initiation and remained in KāmakoṭiPīṭha adorning the Śāradāpīṭhikā for thirty-five years. The noble Gaṅgādhara attained siddhi on the pratipad (first day) of bright fortnight in the month Śravaṇa of the year Saumya."

[names]
sa = [ "काञ्ची ४१ जगद्गुरु श्री-गङ्गाधरेन्द्र सरस्वती २ आराधना",]
