default_to_none = true
id = "manvAdiH~(cAkSuSaH~[6])"
tags = [ "ManvadiDays",]
references_primary = [ "`vaidyanAtha-dIkSitIyam`",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 10
anga_type = "tithi"
anga_number = 11
kaala = "अपराह्णः"
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "मन्वादिः-(चाक्षुषः-[६])",]
