default_to_none = true
id = "vaizAkha-pUrNimA-snAnam"
tags = [ "SpecialSnanam",]
references_primary = [ "Satyavrata Smriti",]
references_secondary = [ "Vrata Nirnaya Kalpavalli",]
jsonClass = "HinduCalendarEvent"
shlokas = """
बलं रूपं यशो धर्मं ज्ञानमायुः सुखं धृतिम्।
आरोग्यं परमाप्नोति सम्यक् स्नानेन मानवः॥
भविष्ये---
वैशाखी कार्तिकी माघी ह्याषाढ्यप्यतिपुण्यदाः।
स्नानदानविहीना वै तासु रौरवगामिनः॥
कृत्यसारसमुच्चये---
वैशाखपूर्णिमामभिधाय विष्णुपुराणे---
कृष्णाजिनं तिलान् कृष्णान् हिरण्यं मधुसर्पिषी।
ददाति यस्तु विप्राय सर्वं तरति दुष्कृतम्॥ इति।
अस्यां गङ्गास्नाने ओं अद्येत्यादि गङ्गास्नानजन्यफलसहस्रगुणाधिकफलप्राप्तिकामो गङ्गायां स्नानमहं करिष्ये।
स्मृति-कौस्तुभे---
निर्णयामृते यमगाथासु---
यस्तु कृष्णाजिनं दद्यात्सखुरं शृङ्गसंयुतम्।
तिलैः प्रच्छाद्य वासोभिः सर्वरत्नैरलङ्कृतम्॥
वैशाख्यां पौर्णमास्यां तु विशाखासु विशेषतः।
ससमुद्रगुहा तेन सशैलवनकानना।
सप्तद्वीपान्विता दत्ता पृथिवी नात्र संशयः॥
"""

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "paraviddha"
month_number = 2
anga_type = "tithi"
anga_number = 15
kaala = "प्राक्तनारुणोदयः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Perform snana four ghatikas before sunrise (during `aruNOdayaH`, when the Moon is still up, on the full-moon days of `ASADha`, `kArttika`, `mAgha` and `vaizAkha` – hence the name `A-kA-mA-vai`) bestows strength, beauty, fame, dharma, knowledge, happiness, fortitude and health."

[names]
sa = [ "वैशाख-पूर्णिमा-स्नानम्",]
