default_to_none = true
id = "vasanta-zrI-paJcamI"
tags = [ "SpecialPuja",]
shlokas = """
माघमासे नृपश्रेष्ठ शुक्लायां पञ्चमीतिथौ।
रतिकामौ तु सम्पूज्य कर्तव्यः सुमहोत्सवः॥
"""
references_primary = [ "Smriti Kaustubham 479, Purushartha Chintamani",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 11
anga_type = "tithi"
anga_number = 5
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Worship Mahavishnu and Mahalakshmi, Rati Devi and Manmatha with jasmine flowers."

[names]
sa = [ "वसन्त-श्री-पञ्चमी", "मदन-पञ्चमी",]
