default_to_none = true
id = "dIpOtsava-caturdazI_or_yama-tarpaNam"
tags = [ "CommonFestivals",]
jsonClass = "HinduCalendarEvent"
shlokas = """
दीपोत्सवचतुर्दश्यां कार्यं तु यमतर्पणम्।
कृष्णाङ्गारचतुर्दश्याम् अपि कार्यं सदैव वा॥
कृष्णपक्षे चतुर्दश्याम् अङ्गारकदिनं यदा।
तदा स्नात्वा शुभे तोये कुर्वीत यमतर्पणम्॥
"""

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 7
anga_type = "tithi"
anga_number = 29
jsonClass = "HinduCalendarEventTiming"

[description]
en = """
Perform Tarpana to Yamadharmaraja (even those with father). `jIvatpitA'pi kurvIta tarpaNaM yamabhISmayOH`"
एकैकेन तिलैर्मिश्रान् दद्यात् त्रींस्त्रीन् जलाञ्जलीन्।
संवत्सरकृतं पापं तत्क्षणादेव नश्यति॥
कृष्णपक्षे चतुर्दश्यां यां काञ्चित् सरितं प्रति।
यमुनायां विशेषेण नियतस्तर्पयेद् यमम्॥
यत्र क्वचन नद्यां हि स्नात्वा कृष्णचतुर्दशीम्।
सन्तर्प्य धर्मराजं तु मुच्यते सर्वकिल्बिषैः॥
दक्षिणभिमुखो भूत्वा तिलैः सव्यं समाहितः।
देवतीर्थेन देवत्वात् तिलैः प्रेताधिपो यतः॥

१. यमं तर्पयामि। (त्रिः)
२. धर्मराजं तर्पयामि।
३. मृत्युं तर्पयामि।
४. अन्तकं तर्पयामि।
५. वैवस्वतं तर्पयामि।
६. कालं तर्पयामि।
७. सर्वभूतक्षयं तर्पयामि।
८. औदुम्बरं तर्पयामि।
९. दध्नं तर्पयामि।
१०. नीलं तर्पयामि।
११. परमेष्ठिनं तर्पयामि।
१२. वृकोदरं तर्पयामि।
१३. चित्रं तर्पयामि।
१४. चित्रगुप्तं तर्पयामि।


Perform Japa of the following names—
यमो निहन्ता पितृधर्मराजो वैवस्वतो दण्डधरश्च कालः।
प्रेताधिपो दत्तकृतानुसारी कृतान्तः (एतद् दशकृज्जपन्ति)॥

Perform `namaskAraH`—
नीलपर्वतसङ्काशो रुद्रकोपसमुद्भवः।
कालो दण्डधरो देवो वैवस्वत नमोऽस्तु ते॥
"""

[names]
sa = [ "दीपोत्सव-चतुर्दशी/यम-तर्पणम्",]
