default_to_none = true
id = "yajurvEda-upAkarma"
tags = [ "CommonFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 5
anga_type = "tithi"
anga_number = 15
kaala = "मध्याह्नः"
priority = "paraviddha"
jsonClass = "HinduCalendarEventTiming"

[description]
sa = """

## आपस्तम्बसूत्रेषु
(आर्तव)श्रवणा(पूर्व)पक्ष ओषधीषु जातासु हस्तेन पौर्णमास्यां वा ऽध्यायोपाकर्म।  
अग्नेर् उपसमाधानाद्य्-आज्यभागान्ते ऽन्वारब्धेषु +++(शिष्येषु)+++ काण्ड-ऋषिभ्यो जुहोति,  
सदसस्पतये, सावित्र्या, ऋग्वेदाय यजुर्वेदाय सामवेदायाथर्वणवेदायेति हुत्वा उपहोमो,  
वेदाहुतीनाम् उपरिष्टात् सदसस्पतिम् इत्येके ३
परिषेचनान्तं कृत्वा  

त्रीन् अनुवाकान् आदितो ऽधीयीरन् ४  
प्रथमोत्तमाव् अनुवाकौ वा ५  
त्र्यहम् एकाहं वा क्षम्याधीयीरन् ६  
यथोपाकरणमध्यायः +++(नाम त्रीनध्यायान् अधीयीरन्, प्रथमोत्तमौ वा)+++७
"""

[names]
sa = [ "यजुर्वेद-उपाकर्म",]
