default_to_none = true
id = "daNDiyaDigaL_nAyan2mAr_(31)_gurupUjai"
tags = [ "NayanmarGurupujai",]
references_secondary = [ "63 Nayanmar Saints by Swami Sivananda, published by The Divine Life Society",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "sidereal_solar_month"
priority = "paraviddha"
month_number = 12
anga_type = "nakshatra"
anga_number = 24
kaala = "प्रातः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """Between the 6th and 9th centuries, in South India, there existed 63 ardent devotees of Bhagavan Shiva, collectively known as the Nayanmars. These devout individuals, hailing from various walks of life including potters, fishermen, farmers, merchants, priests, hunters, and washermen, created devotional songs still sung by followers around the globe. Among these Nayanmars, Appar, Sambandar, and Sundarar, known for their Thevaram hymns, along with Manikkavasagar, are distinguished as the Samayacharyas or the ‘The Four’ (`nAlvar`) revered teachers of the faith. They were instrumental in promoting the Shaiva Siddhanta philosophy and culture, effectively challenging the spread of Jainism and Buddhism. Their teachings centered around the concept that Shiva embodies love, and that embracing love for all beings and existence is essential in connecting with Shiva, the Supreme.

In the Chola kingdom's Tiruvarur, there lived a devout worshipper named Dandi Adigal. Born without sight, he continually chanted the Panchaksharam and envisioned the Bhagavan inwardly. He regularly visited the temple for pradakshinam and prayers.

Adigal aspired to expand a temple-side tank, bordered by Jaina residences. Despite his blindness, he resolved to undertake this task, driven by unwavering faith. He ingeniously set up a system with ropes and posts, using them to navigate and execute the digging. His efforts caught the attention of the nearby Jainas, who, envious of his progress, attempted to dissuade him, citing the sin of harming insects during excavation. Undeterred, Adigal confidently asserted that no harm would come to any creature by divine grace. The Jainas, unimpressed, forcefully took his digging tools away.

Heartbroken, Adigal sought solace in the temple, where the Bhagavan appeared in his dream, promising assistance. Simultaneously, the Bhagavan also visited the king in a dream, urging him to address Adigal's troubles. Subsequently, at a royal assembly, Adigal proclaimed his faith in Bhagavan Shiva and declared that divine will could restore his sight while the Jainas might lose theirs. As he emerged from the tank, chanting the holy Panchaksharam, his sight was miraculously restored, and the Jainas were struck blind. Astonished by this divine intervention, the king expelled the Jainas and reinforced the people's faith in the Bhagavan. Dandi Adigal ultimately achieved enlightenment."""

[names]
ta = [ "daNDiyaDigaL nAyan2mAr (31) gurupUjai",]
