default_to_none = true
id = "tirumUla_nAyan2mAr_(30)_gurupUjai"
tags = [ "NayanmarGurupujai",]
references_secondary = [ "63 Nayanmar Saints by Swami Sivananda, published by The Divine Life Society",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "sidereal_solar_month"
priority = "paraviddha"
month_number = 7
anga_type = "nakshatra"
anga_number = 1
kaala = "प्रातः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """Between the 6th and 9th centuries, in South India, there existed 63 ardent devotees of Bhagavan Shiva, collectively known as the Nayanmars. These devout individuals, hailing from various walks of life including potters, fishermen, farmers, merchants, priests, hunters, and washermen, created devotional songs still sung by followers around the globe. Among these Nayanmars, Appar, Sambandar, and Sundarar, known for their Thevaram hymns, along with Manikkavasagar, are distinguished as the Samayacharyas or the ‘The Four’ (`nAlvar`) revered teachers of the faith. They were instrumental in promoting the Shaiva Siddhanta philosophy and culture, effectively challenging the spread of Jainism and Buddhism. Their teachings centered around the concept that Shiva embodies love, and that embracing love for all beings and existence is essential in connecting with Shiva, the Supreme Being.

Tirumula Nayanmar, a revered Shaiva Siddha and one of the eight disciples of Tirunandi Devar, embarked on a journey to meet Agastya Rishi in the Pothia hills. Departing from Kailasa, he visited numerous Shaivite shrines and, upon reaching Tiruvavaduthurai, witnessed a herd of mourning cows beside their deceased herder, Mulan. To comfort the cows, Tirumula Nayanmar transferred his consciousness into Mulan's body, leaving his own physical form in a tree trunk.

Assuming Mulan's role, he herded the cows back to the village, where Mulan's wife, expecting her husband, was surprised by his changed demeanor. Declaring himself a changed person and advising her to seek spiritual liberation, Tirumula Nayanmar distanced himself from her, arousing the village's curiosity. Upon investigation, the villagers acknowledged his spiritual transformation and advised the wife to respect his new path.

Unable to retrieve his original body owing to Bhagavan Shiva's Lila, Tirumula Nayanmar, still in Mulan's form, dedicated himself to composing a seminal work on Shaiva Philosophy at Tiruvavaduthurai. He devoted himself to worshiping the Bhagavan and settled beneath a nearby peepal tree, entering a state of deep meditation. He remained in this state of Samadhi for three millennia. However, each year, he momentarily emerged from this deep meditative state to compose a single verse. Over the span of three thousand years, this process led to the creation of three thousand verses, collectively forming the sacred text known as the Tirumandiram. Having accomplished his divine mission, Tirumula Nayanmar returned to Kailasa."""

[names]
ta = [ "tirumUla nAyan2mAr (30) gurupUjai",]
