default_to_none = true
id = "karkaTa-saGkramaNa-puNyakAlaH"
references_primary = ["Smriti Muktaphalam SVR p. 267"]
tags = [ "SunSankranti", "CommonFestivals",]
shlokas = """
घृतं च क्षीरकुम्भश्च घृतधेनु फलानि च।
श्रावणे श्रीधरप्रीत्यै दातव्यानि विपश्चिता॥
---वामनपुराणे (स्मृतिकौस्तुभम्)
घृतधेनुप्रदानं तु कर्कटे परिशस्यते॥
---स्मृतिकौस्तुभे
सङ्क्रान्तिस्नानाकरणे प्रत्यवायमाह शातातपः—
सूर्यसङ्क्रमणे पुण्ये न स्नायाद्यदि मानवः।
सप्तजन्मसु रोगी स्याद् दुःखभागी च जायते॥
सङ्क्रान्त्यां यानि दत्तानि हव्यकव्यानि मानवैः।
तानि तस्य ददात्यर्कः सप्तजन्मसु निश्चितम्॥
---वैद्यनाथ-दीक्षितीये स्मृतिमुक्ताफले आह्निक-काण्डः (पूर्वभागः)
अतीतानागते पुण्ये द्वे उदग्दक्षिणायने।
त्रिंशत्कर्कटके नाड्यो मकरे विंशतिः स्मृताः॥
या याः सन्निहिता नाड्यस्तास्ताः पुण्यतमाः स्मृताः॥
---वैद्यनाथ-दीक्षितीये स्मृतिमुक्ताफले आह्निक-काण्डः (पूर्वभागः)
"""
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Karkaṭa-Saṅkramaṇa Punyakala.  Perform danam of ghee, milk vessel, \"ghee cow\" and fruits. For `karkaTa-saGkramaNa`, the 30 ghatikas preceding the `saGkramaNa` form a `puNyakAla`; in general, the ghatikas closer to the `puNyakAla` are even more sacred."

[names]
sa = [ "कर्कट-सङ्क्रमण-पुण्यकालः",]
