default_to_none = true
id = "kumbha-ravi-saGkramaNa-viSNupadI-puNyakAlaH"
tags = [ "SunSankranti", "CommonFestivals",]
shlokas = """
कुम्भप्रवेशे दानं तु गवं अम्बु तृणस्य च।
सङ्क्रान्तिस्नानाकरणे प्रत्यवायमाह शातातपः—
सूर्यसङ्क्रमणे पुण्ये न स्नायाद्यदि मानवः।
सप्तजन्मसु रोगी स्याद् दुःखभागी च जायते॥
सङ्क्रान्त्यां यानि दत्तानि हव्यकव्यानि मानवैः।
तानि तस्य ददात्यर्कः सप्तजन्मसु निश्चितम्॥
(स्मृतिमुक्ताफले आह्निक-काण्डे-पूर्वभागः)
"""
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Kumbha-Ravi-Saṅkramaṇa-Viṣṇupadī Punyakala. Perform danam of hay, grass, food and pure water to cows."

[names]
sa = [ "कुम्भ-रवि-सङ्क्रमण-विष्णुपदी-पुण्यकालः",]
