default_to_none = true
id = "kazhar2ir2r2ar2ivAr_or_cEramAn2_perumAL_nAyan2mAr_(37)_gurupUjai"
tags = [ "NayanmarGurupujai",]
references_secondary = [ "63 Nayanmar Saints by Swami Sivananda, published by The Divine Life Society",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "sidereal_solar_month"
priority = "paraviddha"
month_number = 4
anga_type = "nakshatra"
anga_number = 15
kaala = "प्रातः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """Between the 6th and 9th centuries, in South India, there existed 63 ardent devotees of Bhagavan Shiva, collectively known as the Nayanmars. These devout individuals, hailing from various walks of life including potters, fishermen, farmers, merchants, priests, hunters, and washermen, created devotional songs still sung by followers around the globe. Among these Nayanmars, Appar, Sambandar, and Sundarar, known for their Thevaram hymns, along with Manikkavasagar, are distinguished as the Samayacharyas or the ‘The Four’ (`nAlvar`) revered teachers of the faith. They were instrumental in promoting the Shaiva Siddhanta philosophy and culture, effectively challenging the spread of Jainism and Buddhism. Their teachings centered around the concept that Shiva embodies love, and that embracing love for all beings and existence is essential in connecting with Shiva, the Supreme Being.

Cheraman Perumal Nayanmar, born as Perum-Ma-Kothayar in Kodunkolur, capital of Malai Nadu (now Kerala), was from the royal Kothayars family. His deep devotion to Bhagavan Shiva flourished with age, leading him to renounce the world for a spiritual life in Tiru Anchaikalam. However, upon the abdication of Sengol Porayan, the king with no heir, Cheraman reluctantly accepted rulership following divine approval, ruling justly and wisely.

Cheraman's profound devotion led to a divine encounter where he revered a washerman smeared in white, seeing in him an image of Bhagavan Shiva. This act of supreme devotion stunned onlookers. Bhagavan Shiva later sent musician Banapatirar with a palm leaf praising Cheraman’s devotion. Overwhelmed, Cheraman offered his kingdom to Banapatirar, who modestly accepted only what he needed.

Cheraman's devotion to Bhagavan Nataraja was so intense that he daily heard the divine sound of the Bhagavan's anklets. Distressed one day by its absence, fearing he had erred, he contemplated suicide but was reassured by a divine voice explaining the delay due to Bhagavan Shiva's absorption in Sundarar's hymns. Eager to meet Sundarar and worship Bhagavan Nataraja, Cheraman journeyed to Tillai, where he was enraptured by the Bhagavan's presence.

In Tiruvarur, Cheraman finally met and befriended Sundarar. Together, they traveled, visiting various shrines and composing hymns. After Sundarar attained liberation in Tiru Anchaikalam, Cheraman, sensing his friend's departure, also attained the divine abode, where he became chief of Bhagavan Shiva's ganas."""

[names]
ta = [ "kazhar2ir2r2ar2ivAr/cEramAn2 perumAL nAyan2mAr (37) gurupUjai",]
