default_to_none = true
id = "nRsiMha~jayantI"
tags = [ "Dashavataram", "CommonFestivals",]
jsonClass = "HinduCalendarEvent"
shlokas = """
सत्यं विधातुं निजभृत्यभाषितं
व्याप्तिं च भूतेष्वखिलेषु चात्मनः।
अदृश्यतात्यद्भुतरूपमुद्वहन्
स्तम्भे सभायां न मृगं न मानुषम्॥७-८-१७॥
---श्रीमद्भागवते सप्तमस्कन्धेऽष्टमोऽध्यायः
वैशाखे शुक्लपक्षे तु चतुर्दश्यामिनेऽस्तगे।
उद्बभूवासुरद्वेषी नृसिंहो भक्तवत्सलः॥
अवतारदिने पुण्ये हरिमुद्दिश्य भक्तितः।
उपवासादि यत् किञ्चित्तदानन्त्याय कल्पते॥
"""
references_primary = [ "Vaidyanatha Dikshitiyam (SVR) p.62",]

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "puurvaviddha"
month_number = 2
anga_type = "tithi"
anga_number = 14
kaala = "सूर्यास्तमयः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Monday Swati?"

[names]
sa = [ "नृसिंह-जयन्ती",]
