default_to_none = true
id = "kAJcI_32_jagadguru_zrI~cidAnandaghanEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
अण्णु(कण्व)शङ्करनन्दनः पटुपद्मनाभसमाह्वयो
लम्बिकापथतत्परोऽप्यवलम्ब्य सद्गुरुशासनम्।
कामकोटिपदे स्थितः श्रितकामकोटिफलप्रदे
नित्यदत्तसहस्रभक्तम् अभूद् इदं पदभागसौ॥६१॥
सकरुणम् अपबन्धुं कन्नडेशीकुमारं
पुनरपि निजराज्ये स्थापयंस्तद्विजेत्रा।
अतिलघुतनुवृत्तिर्जीर्णपर्णात् स योगी
पदमनु चतुरोऽब्दानेव देवोऽध्यवात्सीत्॥६२॥
प्रजोत्पत्तौ मार्गशीर्षे सितषष्ठ्याम् अगाद् असौ।
पदं स्वं परमं सर्वशोकमोहविवर्जितम्॥६३॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-32.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 9
anga_type = "tithi"
anga_number = 6
kaala = "अपराह्णः"
year_start = 3773
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Son of Kaṇṇūśaṅkara, the clever Padmanābha by ame, though intent on practising Lambika Yoga, this preceptor Cidānandaghanendra adhering to the injunctions of the Master, remained in the seat of Kāmakoṭi that bestows all desired things to those who resort to, fed innumerable devotees every day. He, the adept in Yoga reinstating compassionately the Kannada prince who lost kith and kin in his own kingdom through his (the prince’s) conqueror, He (Cidānandaghanendra) remained as preceptor only for four years sustaining on dry leaves. This preceptor reached his Ultimate abode which is devoid of all grief, delusion etc. on the sixty day of bright fortnight in the month of Mārgaśīrṣa of the year Prajotpati."

[names]
sa = [ "काञ्ची ३२ जगद्गुरु श्री-चिदानन्दघनेन्द्र सरस्वती आराधना",]
