default_to_none = true
id = "vidyAraNya~svAmI~ArAdhanA"
tags = [ "MahapurushaEvents",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 3
anga_type = "tithi"
anga_number = 13
year_start = 4493
year_start_era = "kali"
priority = "vyaapti"
kaala = "अपराह्णः"
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "विद्यारण्य-स्वामि-आराधना",]
