default_to_none = true
id = "kulaccir2ai_nAyan2mAr_(22)_gurupUjai"
tags = [ "NayanmarGurupujai",]
references_secondary = [ "63 Nayanmar Saints by Swami Sivananda, published by The Divine Life Society",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "sidereal_solar_month"
priority = "paraviddha"
month_number = 5
anga_type = "nakshatra"
anga_number = 17
kaala = "प्रातः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """
Between the 6th and 9th centuries, in South India, there existed 63 ardent devotees of Bhagavan Shiva, collectively known as the Nayanmars. These devout individuals, hailing from various walks of life including potters, fishermen, farmers, merchants, priests, hunters, and washermen, created devotional songs still sung by followers around the globe. Among these Nayanmars, Appar, Sambandar, and Sundarar, known for their Thevaram hymns, along with Manikkavasagar, are distinguished as the Samayacharyas or the ‘The Four’ (`nAlvar`) revered teachers of the faith. They were instrumental in promoting the Shaiva Siddhanta philosophy and culture, effectively challenging the spread of Jainism and Buddhism. Their teachings centered around the concept that Shiva embodies love, and that embracing love for all beings and existence is essential in connecting with Shiva, the Supreme Being.

Kulacchirai Nayanmar, the 22nd of the Nayanmars, was a great devotee of Bhagavan Shiva and His followers. He lived in Manamerkudi, a town in the Pandyan kingdom known for its many Shiva devotees. Kulacchirai Nayanmar was the leader of the town and was very wealthy, but he considered himself a servant of the Shiva Bhaktas. He even saw them as equals to Bhagavan Shiva Himself.

Kulacchirai Nayanmar was also a skilled soldier and administrator, but his mind was always focused on the Bhagavan. He played a key role in helping the queen of the Pandyan kingdom defeat the influence of Jainism. He invited the famous Nayanmar Sambandar to Madurai to help in this effort.

The Jains tried to stop Sambandar by setting fire to his camp, but he extinguished the fire with a song. They also tried to cure the Pandyan king's high fever, but only Sambandar's sacred ash was able to heal him. Finally, Sambandar defeated the Jains in a debate, and Kulacchirai Nayanmar had sent them to the gallows, as per the terms of the debate.

After serving the Shiva Bhaktas for many years, Kulacchirai Nayanmar eventually attained liberation and reached Shiva's abode.
"""

[names]
ta = [ "kulaccir2ai nAyan2mAr (22) gurupUjai",]
