default_to_none = true
id = "cidambarE_rajata_candraprabha_vAhanam"
tags = [ "TamilnaduTempleFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
anchor_festival_id = "naTarAjar_An2i_tirumaJcan2am"
offset = -8
jsonClass = "HinduCalendarEventTiming"

[description]
en = "The Brahmotsavam of Nataraja at Chidambaram happens specially around the Aani Thirumanjana festival each year, for ten days. On this day, Nataraja gives darshan with a silver 'chandra prabha' vahanam."

[names]
sa = [ "चिदम्बरे रजत चन्द्रप्रभ वाहनम्",]
