default_to_none = true
id = "kAri_nAyan2mAr_(48)_gurupUjai"
tags = [ "NayanmarGurupujai",]
references_secondary = [ "63 Nayanmar Saints by Swami Sivananda, published by The Divine Life Society",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "sidereal_solar_month"
priority = "paraviddha"
month_number = 11
anga_type = "nakshatra"
anga_number = 20
kaala = "प्रातः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """Between the 6th and 9th centuries, in South India, there existed 63 ardent devotees of Bhagavan Shiva, collectively known as the Nayanmars. These devout individuals, hailing from various walks of life including potters, fishermen, farmers, merchants, priests, hunters, and washermen, created devotional songs still sung by followers around the globe. Among these Nayanmars, Appar, Sambandar, and Sundarar, known for their Thevaram hymns, along with Manikkavasagar, are distinguished as the Samayacharyas or the ‘The Four’ (`nAlvar`) revered teachers of the faith. They were instrumental in promoting the Shaiva Siddhanta philosophy and culture, effectively challenging the spread of Jainism and Buddhism. Their teachings centered around the concept that Shiva embodies love, and that embracing love for all beings and existence is essential in connecting with Shiva, the Supreme Being.

Kari Nayanmar, the 48th of the Nayanmars, hailed from Tirukadavur, and was a learned Tamil scholar. He regularly visited the three Tamil kings, earning a substantial amount of money through his recitations of Tamil Kovais (anthologies). Utilising his earnings, he constructed temples, actively promoting Shaivism. Furthermore, he dedicated himself to serving devotees of Bhagavan Shiva, garnering him the Bhagavan's divine grace."""

[names]
ta = [ "kAri nAyan2mAr (48) gurupUjai",]
