default_to_none = true
id = "zrIvinAyaka-caturthI"
tags = [ "CommonFestivals",]
jsonClass = "HinduCalendarEvent"
shlokas = """
सुमन्तुरुवाच--- 
शिवा शान्ता सुखा राजंश्चतुर्थी त्रिविधा स्मृता। 
मासि भाद्रपदे शुक्ला शिवा लोकेषु पूजिता॥१॥ 
तस्यां स्नानं तथा दानमुपवासो जपस्तथा। 
क्रियमाणं शतगुणं प्रसादाद्दन्तिनो नृप॥२॥ 
गुडलवणघृतानां तु दानं शुभकरं स्मृतम्। 
गुडापूपैस्तथा वीर पुण्यं ब्राह्मणभोजनम्॥३॥ 
यास्तस्यां नरशार्दूल पूजयन्ति सदा स्त्रियः। 
गुडलवणपूपैश्च श्वश्रूं श्वशुरमेव च॥४॥ 
ताः सर्वाः सुभगाः स्युर्वै विघ्नेशस्यानुमोदनात्। 
कन्यका तु विशेषेण विधिनाऽनेन पूजयेत्॥५॥ 
---श्रीभविष्ये महापुराणे शतार्धसाहस्र्यां संहितायां ब्राह्मे पर्वणि चतुर्थीकल्पे सुखावहाङ्गारकचतुर्थीव्रतनिरूपणं नामैकत्रिंशोऽध्यायतः
अस्यामेव चन्द्रदर्शने दोषमाह पराशरः--- 
कन्यादित्ये चतुर्थ्यां च शुक्ले चन्द्रस्य दर्शनम्। 
मिथ्याभिदूषणं कुर्यात् तस्मात्पश्येन्न तं सदा॥ 
तद्दोषशान्तये मन्त्रो विष्णुपुराणे--- 
सिहः प्रसेनमवधीत्सिहो जाम्बवता हतः। 
सुकुमारक मा रोदीस्तव ह्येषः स्यमन्तकः॥
"""

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "puurvaviddha"
month_number = 6
anga_type = "tithi"
anga_number = 4
kaala = "मध्याह्नः"
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "श्रीविनायक-चतुर्थी",]
