default_to_none = true
id = "nAga-paJcamI"
tags = [ "SpecialPuja", "PuranaEvents",]
shlokas = """
सुमन्तुरुवाच
इत्युक्तवान्पुरा वीर गौतमस्य प्रजापतिः।
लक्षणं सर्वनागानां रूपवर्णों विषं तथा॥६०॥
तस्मात् सम्पूजयेन्नागान् सदा भक्त्या समन्वितः।
विशेषतस्तु पञ्चम्यां पयसा पायसेन च॥६१॥
श्रावणे मासि पञ्चम्यां शुक्लपक्षे नराधिप।
द्वारस्योभयतो लेख्या गोमयेन विषोल्बणाः॥६२॥
पूजयेद्विधिवद्द्वारं दधिदूर्वाक्षतैः कुशैः।
गन्धपुष्पोपहारैश्च ब्राह्मणानां च तर्पणैः॥६३॥
ये त्वस्यां पूजयन्तीह नागान् भक्तिपुरःसराः।
न तेषां सर्पतो वीर भयं भवति कर्हिचित्॥६४॥
॥इति श्रीभविष्ये महापुराणे शतार्धसाहस्र्यां संहितायां ब्राह्मेपर्वणि पञ्चमीकल्पे श्रावणिकनागपञ्चमीव्रतवर्णनं नाम षट्त्रिंशोऽध्यायः॥
अपसर्प सर्प भद्रं ते दूरं गच्छ महायशाः।
जनमेजयस्य यज्ञान्ते अस्तीकवचनं स्मरन्॥
"""
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 5
anga_type = "tithi"
anga_number = 5
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Naga Panchami; SarpaPooja (manasaDevi); Vishnu's boon to AdiSesha that humans will worship on this day"

[names]
sa = [ "नाग-पञ्चमी",]
