default_to_none = true
id = "kAJcI_60_jagadguru_zrI~advaitAtmaprakAzEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
अथ वसिष्ठनदीतटसम्भवः परशुरामसुतः श्रुतिपण्डितः।
अचकलद् गुरुराजधुरां गुरोर्वचनतो रचयन् परितोऽटनम्॥
आत्मप्रकाशेन्द्रसमाख्ययाऽसावाचार्यकं द्वादशवर्षम् आर्च्छत्।
गोविन्दनामा नियतः स्वभानुचैत्रद्वितीयानिशि सिद्धिमापत्॥१४॥
—पुण्यश्लोकमञ्जरी परिशिष्टम्
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-60.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 1
anga_type = "tithi"
anga_number = 17
kaala = "अपराह्णः"
year_start = 4805
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Then, son of Paraśurāma on the banks of river Vaśiṣṭha, well-versed in scriptures, touring all around bore the burden (or preceptor) on him. This sage by name Govinda with the appellation Ātmaprakāśendra carried out the responsibilities of preceptor for twelve years. He attained siddhi on the second day of Kṛṣṇapakṣa in the month Caitra of the year Svabhānu. This preceptor remained in Shahajipuram for a long period hailed as Govindajagadguru by Śrīdhara Veṅkateśa and other learned men."

[names]
sa = [ "काञ्ची ६० जगद्गुरु श्री-अद्वैतात्मप्रकाशेन्द्र सरस्वती आराधना",]
