default_to_none = true
id = "tiruccendUr_murugan2_mAcit_tiruvizhA_##7##m_nAL—urugu_cattac_cEvai_or_cigappu_cAtti_alaGkAram"
tags = [ "TamilnaduTempleFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
anchor_festival_id = "tiruccendUr_mAcit_tiruvizhA_nir2aivu"
offset = -5
jsonClass = "HinduCalendarEventTiming"

[description]
en = "The Tiruchendur Brahmotsavam of Masi each year is very special, wherein all the three temple chariots are dragged and the festival is conducted for twelve days, concluding with a Teppam or Float Festival. This marks the seventh day of the festival. A unique decoration on this day is the 'urugu chattai' sevai, and 'sigappu satthi alankaram'."

[names]
ta = [ "tiruccendUr murugan2 mAcit tiruvizhA ##7##m nAL—urugu cattac cEvai/cigappu cAtti alaGkAram",]
