default_to_none = true
id = "bhRgurEvatI-puNyakAlaH"
tags = [ "RareDays", "Combinations", "AmritaSiddhiYogaDays",]
shlokas = """
आदित्यहस्ते गुरुपुष्ययोगे बुधानुराधा शनिरोहिणी च।
सोमे च सौम्यं भृगुरेवती च भौमाश्विनी चामृतसिद्धियोगाः॥
"""
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
jsonClass = "HinduCalendarEventTiming"

[description]
en = """
When Revati nakshatra falls on a Friday, it is a special `puNyakAlaH`. When Rohini nakshatra falls on a Saturday, it is a special `puNyakAlaH`. In the cyclic rotation of time, along with the bad combinations of grahas and nakshatras that indicate the probability of upcoming difficulties, good combinations that grant benefits in multiples also arise. Among such good combinations are the Amrita Siddhi yogas of certain weekdays and nakshatras. They are Sunday-Hasta, Monday-Mrigashirsha, Tuesday-Ashvini, Wednesday-Anuradha, Thursday-Pushya, Friday-Revati, Saturday-Rohini. Good deeds performed on such yogas become especially strong in protecting and nourishing us.
For instance, in Devi Atharvashirsha, it is said `bhaumAzvinyAM mahAdevI-sannidhau japtvA mahAmRtyuM tarati`, that is, one can cross even `mahAmRtyu` by doing parayanam when Tuesday and Ashvini join.
"""

[names]
sa = [ "भृगुरेवती-पुण्यकालः",]
