default_to_none = true
id = "kAJcI_35_jagadguru_zrI~citsukhEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
वेदाचलान्तिकभवो विमलाक्षनाम्नः सूनुः सुशीलकमलाक्ष इति प्रसिद्धः।
संयम्य चित्सुखतनुः श्रितकामकोटीपीठाधिपत्यविभवोऽप्यवसत् स सह्ये॥६८॥
चित्सुखानन्दयोगीन्द्रं निवेश्य निजविष्टरे।
सर्वात्मना तिरोऽधात् स धात्वाषाढाच्छषष्ठ्यहे॥६९॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-35.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 4
anga_type = "tithi"
anga_number = 6
kaala = "अपराह्णः"
year_start = 3838
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Born near the Vedāchala mountain as the son of Vimalākṣa and well-known as Suśīlakamalākṣa, after renunciation became Citsukha; having had the authority of the preceptorship of Kāñci, He lived in the caves of Sahya mountain. He, having installed/deputed Citsukhānanda Yogīndra in his place, vanished fully on the sixth day of the bright fortnight of the month of Āṣāḍha of the year Dhātu. His preceptorship was for twenty-seven years."

[names]
sa = [ "काञ्ची ३५ जगद्गुरु श्री-चित्सुखेन्द्र सरस्वती आराधना",]
