default_to_none = true
id = "sarasvatI-AvAhanam"
tags = [ "CommonFestivals",]
shlokas = """
अथवा  मूलनक्षत्रे  समारभ्य  प्रपूजयेत्।
तत्राप्यशक्तो  विप्रेन्द्रो  नवम्यां  तु  प्रपूजयेत्॥
नाऽध्यापयेन्न  च  लिखेन्नाऽधीयीत  कदाचन।
पुस्तके  स्थापिते  देवीं  विद्याकामो  द्विजोत्तमः॥
"""
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "puurvaviddha"
month_number = 7
anga_type = "nakshatra"
anga_number = 19
kaala = "मध्याह्नः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Being `mUlA` nakshatra, it is another ideal day to begin Saraswati Puja. If not, at least perform on Navami. During the Saraswati Puja days, those desirous of obtaining knowledge must not teach, learn or write anything!"

[names]
sa = [ "सरस्वती-आवाहनम्",]
