default_to_none = true
id = "kaliya_nAyan2mAr_(44)_gurupUjai"
tags = [ "NayanmarGurupujai",]
references_secondary = [ "63 Nayanmar Saints by Swami Sivananda, published by The Divine Life Society",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "sidereal_solar_month"
priority = "paraviddha"
month_number = 4
anga_type = "nakshatra"
anga_number = 18
kaala = "प्रातः"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """Between the 6th and 9th centuries, in South India, there existed 63 ardent devotees of Bhagavan Shiva, collectively known as the Nayanmars. These devout individuals, hailing from various walks of life including potters, fishermen, farmers, merchants, priests, hunters, and washermen, created devotional songs still sung by followers around the globe. Among these Nayanmars, Appar, Sambandar, and Sundarar, known for their Thevaram hymns, along with Manikkavasagar, are distinguished as the Samayacharyas or the ‘The Four’ (`nAlvar`) revered teachers of the faith. They were instrumental in promoting the Shaiva Siddhanta philosophy and culture, effectively challenging the spread of Jainism and Buddhism. Their teachings centered around the concept that Shiva embodies love, and that embracing love for all beings and existence is essential in connecting with Shiva, the Supreme Being.

Kaliya Nayanmar, a resident and oil merchant of Tiruvotriyur, was known for his deep devotion to Bhagavan Shiva, particularly expressed through his daily service of lighting lamps in the temple. Initially affluent, he faced a dramatic turn of fortune when the Bhagavan, to demonstrate Kaliya Nayanmar's unwavering faith, led him into poverty. This sudden change in his circumstances also brought about a lack of support from his family.

In his commitment to continue his service to the Bhagavan, Kaliya Nayanmar resorted to manual labour to earn enough to buy oil for the temple lamps. However, as his situation worsened, even this means became unfeasible. Driven to desperation, he considered selling his wife, but this plan too did not materialise, as no one was willing to buy her. Facing utter despair and determined to fulfill his service, Kaliya Nayanmar contemplated using his own blood as a substitute for the oil to keep the temple lamps burning! At this poignant moment of self-sacrifice, Bhagavan Shiva intervened, stopping Kaliya Nayanmar from harming himself, and blessed him, acknowledging his profound devotion and selfless service."""

[names]
ta = [ "kaliya nAyan2mAr (44) gurupUjai",]
