id = "tArApura-durga-jayaH"
jsonClass = "HinduCalendarEvent"

[timing]
month_type = "gregorian"
anga_type = "day"
month_number = 2
anga_number = 3
year_start = 1739
year_start_era = "gregorian"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """
Marathas captured Tarapur fort. Congratulations poured on Chimaji Appa! Khandoji Mankar and other Maratha commanders and unit of artillery fired shots to celebrate the victory! After the fall of Tarapur on 3 Feb 1739 Chimaji Appa immediately sent force of 4000 infantry & 5000 cavalry to capture Asheri under Haripant.

Marathas employed 30 cannons against the fort and made heavy bombardment on the fort resulting in damages to the fortification. But, Portuguese continued their defence. The Marathas, seeing no sign of Portuguese surrender, decided to mine the fort. Baji Bhivrao, Ramchandra Hari, Baloji Chandrao, *Malharrao Holkar, Ranoji Shinde*, Yashwantrao Pawar were the prominent Maratha Sardars in this action. Finally the mines exploded resulting in destruction of fort & bastion, allowing Marathas to enter the Fort! 

Baji Bhivrao Retrekar, a leading Maratha commander of Peshwa Bajirao I led the attack from the front, when a bullet struck in his mouth & he was killed. Baji Bhivrao Retrekar was considered 'own brother' by Peshwa Bajirao in a letter. The Portuguese Captain of Tarapore Luiz  Veleso Machado also died while fighting. There were many Portuguese women in the fort who were made captive but Chimaji gave them very decent treatment, according to a Portuguese chronicler.

Context: Asheri Fort, another strategically important fort, is in Palghar district (Maharashtra). Asheri was sieged by Maratha Commander Pantaji Moreshwar. But Portuguese held onto the fort because they were gaining enough supplies from Tarapur outpost. Unless Tarapur was captured, Asheri was difficult to capture.

"""

[names]
sa = [ "तारापुर-दुर्ग-जयः",]
