default_to_none = true
id = "zravaNa-vratam"
tags = [ "SpecialVratam",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "sidereal_solar_month"
month_number = 0
anga_type = "nakshatra"
anga_number = 22
kaala = "साङ्गवः"
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "श्रवण-व्रतम्",]
