default_to_none = true
id = "sidereal_solar_month_amAvAsyA"
tags = [ "MonthlyShraddhaDays", "ShannavatiTarpanaDays",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "sidereal_solar_month"
priority = "vyaapti"
month_number = 0
anga_type = "tithi"
anga_number = 30
kaala = "अपराह्णः"
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "अमावास्या",]
