id = "avrangazebaH_paNDharapura-mandiram_anAshayat"
jsonClass = "HinduCalendarEvent"

[timing]
month_type = "julian"
anga_type = "day"
month_number = 1
anga_number = 2
year_start = 1705
year_start_era = "gregorian"
jsonClass = "HinduCalendarEventTiming"

[description]
en = """
Entry from court akhbAr 1116-09-17 Ramaḍān. Aurangzeb halted at Pandharpur. That night Khwaja Mohammed Shah Mohtasib reported that there is a temple at Pandharpur and hindus from the army are crowding and worshipping idols there. The emperor ordered that the temple be demolished and butchers from the army should go to the temple site and slaughter cows. Muhammad Ishaq son of Tarbiyat khan bahadur should disperse the crowds. The emperors orders were duly carried out.

Original: दर शब ख्वाजा मुहम्मद शाह मुहतसीब ब-अर्ज रसानीद दर मौजे पंदरपूर बुतखाने अस्त. मरदूमे हुनुदान लष्करे माली हुजुम व बुतपरस्ती मी नूमायद. चुनांचे मुहम्मद खलील व खिदतमतराय दारुगा इ बेलदारान मुहम्मद आमीन  रा ब-हुजूर तलबीदा फर्मुदंद के निज बुतखाना रा मिस्मार नूमायंद व कसायान इ लष्कर रा दर बुतखाने ब-रवद गावान हलाल बकुनानद . मुहम्मद इसहाक पिसर इ तरबियत खान बहादूर रफ्ते हुजुम दूर नुमायद चुनांचे ब-अमल आमद.
"""

[names]
sa = [ "अवरङ्गज़ेबः पण्ढरपुरमन्दिरम् अनाशयत्",]
