default_to_none = true
id = "pancha-parva-3"
tags = [ "Pancha Parva"]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "paraviddha"
month_number = 0
anga_type = "tithi"
anga_number = 23
kaala = "आश्विनः"
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "पञ्च-पर्व-पूजा (अष्टमी)",]
