default_to_none = true
id = "kRSi-pUrNimA"
tags = [ "LessCommonFestivals", "DanamDays",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 3
anga_type = "tithi"
anga_number = 15
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Danam of Padma Puranam. Also widely celebrated by farmers."

[names]
sa = [ "कृषि-पूर्णिमा",]
