default_to_none = true
id = "kAJcI_69_jagadguru_zrI~jayEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays", "CommonFestivals",]
shlokas = ""
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 12
anga_type = "tithi"
anga_number = 13
kaala = "अपराह्णः"
year_start = 5119
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = ""

[names]
sa = [ "काञ्ची ६९ जगद्गुरु श्री-जयेन्द्र सरस्वती आराधना",]
