default_to_none = true
id = "kAJcI_26_jagadguru_zrI~prajJAghanEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
प्रभाकरस्यात्मभवः पिनाकिनीतटीभवः शोणगिरिर्जगद्गुरुः।
स्वभानुवैशाखसिताष्टमीनिशि प्रज्ञाघनः प्राप परं पदं मुदा॥५५॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-26.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 2
anga_type = "tithi"
anga_number = 8
kaala = "अपराह्णः"
year_start = 3665
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Śoṇagiri, son of Prabhākaraśarma, who lived on the banks of river Pinākinī, became Jagadguru Prajñāghana and attained blissful state on the night of the eighth day of the bright fortnight of the month of Vaiśāka in the year Subhānu/Svabhānu."

[names]
sa = [ "काञ्ची २६ जगद्गुरु श्री-प्रज्ञाघनेन्द्र सरस्वती आराधना",]
