jsonClass = "HinduCalendarEvent"
default_to_none = true
id = "ta__tiruccendUr murugan2 AvaNit tiruvizhA ##3##m nALâ€”murugan2 bhavan2i"
script_priority = "ta"
tags = [ "TamilnaduTempleFestivals",]

[timing]
jsonClass = "HinduCalendarEventTiming"
default_to_none = true
anchor_festival_id = "ta__tiruccendUr AvaNit tiruvizhA nir2aivu"
offset = -9
