default_to_none = true
id = "kAJcI_15_jagadguru_zrI~gaGgAdharEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
सूनुर्भद्रगिरेः सुभद्र इति यः काञ्च्य(कप्य?)न्वयो द्वादशे
वर्षे संयमम् आश्रितोऽनुचरिताद् आचार्यविद्याघनात्।
श्रीगङ्गाधरगीष्पतिः स च चतुर्विंशे वयस्यात्मवित्
श्रीविद्याशिवयोर्निरन्तरधृतेराप्नोत् पदं शाश्वतम्॥३०॥
सर्वधारिणि स सर्वधारकश्चित्रशक्तिरधिचैत्रम् अर्जुने।
अर्जुनः स्वयशसाऽऽदिमे दिनेऽनादिधाम महसा जगाम ह॥३१॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-15.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 1
anga_type = "tithi"
anga_number = 1
kaala = "अपराह्णः"
year_start = 3430
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "Gaṅgādharagīṣpatiḥ, known as Subhadra, son of Kāñci Bhadragiri, got initiated in the twelfth year of age by Śrī Vidyāghana whom He had served became a realised soul when He as twenty-four years old and reached the eternal abode of Śrīvidyā and Śrī Śiva. He, the Omnipotent, omniscient and pure reached the eternal abode by his glory on the first day of the bright fortnight in the month of Caitra of the year Sarvadhari."

[names]
sa = [ "काञ्ची १५ जगद्गुरु श्री-गङ्गाधरेन्द्र सरस्वती आराधना",]
