default_to_none = true
id = "kAJcI_52_jagadguru_zrI~zaGkarAnandEndra_sarasvatI_ArAdhanA"
tags = [ "KanchiAradhanaDays",]
shlokas = """
आदिश्याष्ट यमीश्वरान् समवितुं कर्णाटदेशेऽद्वयं
रोद्धुं सायणमाधवोक्तविधया वृद्धिं च मध्वाध्वनाम्।
विद्यातीर्थगुरोरसोढविरहोऽप्यावृत्य शीताचलात्
तस्योक्तेर्बिभराम्बभूव स धुरां श्रीकामकोटीमठे॥१०२॥
श्रीमध्यार्जुनभालचन्द्रमखिराट्सूनुर्महेशाह्वयो
विद्यातीर्थपदान्नियम्य समयेष्वद्वैतमुद्द्योतयन्।
अध्यास्त प्रतिकामकोटि शरदो द्वात्रिंशतं देहिनां
द्वैतध्वान्तनिवारणो नवमठीनाथो नवः शङ्करः॥१०३॥
स दुर्मुखिनि सन्मुखो मधुरवाङ्मधौ मौनिराट्
पदी प्रतिपदि प्रगे प्रसितधीः सिते पक्षके।
समस्तभुवनार्चितः सकृद् उमेशयन् अच्युतं
जहौ तनुमनुत्तमाम् अविशद् आशु नैजं महः॥१०४॥
—पुण्यश्लोकमञ्जरी
"""
image = "mahApuruSha/kAnchI-maTha/images/jagadgurus/jagadguru-52.jpg"
references_primary = [ "Punya Shloka Manjari",]
references_secondary = [ "www.kamakoti.org",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
priority = "vyaapti"
month_number = 1
anga_type = "tithi"
anga_number = 1
kaala = "अपराह्णः"
year_start = 4518
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[description]
en = "He, as per the suggestions of the Sāyaṇa Mādhava, having commissioned the eight saints disciples to protect the tenets of Advaita and to check the development of the faith of Madhva in Karnataka, despite the unbearable separation from the master preceptor Vidyātīrtha, returned from Himalayas and under his (master’s) directions held the responsibilities of the Kāmakoṭi Maṭha. Son of Balacandra Makhi of Madhyārjuna, by name Maheśa (before initiation), having received initiation into asceticism from Vidyātīrtha, popularising among people Advaita among the systems and dispelling the ignorance caused by dvaita, the head of nine Maṭhas, the Navaśaṅkara, headed the Kāmakoṭi Pīṭha for thirty-two years. He the pleasing one, the great preceptor with a sweet speech, the intelligent One, adored by all in the world, shed his physical body on the pratipad of bright fortnight in the month of Vaiśākha of the year Durmukhi; entered at once into his effulgence. This preceptor Śrī Abhinva Śaṅkara or Śaṅkarānanda also known as Navamaṭhīnātha, was the founder of nine Maṭhas—Śṛṅgeri etc. adept in destroying the schools of Madhva, the one who made the idol Varadarāja appear as Lord Śiva to wipe off the predominance of Vaiṣṇavism, adored by the king Bukka, renowned everywhere attained siddhi near Kāṅcipuram. This preceptor is the one who initiated the tradition of Śrividya mudrā."

[names]
sa = [ "काञ्ची ५२ जगद्गुरु श्री-शङ्करानन्देन्द्र सरस्वती आराधना",]
