default_to_none = true
id = "cidambarE_naTarAjasya_rAjasabhAyAM_mahAbhiSEkaH"
tags = [ "TamilnaduTempleFestivals",]
shlokas = """
मौलौ गङ्गा-शशाङ्कौ करचरणतले शीतलाङ्गा भुजङ्गा:
वामे भागे दयार्द्रा हिमगिरिदुहिता चन्दनं सर्वगात्रे।
इत्थं शीतं प्रभूतं तव कनकसभानाथ सोढुं क्व शक्ति:
चित्ते निर्वेदतप्ते यदि भवति न ते नित्यवासो मदीये॥
"""
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
anchor_festival_id = "naTarAjar_An2i_tirumaJcan2am"
offset = 0
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "चिदम्बरे नटराजस्य राजसभायां महाभिषेकः",]
