default_to_none = true
id = "vivEkAnanda~jayantI"
tags = [ "MahapurushaEvents", "CommonFestivals",]
jsonClass = "HinduCalendarEvent"

[timing]
default_to_none = true
month_type = "lunar_month"
month_number = 10
anga_type = "tithi"
anga_number = 22
year_start = 4963
year_start_era = "kali"
jsonClass = "HinduCalendarEventTiming"

[names]
sa = [ "विवेकानन्द-जयन्ती",]
